const table = 'episodes'
exports.seed = knex => {
  return knex(table)
    .insert([{ user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 139034,
    season_no: 5,
    ep_no: 1,
    ep_name: 'RuPaullywood or Bust',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 139035,
    season_no: 5,
    ep_no: 2,
    ep_name: 'Lip Synch Extravaganza Eleganza',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 139036,
    season_no: 5,
    ep_no: 3,
    ep_name: 'Draggle Rock',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 139037,
    season_no: 5,
    ep_no: 4,
    ep_name: 'Black Swan: Why It Gotta Be Black?',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 139038,
    season_no: 5,
    ep_no: 5,
    ep_name: 'Snatch Game',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 139039,
    season_no: 5,
    ep_no: 6,
    ep_name: 'Can I Get An Amen',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 139040,
    season_no: 5,
    ep_no: 7,
    ep_name: 'RuPaul Roast',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 139041,
    season_no: 5,
    ep_no: 8,
    ep_name: 'Scent of a Drag Queen',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 139042,
    season_no: 5,
    ep_no: 9,
    ep_name: 'Drama Queens',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 139043,
    season_no: 5,
    ep_no: 10,
    ep_name: 'Super Troopers',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 139044,
    season_no: 5,
    ep_no: 11,
    ep_name: 'Sugar Ball',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 139045,
    season_no: 5,
    ep_no: 12,
    ep_name: 'The Final Three, Hunty',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 139046,
    season_no: 5,
    ep_no: 13,
    ep_name: 'Countdown to the Crown',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 139047,
    season_no: 5,
    ep_no: 14,
    ep_name: 'Reunited',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 139048,
    season_no: 6,
    ep_no: 1,
    ep_name: 'RuPaul\'s Big Opening',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 139049,
    season_no: 6,
    ep_no: 2,
    ep_name: 'RuPaul\'s Big Opening: Part 2',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 139050,
    season_no: 6,
    ep_no: 3,
    ep_name: 'Scream Queens',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 139051,
    season_no: 6,
    ep_no: 4,
    ep_name: 'Shade: The Rusical',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 139052,
    season_no: 6,
    ep_no: 5,
    ep_name: 'Snatch Game',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 139053,
    season_no: 6,
    ep_no: 6,
    ep_name: 'Oh No She Betta Don\'t',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 139054,
    season_no: 6,
    ep_no: 7,
    ep_name: 'Glamazon by Colorevolution',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 139055,
    season_no: 6,
    ep_no: 8,
    ep_name: 'Drag Queens of Comedy',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 139056,
    season_no: 6,
    ep_no: 9,
    ep_name: 'Queens of Talk',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 139057,
    season_no: 6,
    ep_no: 10,
    ep_name: 'Drag My Wedding',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 139058,
    season_no: 6,
    ep_no: 11,
    ep_name: 'Glitter Ball',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 139059,
    season_no: 6,
    ep_no: 12,
    ep_name: 'Sissy That Walk',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 139060,
    season_no: 6,
    ep_no: 13,
    ep_name: 'Countdown To The Crown',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 139061,
    season_no: 6,
    ep_no: 14,
    ep_name: 'The Finale',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 139062,
    season_no: 7,
    ep_no: 1,
    ep_name: 'Born Naked',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 142523,
    season_no: 7,
    ep_no: 2,
    ep_name: 'Glamazonian Airways',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 142524,
    season_no: 7,
    ep_no: 3,
    ep_name: 'ShakesQueer',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 151565,
    season_no: 7,
    ep_no: 4,
    ep_name: 'Spoof! (There It Is)',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 151566,
    season_no: 7,
    ep_no: 5,
    ep_name: 'The DESPY Awards',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 151567,
    season_no: 7,
    ep_no: 6,
    ep_name: 'Ru Hollywood Stories',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 153943,
    season_no: 7,
    ep_no: 7,
    ep_name: 'Snatch Game',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 153910,
    season_no: 7,
    ep_no: 8,
    ep_name: 'Conjoined Queens',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 153911,
    season_no: 7,
    ep_no: 9,
    ep_name: 'Divine Inspiration',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 155573,
    season_no: 7,
    ep_no: 10,
    ep_name: 'Prancing Queens',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 155574,
    season_no: 7,
    ep_no: 11,
    ep_name: 'Hello, Kitty Girls!',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 155575,
    season_no: 7,
    ep_no: 12,
    ep_name: 'And The Rest Is Drag',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 161224,
    season_no: 7,
    ep_no: 13,
    ep_name: 'Countdown to the Crown',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 161225,
    season_no: 7,
    ep_no: 14,
    ep_name: 'Grand Finale',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 620097,
    season_no: 8,
    ep_no: 1,
    ep_name: 'Keeping It 100!',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 633833,
    season_no: 8,
    ep_no: 2,
    ep_name: 'Bitch Perfect',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 653041,
    season_no: 8,
    ep_no: 3,
    ep_name: 'RuCo\'s Empire',
    watched: true },
  { user_id: 2,
    tv_id: 1526,
    tv_name: 'RuPaul\'s Drag Race',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/8/21309.jpg',
    ep_id: 516023,
    season_no: 8,
    ep_no: 4,
    ep_name: 'New Wave Queens',
    watched: true }, { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1567,
    season_no: 1,
    ep_no: 1,
    ep_name: 'Pilot',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1568,
    season_no: 1,
    ep_no: 2,
    ep_name: 'Home Invasion',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1569,
    season_no: 1,
    ep_no: 3,
    ep_name: 'Murder House',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1570,
    season_no: 1,
    ep_no: 4,
    ep_name: 'Halloween Part 1',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1571,
    season_no: 1,
    ep_no: 5,
    ep_name: 'Halloween Part 2',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1572,
    season_no: 1,
    ep_no: 6,
    ep_name: 'Piggy, Piggy',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1573,
    season_no: 1,
    ep_no: 7,
    ep_name: 'Open House',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1574,
    season_no: 1,
    ep_no: 8,
    ep_name: 'Rubber Man',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1575,
    season_no: 1,
    ep_no: 9,
    ep_name: 'Spooky Little Girl',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1576,
    season_no: 1,
    ep_no: 10,
    ep_name: 'Smoldering Children',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1577,
    season_no: 1,
    ep_no: 11,
    ep_name: 'Birth',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1578,
    season_no: 1,
    ep_no: 12,
    ep_name: 'Afterbirth',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1579,
    season_no: 2,
    ep_no: 1,
    ep_name: 'Welcome to Briarcliff',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1580,
    season_no: 2,
    ep_no: 2,
    ep_name: 'Tricks and Treats',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1581,
    season_no: 2,
    ep_no: 3,
    ep_name: 'Nor\'easter',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1582,
    season_no: 2,
    ep_no: 4,
    ep_name: 'I Am Anne Frank Part 1',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1583,
    season_no: 2,
    ep_no: 5,
    ep_name: 'I Am Anne Frank Part 2',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1584,
    season_no: 2,
    ep_no: 6,
    ep_name: 'Origins of Monstrosity',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1585,
    season_no: 2,
    ep_no: 7,
    ep_name: 'Dark Cousin',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1586,
    season_no: 2,
    ep_no: 8,
    ep_name: 'Unholy Night',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1587,
    season_no: 2,
    ep_no: 9,
    ep_name: 'The Coat Hanger',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1588,
    season_no: 2,
    ep_no: 10,
    ep_name: 'The Name Game',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1589,
    season_no: 2,
    ep_no: 11,
    ep_name: 'Spilt Milk',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1590,
    season_no: 2,
    ep_no: 12,
    ep_name: 'Continuum',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1591,
    season_no: 2,
    ep_no: 13,
    ep_name: 'Madness Ends',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1592,
    season_no: 3,
    ep_no: 1,
    ep_name: 'Bitchcraft',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1593,
    season_no: 3,
    ep_no: 2,
    ep_name: 'Boy Parts',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1594,
    season_no: 3,
    ep_no: 3,
    ep_name: 'The Replacements',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1595,
    season_no: 3,
    ep_no: 4,
    ep_name: 'Fearful Pranks Ensue',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1596,
    season_no: 3,
    ep_no: 5,
    ep_name: 'Burn, Witch. Burn!',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1597,
    season_no: 3,
    ep_no: 6,
    ep_name: 'The Axeman Cometh',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1598,
    season_no: 3,
    ep_no: 7,
    ep_name: 'The Dead',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1599,
    season_no: 3,
    ep_no: 8,
    ep_name: 'The Sacred Taking',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1600,
    season_no: 3,
    ep_no: 9,
    ep_name: 'Head',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1601,
    season_no: 3,
    ep_no: 10,
    ep_name: 'The Magical Delights of Stevie Nicks',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1602,
    season_no: 3,
    ep_no: 11,
    ep_name: 'Protect the Coven',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1603,
    season_no: 3,
    ep_no: 12,
    ep_name: 'Go to Hell',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1604,
    season_no: 3,
    ep_no: 13,
    ep_name: 'The Seven Wonders',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1605,
    season_no: 4,
    ep_no: 1,
    ep_name: 'Monsters Among Us',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1606,
    season_no: 4,
    ep_no: 2,
    ep_name: 'Massacres and Matinees',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1607,
    season_no: 4,
    ep_no: 3,
    ep_name: 'Edward Mordrake (1)',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1608,
    season_no: 4,
    ep_no: 4,
    ep_name: 'Edward Mordrake (2)',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1609,
    season_no: 4,
    ep_no: 5,
    ep_name: 'Pink Cupcakes',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 11226,
    season_no: 4,
    ep_no: 6,
    ep_name: 'Bullseye',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 14881,
    season_no: 4,
    ep_no: 7,
    ep_name: 'Test of Strength',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 14882,
    season_no: 4,
    ep_no: 8,
    ep_name: 'Blood Bath',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 45257,
    season_no: 4,
    ep_no: 9,
    ep_name: 'Tupperware Party Massacre',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 14883,
    season_no: 4,
    ep_no: 10,
    ep_name: 'Orphans',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 14885,
    season_no: 4,
    ep_no: 11,
    ep_name: 'Magical Thinking',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 14886,
    season_no: 4,
    ep_no: 12,
    ep_name: 'Show Stoppers',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 14887,
    season_no: 4,
    ep_no: 13,
    ep_name: 'Curtain Call',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 202975,
    season_no: 5,
    ep_no: 1,
    ep_name: 'Checking In',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 202976,
    season_no: 5,
    ep_no: 2,
    ep_name: 'Chutes and Ladders',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 202977,
    season_no: 5,
    ep_no: 3,
    ep_name: 'Mommy',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 203248,
    season_no: 5,
    ep_no: 4,
    ep_name: 'Devil\'s Night',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 203249,
    season_no: 5,
    ep_no: 5,
    ep_name: 'Room Service',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 203250,
    season_no: 5,
    ep_no: 6,
    ep_name: 'Room 33',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 203251,
    season_no: 5,
    ep_no: 7,
    ep_name: 'Flicker',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 203252,
    season_no: 5,
    ep_no: 8,
    ep_name: 'The Ten Commandments Killer',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 203253,
    season_no: 5,
    ep_no: 9,
    ep_name: 'She Wants Revenge',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 203254,
    season_no: 5,
    ep_no: 10,
    ep_name: 'She Gets Revenge',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 203255,
    season_no: 5,
    ep_no: 11,
    ep_name: 'Battle Royale',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 203256,
    season_no: 5,
    ep_no: 12,
    ep_name: 'Be Our Guest',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 858583,
    season_no: 6,
    ep_no: 1,
    ep_name: 'Chapter 1',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 878021,
    season_no: 6,
    ep_no: 2,
    ep_name: 'Chapter 2',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 878022,
    season_no: 6,
    ep_no: 3,
    ep_name: 'Chapter 3',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 878023,
    season_no: 6,
    ep_no: 4,
    ep_name: 'Chapter 4',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 878024,
    season_no: 6,
    ep_no: 5,
    ep_name: 'Chapter 5',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 878025,
    season_no: 6,
    ep_no: 6,
    ep_name: 'Chapter 6',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 878026,
    season_no: 6,
    ep_no: 7,
    ep_name: 'Chapter 7',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 878027,
    season_no: 6,
    ep_no: 8,
    ep_name: 'Chapter 8',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 878028,
    season_no: 6,
    ep_no: 9,
    ep_name: 'Chapter 9',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 878029,
    season_no: 6,
    ep_no: 10,
    ep_name: 'Chapter 10',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1255009,
    season_no: 7,
    ep_no: 1,
    ep_name: 'Election Night',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1260245,
    season_no: 7,
    ep_no: 2,
    ep_name: 'Don\'t Be Afraid of the Dark',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1260246,
    season_no: 7,
    ep_no: 3,
    ep_name: 'Neighbors from Hell',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1260247,
    season_no: 7,
    ep_no: 4,
    ep_name: '11/9',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1272037,
    season_no: 7,
    ep_no: 5,
    ep_name: 'Holes',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1272038,
    season_no: 7,
    ep_no: 6,
    ep_name: 'Mid-Western Assassin',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1272039,
    season_no: 7,
    ep_no: 7,
    ep_name: 'Valerie Solanas Died for Your Sins: Scumbag',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1272040,
    season_no: 7,
    ep_no: 8,
    ep_name: 'Winter of Our Discontent',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1272041,
    season_no: 7,
    ep_no: 9,
    ep_name: 'Drink the Kool-Aid',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1272042,
    season_no: 7,
    ep_no: 10,
    ep_name: 'Charles (Manson) in Charge',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1277290,
    season_no: 7,
    ep_no: 11,
    ep_name: 'Great Again',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1486732,
    season_no: 8,
    ep_no: 1,
    ep_name: 'The End',
    watched: true },
  { user_id: 2,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1516010,
    season_no: 8,
    ep_no: 2,
    ep_name: 'The Morning After',
    watched: true },{ user_id: 2,
    tv_id: 5967,
    tv_name: 'Insecure',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/80/201348.jpg',
    ep_id: 881339,
    season_no: 1,
    ep_no: 1,
    ep_name: 'Insecure as F**k',
    watched: true },
  { user_id: 2,
    tv_id: 5967,
    tv_name: 'Insecure',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/80/201348.jpg',
    ep_id: 920892,
    season_no: 1,
    ep_no: 2,
    ep_name: 'Messy as F**k',
    watched: true },
  { user_id: 2,
    tv_id: 5967,
    tv_name: 'Insecure',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/80/201348.jpg',
    ep_id: 920893,
    season_no: 1,
    ep_no: 3,
    ep_name: 'Racist as F**k',
    watched: true },
  { user_id: 2,
    tv_id: 5967,
    tv_name: 'Insecure',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/80/201348.jpg',
    ep_id: 920894,
    season_no: 1,
    ep_no: 4,
    ep_name: 'Thirsty as F**k',
    watched: true },
  { user_id: 2,
    tv_id: 5967,
    tv_name: 'Insecure',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/80/201348.jpg',
    ep_id: 935648,
    season_no: 1,
    ep_no: 5,
    ep_name: 'Shady as F**k',
    watched: true },
  { user_id: 2,
    tv_id: 5967,
    tv_name: 'Insecure',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/80/201348.jpg',
    ep_id: 938498,
    season_no: 1,
    ep_no: 6,
    ep_name: 'Guilty as F**k',
    watched: true },
  { user_id: 2,
    tv_id: 5967,
    tv_name: 'Insecure',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/80/201348.jpg',
    ep_id: 948289,
    season_no: 1,
    ep_no: 7,
    ep_name: 'Real as F**k',
    watched: true },
  { user_id: 2,
    tv_id: 5967,
    tv_name: 'Insecure',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/80/201348.jpg',
    ep_id: 948291,
    season_no: 1,
    ep_no: 8,
    ep_name: 'Broken as F**k',
    watched: true },
  { user_id: 2,
    tv_id: 5967,
    tv_name: 'Insecure',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/80/201348.jpg',
    ep_id: 1098889,
    season_no: 2,
    ep_no: 1,
    ep_name: 'Hella Great',
    watched: true },
  { user_id: 2,
    tv_id: 5967,
    tv_name: 'Insecure',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/80/201348.jpg',
    ep_id: 1233372,
    season_no: 2,
    ep_no: 2,
    ep_name: 'Hella Questions',
    watched: true },
  { user_id: 2,
    tv_id: 5967,
    tv_name: 'Insecure',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/80/201348.jpg',
    ep_id: 1241572,
    season_no: 2,
    ep_no: 3,
    ep_name: 'Hella Open',
    watched: true },
  { user_id: 2,
    tv_id: 5967,
    tv_name: 'Insecure',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/80/201348.jpg',
    ep_id: 1241573,
    season_no: 2,
    ep_no: 4,
    ep_name: 'Hella La',
    watched: true },
  { user_id: 2,
    tv_id: 5967,
    tv_name: 'Insecure',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/80/201348.jpg',
    ep_id: 1247552,
    season_no: 2,
    ep_no: 5,
    ep_name: 'Hella Shook',
    watched: true },
  { user_id: 2,
    tv_id: 5967,
    tv_name: 'Insecure',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/80/201348.jpg',
    ep_id: 1247553,
    season_no: 2,
    ep_no: 6,
    ep_name: 'Hella Blows',
    watched: true },
  { user_id: 2,
    tv_id: 5967,
    tv_name: 'Insecure',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/80/201348.jpg',
    ep_id: 1257653,
    season_no: 2,
    ep_no: 7,
    ep_name: 'Hella Disrespectful',
    watched: true },
  { user_id: 2,
    tv_id: 5967,
    tv_name: 'Insecure',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/80/201348.jpg',
    ep_id: 1257654,
    season_no: 2,
    ep_no: 8,
    ep_name: 'Hella Perspective',
    watched: true },
  { user_id: 2,
    tv_id: 5967,
    tv_name: 'Insecure',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/80/201348.jpg',
    ep_id: 1468502,
    season_no: 3,
    ep_no: 1,
    ep_name: 'Better-Like',
    watched: true },
  { user_id: 2,
    tv_id: 5967,
    tv_name: 'Insecure',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/80/201348.jpg',
    ep_id: 1495078,
    season_no: 3,
    ep_no: 2,
    ep_name: 'Familiar-Like',
    watched: true },
  { user_id: 2,
    tv_id: 5967,
    tv_name: 'Insecure',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/80/201348.jpg',
    ep_id: 1507499,
    season_no: 3,
    ep_no: 3,
    ep_name: 'Backwards-Like',
    watched: true },
  { user_id: 2,
    tv_id: 5967,
    tv_name: 'Insecure',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/80/201348.jpg',
    ep_id: 1507500,
    season_no: 3,
    ep_no: 4,
    ep_name: 'Fresh-Like',
    watched: true },
  { user_id: 2,
    tv_id: 5967,
    tv_name: 'Insecure',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/80/201348.jpg',
    ep_id: 1507501,
    season_no: 3,
    ep_no: 5,
    ep_name: 'High-Like',
    watched: true },
  { user_id: 2,
    tv_id: 5967,
    tv_name: 'Insecure',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/80/201348.jpg',
    ep_id: 1510249,
    season_no: 3,
    ep_no: 6,
    ep_name: 'Ready-Like',
    watched: true },{ user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4952,
    season_no: 1,
    ep_no: 1,
    ep_name: 'Winter is Coming',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4953,
    season_no: 1,
    ep_no: 2,
    ep_name: 'The Kingsroad',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4954,
    season_no: 1,
    ep_no: 3,
    ep_name: 'Lord Snow',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4955,
    season_no: 1,
    ep_no: 4,
    ep_name: 'Cripples, Bastards, and Broken Things',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4956,
    season_no: 1,
    ep_no: 5,
    ep_name: 'The Wolf and the Lion',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4957,
    season_no: 1,
    ep_no: 6,
    ep_name: 'A Golden Crown',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4958,
    season_no: 1,
    ep_no: 7,
    ep_name: 'You Win or You Die',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4959,
    season_no: 1,
    ep_no: 8,
    ep_name: 'The Pointy End',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4960,
    season_no: 1,
    ep_no: 9,
    ep_name: 'Baelor',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4961,
    season_no: 1,
    ep_no: 10,
    ep_name: 'Fire and Blood',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4962,
    season_no: 2,
    ep_no: 1,
    ep_name: 'The North Remembers',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4963,
    season_no: 2,
    ep_no: 2,
    ep_name: 'The Night Lands',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4964,
    season_no: 2,
    ep_no: 3,
    ep_name: 'What is Dead May Never Die',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4965,
    season_no: 2,
    ep_no: 4,
    ep_name: 'Garden of Bones',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4966,
    season_no: 2,
    ep_no: 5,
    ep_name: 'The Ghost of Harrenhal',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4967,
    season_no: 2,
    ep_no: 6,
    ep_name: 'The Old Gods and the New',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4968,
    season_no: 2,
    ep_no: 7,
    ep_name: 'A Man Without Honor',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4969,
    season_no: 2,
    ep_no: 8,
    ep_name: 'The Prince of Winterfell',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4970,
    season_no: 2,
    ep_no: 9,
    ep_name: 'Blackwater',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4971,
    season_no: 2,
    ep_no: 10,
    ep_name: 'Valar Morghulis',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4972,
    season_no: 3,
    ep_no: 1,
    ep_name: 'Valar Dohaeris',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4973,
    season_no: 3,
    ep_no: 2,
    ep_name: 'Dark Wings, Dark Words',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4974,
    season_no: 3,
    ep_no: 3,
    ep_name: 'Walk of Punishment',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4975,
    season_no: 3,
    ep_no: 4,
    ep_name: 'And Now His Watch is Ended',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4976,
    season_no: 3,
    ep_no: 5,
    ep_name: 'Kissed by Fire',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4977,
    season_no: 3,
    ep_no: 6,
    ep_name: 'The Climb',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4978,
    season_no: 3,
    ep_no: 7,
    ep_name: 'The Bear and the Maiden Fair',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4979,
    season_no: 3,
    ep_no: 8,
    ep_name: 'Second Sons',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4980,
    season_no: 3,
    ep_no: 9,
    ep_name: 'The Rains of Castamere',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4981,
    season_no: 3,
    ep_no: 10,
    ep_name: 'Mhysa',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4982,
    season_no: 4,
    ep_no: 1,
    ep_name: 'Two Swords',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4983,
    season_no: 4,
    ep_no: 2,
    ep_name: 'The Lion and the Rose',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4984,
    season_no: 4,
    ep_no: 3,
    ep_name: 'Breaker of Chains',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4985,
    season_no: 4,
    ep_no: 4,
    ep_name: 'Oathkeeper',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4986,
    season_no: 4,
    ep_no: 5,
    ep_name: 'First of His Name',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4987,
    season_no: 4,
    ep_no: 6,
    ep_name: 'The Laws of Gods and Men',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4988,
    season_no: 4,
    ep_no: 7,
    ep_name: 'Mockingbird',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4989,
    season_no: 4,
    ep_no: 8,
    ep_name: 'The Mountain and the Viper',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4990,
    season_no: 4,
    ep_no: 9,
    ep_name: 'The Watchers on the Wall',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4991,
    season_no: 4,
    ep_no: 10,
    ep_name: 'The Children',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 116522,
    season_no: 5,
    ep_no: 1,
    ep_name: 'The Wars to Come',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 144328,
    season_no: 5,
    ep_no: 2,
    ep_name: 'The House of Black and White',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 144329,
    season_no: 5,
    ep_no: 3,
    ep_name: 'High Sparrow',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 144330,
    season_no: 5,
    ep_no: 4,
    ep_name: 'Sons of the Harpy',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 151777,
    season_no: 5,
    ep_no: 5,
    ep_name: 'Kill the Boy',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 152766,
    season_no: 5,
    ep_no: 6,
    ep_name: 'Unbowed, Unbent, Unbroken',
    watched: true },
  { user_id: 2,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 153327,
    season_no: 5,
    ep_no: 7,
    ep_name: 'The Gift',
    watched: true },
    { user_id: 2,
    tv_id: 128,
    tv_name: 'Jane the Virgin',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/53/132727.jpg',
    ep_id: 10381,
    season_no: 1,
    ep_no: 1,
    ep_name: 'Chapter One',
    watched: true },
  { user_id: 2,
    tv_id: 128,
    tv_name: 'Jane the Virgin',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/53/132727.jpg',
    ep_id: 10382,
    season_no: 1,
    ep_no: 2,
    ep_name: 'Chapter Two',
    watched: true },
  { user_id: 2,
    tv_id: 128,
    tv_name: 'Jane the Virgin',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/53/132727.jpg',
    ep_id: 10383,
    season_no: 1,
    ep_no: 3,
    ep_name: 'Chapter Three',
    watched: true },
  { user_id: 2,
    tv_id: 128,
    tv_name: 'Jane the Virgin',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/53/132727.jpg',
    ep_id: 10384,
    season_no: 1,
    ep_no: 4,
    ep_name: 'Chapter Four',
    watched: true },
  { user_id: 2,
    tv_id: 128,
    tv_name: 'Jane the Virgin',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/53/132727.jpg',
    ep_id: 10385,
    season_no: 1,
    ep_no: 5,
    ep_name: 'Chapter Five',
    watched: true },
  { user_id: 2,
    tv_id: 128,
    tv_name: 'Jane the Virgin',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/53/132727.jpg',
    ep_id: 32267,
    season_no: 1,
    ep_no: 6,
    ep_name: 'Chapter Six',
    watched: true },
  { user_id: 2,
    tv_id: 128,
    tv_name: 'Jane the Virgin',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/53/132727.jpg',
    ep_id: 40956,
    season_no: 1,
    ep_no: 7,
    ep_name: 'Chapter Seven',
    watched: true },
  { user_id: 2,
    tv_id: 128,
    tv_name: 'Jane the Virgin',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/53/132727.jpg',
    ep_id: 40957,
    season_no: 1,
    ep_no: 8,
    ep_name: 'Chapter Eight',
    watched: true },
  { user_id: 2,
    tv_id: 128,
    tv_name: 'Jane the Virgin',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/53/132727.jpg',
    ep_id: 45284,
    season_no: 1,
    ep_no: 9,
    ep_name: 'Chapter Nine',
    watched: true },
  { user_id: 2,
    tv_id: 128,
    tv_name: 'Jane the Virgin',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/53/132727.jpg',
    ep_id: 45285,
    season_no: 1,
    ep_no: 10,
    ep_name: 'Chapter Ten',
    watched: true },
  { user_id: 2,
    tv_id: 128,
    tv_name: 'Jane the Virgin',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/53/132727.jpg',
    ep_id: 109665,
    season_no: 1,
    ep_no: 11,
    ep_name: 'Chapter Eleven',
    watched: true },
  { user_id: 2,
    tv_id: 128,
    tv_name: 'Jane the Virgin',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/53/132727.jpg',
    ep_id: 109666,
    season_no: 1,
    ep_no: 12,
    ep_name: 'Chapter Twelve',
    watched: true },
  { user_id: 2,
    tv_id: 128,
    tv_name: 'Jane the Virgin',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/53/132727.jpg',
    ep_id: 122996,
    season_no: 1,
    ep_no: 13,
    ep_name: 'Chapter Thirteen',
    watched: true },
  { user_id: 2,
    tv_id: 128,
    tv_name: 'Jane the Virgin',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/53/132727.jpg',
    ep_id: 128612,
    season_no: 1,
    ep_no: 14,
    ep_name: 'Chapter Fourteen',
    watched: true },
  { user_id: 2,
    tv_id: 128,
    tv_name: 'Jane the Virgin',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/53/132727.jpg',
    ep_id: 128873,
    season_no: 1,
    ep_no: 15,
    ep_name: 'Chapter Fifteen',
    watched: true },
  { user_id: 2,
    tv_id: 128,
    tv_name: 'Jane the Virgin',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/53/132727.jpg',
    ep_id: 128874,
    season_no: 1,
    ep_no: 16,
    ep_name: 'Chapter Sixteen',
    watched: true },
  { user_id: 2,
    tv_id: 128,
    tv_name: 'Jane the Virgin',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/53/132727.jpg',
    ep_id: 145549,
    season_no: 1,
    ep_no: 17,
    ep_name: 'Chapter Seventeen',
    watched: true },
  { user_id: 2,
    tv_id: 128,
    tv_name: 'Jane the Virgin',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/53/132727.jpg',
    ep_id: 145550,
    season_no: 1,
    ep_no: 18,
    ep_name: 'Chapter Eighteen',
    watched: true },
  { user_id: 2,
    tv_id: 128,
    tv_name: 'Jane the Virgin',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/53/132727.jpg',
    ep_id: 145551,
    season_no: 1,
    ep_no: 19,
    ep_name: 'Chapter Nineteen',
    watched: true },
  { user_id: 2,
    tv_id: 128,
    tv_name: 'Jane the Virgin',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/53/132727.jpg',
    ep_id: 145552,
    season_no: 1,
    ep_no: 20,
    ep_name: 'Chapter Twenty',
    watched: true },
  { user_id: 2,
    tv_id: 128,
    tv_name: 'Jane the Virgin',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/53/132727.jpg',
    ep_id: 145555,
    season_no: 1,
    ep_no: 21,
    ep_name: 'Chapter Twenty-One',
    watched: true },
  { user_id: 2,
    tv_id: 128,
    tv_name: 'Jane the Virgin',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/53/132727.jpg',
    ep_id: 145553,
    season_no: 1,
    ep_no: 22,
    ep_name: 'Chapter Twenty-Two',
    watched: true },
  { user_id: 2,
    tv_id: 128,
    tv_name: 'Jane the Virgin',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/53/132727.jpg',
    ep_id: 182154,
    season_no: 2,
    ep_no: 1,
    ep_name: 'Chapter Twenty-Three',
    watched: true },
  { user_id: 2,
    tv_id: 128,
    tv_name: 'Jane the Virgin',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/53/132727.jpg',
    ep_id: 260919,
    season_no: 2,
    ep_no: 2,
    ep_name: 'Chapter Twenty-Four',
    watched: true },
  { user_id: 2,
    tv_id: 128,
    tv_name: 'Jane the Virgin',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/53/132727.jpg',
    ep_id: 260920,
    season_no: 2,
    ep_no: 3,
    ep_name: 'Chapter Twenty-Five',
    watched: true },
  { user_id: 2,
    tv_id: 128,
    tv_name: 'Jane the Virgin',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/53/132727.jpg',
    ep_id: 260921,
    season_no: 2,
    ep_no: 4,
    ep_name: 'Chapter Twenty-Six',
    watched: true },
  { user_id: 2,
    tv_id: 128,
    tv_name: 'Jane the Virgin',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/53/132727.jpg',
    ep_id: 365916,
    season_no: 2,
    ep_no: 5,
    ep_name: 'Chapter Twenty-Seven',
    watched: true },
  { user_id: 2,
    tv_id: 128,
    tv_name: 'Jane the Virgin',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/53/132727.jpg',
    ep_id: 415085,
    season_no: 2,
    ep_no: 6,
    ep_name: 'Chapter Twenty-Eight',
    watched: true },
  { user_id: 2,
    tv_id: 128,
    tv_name: 'Jane the Virgin',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/53/132727.jpg',
    ep_id: 431918,
    season_no: 2,
    ep_no: 7,
    ep_name: 'Chapter Twenty-Nine',
    watched: true },
  { user_id: 2,
    tv_id: 128,
    tv_name: 'Jane the Virgin',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/53/132727.jpg',
    ep_id: 488562,
    season_no: 2,
    ep_no: 8,
    ep_name: 'Chapter Thirty',
    watched: true },
  { user_id: 2,
    tv_id: 128,
    tv_name: 'Jane the Virgin',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/53/132727.jpg',
    ep_id: 526412,
    season_no: 2,
    ep_no: 9,
    ep_name: 'Chapter Thirty-One',
    watched: true },
  { user_id: 2,
    tv_id: 128,
    tv_name: 'Jane the Virgin',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/53/132727.jpg',
    ep_id: 573859,
    season_no: 2,
    ep_no: 10,
    ep_name: 'Chapter Thirty-Two',
    watched: true },
  { user_id: 2,
    tv_id: 128,
    tv_name: 'Jane the Virgin',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/53/132727.jpg',
    ep_id: 579815,
    season_no: 2,
    ep_no: 11,
    ep_name: 'Chapter Thirty-Three',
    watched: true },
  { user_id: 2,
    tv_id: 128,
    tv_name: 'Jane the Virgin',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/53/132727.jpg',
    ep_id: 600745,
    season_no: 2,
    ep_no: 12,
    ep_name: 'Chapter Thirty-Four',
    watched: true },
  { user_id: 2,
    tv_id: 128,
    tv_name: 'Jane the Virgin',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/53/132727.jpg',
    ep_id: 611610,
    season_no: 2,
    ep_no: 13,
    ep_name: 'Chapter Thirty-Five',
    watched: true },
  { user_id: 2,
    tv_id: 128,
    tv_name: 'Jane the Virgin',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/53/132727.jpg',
    ep_id: 622452,
    season_no: 2,
    ep_no: 14,
    ep_name: 'Chapter Thirty-Six',
    watched: true },
  { user_id: 2,
    tv_id: 128,
    tv_name: 'Jane the Virgin',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/53/132727.jpg',
    ep_id: 636782,
    season_no: 2,
    ep_no: 15,
    ep_name: 'Chapter Thirty-Seven',
    watched: true },
  { user_id: 2,
    tv_id: 128,
    tv_name: 'Jane the Virgin',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/53/132727.jpg',
    ep_id: 647357,
    season_no: 2,
    ep_no: 16,
    ep_name: 'Chapter Thirty-Eight',
    watched: true },
  { user_id: 2,
    tv_id: 128,
    tv_name: 'Jane the Virgin',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/53/132727.jpg',
    ep_id: 647358,
    season_no: 2,
    ep_no: 17,
    ep_name: 'Chapter Thirty-Nine',
    watched: true },
  { user_id: 2,
    tv_id: 128,
    tv_name: 'Jane the Virgin',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/53/132727.jpg',
    ep_id: 647359,
    season_no: 2,
    ep_no: 18,
    ep_name: 'Chapter Forty',
    watched: true },
  { user_id: 2,
    tv_id: 128,
    tv_name: 'Jane the Virgin',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/53/132727.jpg',
    ep_id: 647360,
    season_no: 2,
    ep_no: 19,
    ep_name: 'Chapter Forty-One',
    watched: true }
    ])
    .then(() => {
      return knex.raw(`SELECT setval('${table}_id_seq', (SELECT MAX(id) FROM ${table}));`)
    })
};
