const table = 'episodes'
exports.seed = knex => {
  return knex(table)
    .insert([{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 2010,
  season_no: 1,
  ep_no: 1,
  ep_name: 'Pilot',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 2011,
  season_no: 1,
  ep_no: 2,
  ep_name: 'The Tagger',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 2012,
  season_no: 1,
  ep_no: 3,
  ep_name: 'The Slump',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 2013,
  season_no: 1,
  ep_no: 4,
  ep_name: 'M.E. Time',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 2014,
  season_no: 1,
  ep_no: 5,
  ep_name: 'The Vulture',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 2015,
  season_no: 1,
  ep_no: 6,
  ep_name: 'Halloween',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 2016,
  season_no: 1,
  ep_no: 7,
  ep_name: '48 Hours',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 2017,
  season_no: 1,
  ep_no: 8,
  ep_name: 'Old School',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 2018,
  season_no: 1,
  ep_no: 9,
  ep_name: 'Sal\'s Pizza',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 2019,
  season_no: 1,
  ep_no: 10,
  ep_name: 'Thanksgiving',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 2020,
  season_no: 1,
  ep_no: 11,
  ep_name: 'Christmas',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 2021,
  season_no: 1,
  ep_no: 12,
  ep_name: 'Pontiac Bandit',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 2022,
  season_no: 1,
  ep_no: 13,
  ep_name: 'The Bet',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 2023,
  season_no: 1,
  ep_no: 14,
  ep_name: 'The Ebony Falcon',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 2024,
  season_no: 1,
  ep_no: 15,
  ep_name: 'Operation: Broken Feather',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 2025,
  season_no: 1,
  ep_no: 16,
  ep_name: 'The Party',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 2026,
  season_no: 1,
  ep_no: 17,
  ep_name: 'Full Boyle',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 2027,
  season_no: 1,
  ep_no: 18,
  ep_name: 'The Apartment',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 2028,
  season_no: 1,
  ep_no: 19,
  ep_name: 'Tactical Village',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 2029,
  season_no: 1,
  ep_no: 20,
  ep_name: 'Fancy Brudgom',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 2030,
  season_no: 1,
  ep_no: 21,
  ep_name: 'Unsolvable',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 2031,
  season_no: 1,
  ep_no: 22,
  ep_name: 'Charges and Specs',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 2032,
  season_no: 2,
  ep_no: 1,
  ep_name: 'Undercover',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 2033,
  season_no: 2,
  ep_no: 2,
  ep_name: 'Chocolate Milk',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 2034,
  season_no: 2,
  ep_no: 3,
  ep_name: 'The Jimmy Jab Games',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 14051,
  season_no: 2,
  ep_no: 4,
  ep_name: 'Halloween II',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 14052,
  season_no: 2,
  ep_no: 5,
  ep_name: 'The Mole',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 14545,
  season_no: 2,
  ep_no: 6,
  ep_name: 'Jake and Sophia',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 39443,
  season_no: 2,
  ep_no: 7,
  ep_name: 'Lockdown',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 39444,
  season_no: 2,
  ep_no: 8,
  ep_name: 'USPIS',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 44365,
  season_no: 2,
  ep_no: 9,
  ep_name: 'The Road Trip',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 45777,
  season_no: 2,
  ep_no: 10,
  ep_name: 'The Pontiac Bandit Returns',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 50183,
  season_no: 2,
  ep_no: 11,
  ep_name: 'Stakeout',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 58257,
  season_no: 2,
  ep_no: 12,
  ep_name: 'Beach House',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 92045,
  season_no: 2,
  ep_no: 13,
  ep_name: 'Payback',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 108510,
  season_no: 2,
  ep_no: 14,
  ep_name: 'Defense Rests',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 117726,
  season_no: 2,
  ep_no: 15,
  ep_name: 'Windbreaker City',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 122944,
  season_no: 2,
  ep_no: 16,
  ep_name: 'The Wednesday Incident',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 128944,
  season_no: 2,
  ep_no: 17,
  ep_name: 'Boyle-Linetti Wedding',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 139657,
  season_no: 2,
  ep_no: 18,
  ep_name: 'Captain Peralta',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 141513,
  season_no: 2,
  ep_no: 19,
  ep_name: 'Sabotage',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 144419,
  season_no: 2,
  ep_no: 20,
  ep_name: 'AC/DC',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 144420,
  season_no: 2,
  ep_no: 21,
  ep_name: 'Det. Dave Majors',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 144421,
  season_no: 2,
  ep_no: 22,
  ep_name: 'The Chopper',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 151671,
  season_no: 2,
  ep_no: 23,
  ep_name: 'Johnny and Dora',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 182392,
  season_no: 3,
  ep_no: 1,
  ep_name: 'New Captain',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 185606,
  season_no: 3,
  ep_no: 2,
  ep_name: 'The Funeral',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 236848,
  season_no: 3,
  ep_no: 3,
  ep_name: 'Boyle\'s Hunch',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 277905,
  season_no: 3,
  ep_no: 4,
  ep_name: 'The Oolong Slayer',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 313290,
  season_no: 3,
  ep_no: 5,
  ep_name: 'Halloween III',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 378141,
  season_no: 3,
  ep_no: 6,
  ep_name: 'Into the Woods',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 385062,
  season_no: 3,
  ep_no: 7,
  ep_name: 'The Mattress',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 2035,
  season_no: 3,
  ep_no: 8,
  ep_name: 'Ava',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 443338,
  season_no: 3,
  ep_no: 9,
  ep_name: 'The Swedes',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 473784,
  season_no: 3,
  ep_no: 10,
  ep_name: 'Yippie Kayak',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 529664,
  season_no: 3,
  ep_no: 11,
  ep_name: 'Hostage Situation',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 550601,
  season_no: 3,
  ep_no: 12,
  ep_name: '9 Days',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 558571,
  season_no: 3,
  ep_no: 13,
  ep_name: 'The Cruise',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 563475,
  season_no: 3,
  ep_no: 14,
  ep_name: 'Karen Peralta',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 573792,
  season_no: 3,
  ep_no: 15,
  ep_name: 'The 9-8',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 589447,
  season_no: 3,
  ep_no: 16,
  ep_name: 'House Mouses',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 594135,
  season_no: 3,
  ep_no: 17,
  ep_name: 'Adrian Pimento',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 608802,
  season_no: 3,
  ep_no: 18,
  ep_name: 'Cheddar',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 622396,
  season_no: 3,
  ep_no: 19,
  ep_name: 'Terry Kitties',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 636787,
  season_no: 3,
  ep_no: 20,
  ep_name: 'Paranoia',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 636788,
  season_no: 3,
  ep_no: 21,
  ep_name: 'Maximum Security',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 636789,
  season_no: 3,
  ep_no: 22,
  ep_name: 'The Bureau',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 636790,
  season_no: 3,
  ep_no: 23,
  ep_name: 'Greg and Larry',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 835409,
  season_no: 4,
  ep_no: 1,
  ep_name: 'Coral Palms, Part 1',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 895548,
  season_no: 4,
  ep_no: 2,
  ep_name: 'Coral Palms, Part 2',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 895549,
  season_no: 4,
  ep_no: 3,
  ep_name: 'Coral Palms, Part 3',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 893359,
  season_no: 4,
  ep_no: 4,
  ep_name: 'The Night Shift',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 944750,
  season_no: 4,
  ep_no: 5,
  ep_name: 'Halloween IV',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 974745,
  season_no: 4,
  ep_no: 6,
  ep_name: 'Monster in the Closet',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 979324,
  season_no: 4,
  ep_no: 7,
  ep_name: 'Mr. Santiago',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 979805,
  season_no: 4,
  ep_no: 8,
  ep_name: 'Skyfire Cycle',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 952563,
  season_no: 4,
  ep_no: 9,
  ep_name: 'The Overmining',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 986268,
  season_no: 4,
  ep_no: 10,
  ep_name: 'Captain Latvia',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 1007920,
  season_no: 4,
  ep_no: 11,
  ep_name: 'The Fugitive, Part 1',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 1008010,
  season_no: 4,
  ep_no: 12,
  ep_name: 'The Fugitive, Part 2',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 1038751,
  season_no: 4,
  ep_no: 13,
  ep_name: 'The Audit',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 1096395,
  season_no: 4,
  ep_no: 14,
  ep_name: 'Serve & Protect',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 1096396,
  season_no: 4,
  ep_no: 15,
  ep_name: 'The Last Ride',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 1096398,
  season_no: 4,
  ep_no: 16,
  ep_name: 'Moo Moo',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 1053163,
  season_no: 4,
  ep_no: 17,
  ep_name: 'Cop-Con',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 1096399,
  season_no: 4,
  ep_no: 18,
  ep_name: 'Chasing Amy',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 1096400,
  season_no: 4,
  ep_no: 19,
  ep_name: 'Your Honor',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 1096401,
  season_no: 4,
  ep_no: 20,
  ep_name: 'The Slaughterhouse',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 1096402,
  season_no: 4,
  ep_no: 21,
  ep_name: 'The Bank Job',
  watched: true },
{ user_id: 3,
  tv_id: 49,
  tv_name: 'Brooklyn Nine-Nine',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/128/321052.jpg',
  ep_id: 1223230,
  season_no: 5,
  ep_no: 1,
  ep_name: 'The Big House Pt. 1',
  watched: true }, { user_id: 3,
  tv_id: 919,
  tv_name: 'Attack on Titan',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/6/16094.jpg',
  ep_id: 86778,
  season_no: 1,
  ep_no: 1,
  ep_name: 'To You, in 2000 Years - The Fall of Shiganshina (1)',
  watched: true },
{ user_id: 3,
  tv_id: 919,
  tv_name: 'Attack on Titan',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/6/16094.jpg',
  ep_id: 86779,
  season_no: 1,
  ep_no: 2,
  ep_name: 'That Day - The Fall of Shiganshina (2)',
  watched: true },
{ user_id: 3,
  tv_id: 919,
  tv_name: 'Attack on Titan',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/6/16094.jpg',
  ep_id: 86780,
  season_no: 1,
  ep_no: 3,
  ep_name: 'A Dim Light Amid Despair - Humanity\'s Comeback (1)',
  watched: true },
{ user_id: 3,
  tv_id: 919,
  tv_name: 'Attack on Titan',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/6/16094.jpg',
  ep_id: 86781,
  season_no: 1,
  ep_no: 4,
  ep_name:
   'The Night of the Closing Ceremony - Humanity\'s Comeback (2)',
  watched: true },
{ user_id: 3,
  tv_id: 919,
  tv_name: 'Attack on Titan',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/6/16094.jpg',
  ep_id: 86782,
  season_no: 1,
  ep_no: 5,
  ep_name: 'First Battle - The Struggle for Trost (1)',
  watched: true },
{ user_id: 3,
  tv_id: 919,
  tv_name: 'Attack on Titan',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/6/16094.jpg',
  ep_id: 86783,
  season_no: 1,
  ep_no: 6,
  ep_name: 'The World the Girl Saw - The Struggle for Trost (2)',
  watched: true },
{ user_id: 3,
  tv_id: 919,
  tv_name: 'Attack on Titan',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/6/16094.jpg',
  ep_id: 86784,
  season_no: 1,
  ep_no: 7,
  ep_name: 'Small Blade - The Struggle for Trost (3)',
  watched: true },
{ user_id: 3,
  tv_id: 919,
  tv_name: 'Attack on Titan',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/6/16094.jpg',
  ep_id: 86785,
  season_no: 1,
  ep_no: 8,
  ep_name: 'I Can Hear His Heartbeat - The Struggle for Trost (4)',
  watched: true },
{ user_id: 3,
  tv_id: 919,
  tv_name: 'Attack on Titan',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/6/16094.jpg',
  ep_id: 86786,
  season_no: 1,
  ep_no: 9,
  ep_name: 'Whereabouts of His Left Arm - The Struggle for Trost (5)',
  watched: true },
{ user_id: 3,
  tv_id: 919,
  tv_name: 'Attack on Titan',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/6/16094.jpg',
  ep_id: 86787,
  season_no: 1,
  ep_no: 10,
  ep_name: 'Response - The Struggle for Trost (6)',
  watched: true },
{ user_id: 3,
  tv_id: 919,
  tv_name: 'Attack on Titan',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/6/16094.jpg',
  ep_id: 86788,
  season_no: 1,
  ep_no: 11,
  ep_name: 'Idol - The Struggle for Trost (7)',
  watched: true },
{ user_id: 3,
  tv_id: 919,
  tv_name: 'Attack on Titan',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/6/16094.jpg',
  ep_id: 86789,
  season_no: 1,
  ep_no: 12,
  ep_name: 'Wound - The Struggle for Trost (8)',
  watched: true },
{ user_id: 3,
  tv_id: 919,
  tv_name: 'Attack on Titan',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/6/16094.jpg',
  ep_id: 86790,
  season_no: 1,
  ep_no: 13,
  ep_name: 'Primal Desire - The Struggle for Trost (9)',
  watched: true },
{ user_id: 3,
  tv_id: 919,
  tv_name: 'Attack on Titan',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/6/16094.jpg',
  ep_id: 86791,
  season_no: 1,
  ep_no: 14,
  ep_name: 'Can\'t Look Into His Eyes - Eve of the Counterattack (1)',
  watched: true },
{ user_id: 3,
  tv_id: 919,
  tv_name: 'Attack on Titan',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/6/16094.jpg',
  ep_id: 86796,
  season_no: 1,
  ep_no: 19,
  ep_name: 'Bite - The 57th Exterior Scouting Mission (3)',
  watched: true },
{ user_id: 3,
  tv_id: 919,
  tv_name: 'Attack on Titan',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/6/16094.jpg',
  ep_id: 86797,
  season_no: 1,
  ep_no: 20,
  ep_name: 'Erwin Smith - The 57th Exterior Scouting Mission (4)',
  watched: true },
{ user_id: 3,
  tv_id: 919,
  tv_name: 'Attack on Titan',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/6/16094.jpg',
  ep_id: 86798,
  season_no: 1,
  ep_no: 21,
  ep_name: 'Crushing Blow - The 57th Exterior Scouting Mission (5)',
  watched: true },
{ user_id: 3,
  tv_id: 919,
  tv_name: 'Attack on Titan',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/6/16094.jpg',
  ep_id: 86799,
  season_no: 1,
  ep_no: 22,
  ep_name: 'The Defeated - The 57th Exterior Scouting Mission (6)',
  watched: true },
{ user_id: 3,
  tv_id: 919,
  tv_name: 'Attack on Titan',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/6/16094.jpg',
  ep_id: 86800,
  season_no: 1,
  ep_no: 23,
  ep_name: 'Smile - Assault on Stohess (1)',
  watched: true },
{ user_id: 3,
  tv_id: 919,
  tv_name: 'Attack on Titan',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/6/16094.jpg',
  ep_id: 86801,
  season_no: 1,
  ep_no: 24,
  ep_name: 'Mercy - Assault on Stohess (2)',
  watched: true },
{ user_id: 3,
  tv_id: 919,
  tv_name: 'Attack on Titan',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/6/16094.jpg',
  ep_id: 86802,
  season_no: 1,
  ep_no: 25,
  ep_name: 'Wall: Raid on Stohess District (3)',
  watched: true },
{ user_id: 3,
  tv_id: 919,
  tv_name: 'Attack on Titan',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/6/16094.jpg',
  ep_id: 1065098,
  season_no: 2,
  ep_no: 1,
  ep_name: 'Beast Titan',
  watched: true },
{ user_id: 3,
  tv_id: 919,
  tv_name: 'Attack on Titan',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/6/16094.jpg',
  ep_id: 1105636,
  season_no: 2,
  ep_no: 2,
  ep_name: 'I\'m Home',
  watched: true },
{ user_id: 3,
  tv_id: 919,
  tv_name: 'Attack on Titan',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/6/16094.jpg',
  ep_id: 1105637,
  season_no: 2,
  ep_no: 3,
  ep_name: 'Southwestward',
  watched: true },
{ user_id: 3,
  tv_id: 919,
  tv_name: 'Attack on Titan',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/6/16094.jpg',
  ep_id: 1105638,
  season_no: 2,
  ep_no: 4,
  ep_name: 'Soldier',
  watched: true },
{ user_id: 3,
  tv_id: 919,
  tv_name: 'Attack on Titan',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/6/16094.jpg',
  ep_id: 1151406,
  season_no: 2,
  ep_no: 5,
  ep_name: 'Historia',
  watched: true },
{ user_id: 3,
  tv_id: 919,
  tv_name: 'Attack on Titan',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/6/16094.jpg',
  ep_id: 1151407,
  season_no: 2,
  ep_no: 6,
  ep_name: 'Warrior',
  watched: true },
  { user_id: 3,
    tv_id: 12036,
    tv_name: 'Altered Carbon',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/358572.jpg',
    ep_id: 1367519,
    season_no: 1,
    ep_no: 1,
    ep_name: 'Out of the Past',
    watched: true },
  { user_id: 3,
    tv_id: 12036,
    tv_name: 'Altered Carbon',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/358572.jpg',
    ep_id: 1389593,
    season_no: 1,
    ep_no: 2,
    ep_name: 'Fallen Angel',
    watched: true },
  { user_id: 3,
    tv_id: 12036,
    tv_name: 'Altered Carbon',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/358572.jpg',
    ep_id: 1389596,
    season_no: 1,
    ep_no: 3,
    ep_name: 'In a Lonely Place',
    watched: true },
  { user_id: 3,
    tv_id: 12036,
    tv_name: 'Altered Carbon',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/358572.jpg',
    ep_id: 1389597,
    season_no: 1,
    ep_no: 4,
    ep_name: 'Force of Evil',
    watched: true },
  { user_id: 3,
    tv_id: 12036,
    tv_name: 'Altered Carbon',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/358572.jpg',
    ep_id: 1389598,
    season_no: 1,
    ep_no: 5,
    ep_name: 'The Wrong Man',
    watched: true },
    { user_id: 3,
  tv_id: 1440,
  tv_name: 'Tokyo Ghoul',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/8/20809.jpg',
  ep_id: 129605,
  season_no: 1,
  ep_no: 1,
  ep_name: 'Tragedy',
  watched: true },
{ user_id: 3,
  tv_id: 1440,
  tv_name: 'Tokyo Ghoul',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/8/20809.jpg',
  ep_id: 129606,
  season_no: 1,
  ep_no: 2,
  ep_name: 'Incubation',
  watched: true },
{ user_id: 3,
  tv_id: 1440,
  tv_name: 'Tokyo Ghoul',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/8/20809.jpg',
  ep_id: 129607,
  season_no: 1,
  ep_no: 3,
  ep_name: 'Dove',
  watched: true },
{ user_id: 3,
  tv_id: 1440,
  tv_name: 'Tokyo Ghoul',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/8/20809.jpg',
  ep_id: 129608,
  season_no: 1,
  ep_no: 4,
  ep_name: 'Supper',
  watched: true },
{ user_id: 3,
  tv_id: 1440,
  tv_name: 'Tokyo Ghoul',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/8/20809.jpg',
  ep_id: 129609,
  season_no: 1,
  ep_no: 5,
  ep_name: 'Scars',
  watched: true },
{ user_id: 3,
  tv_id: 1440,
  tv_name: 'Tokyo Ghoul',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/8/20809.jpg',
  ep_id: 129610,
  season_no: 1,
  ep_no: 6,
  ep_name: 'Cloudburst',
  watched: true },
{ user_id: 3,
  tv_id: 1440,
  tv_name: 'Tokyo Ghoul',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/8/20809.jpg',
  ep_id: 129611,
  season_no: 1,
  ep_no: 7,
  ep_name: 'Captivity',
  watched: true },
{ user_id: 3,
  tv_id: 1440,
  tv_name: 'Tokyo Ghoul',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/8/20809.jpg',
  ep_id: 129612,
  season_no: 1,
  ep_no: 8,
  ep_name: 'Circular',
  watched: true },
{ user_id: 3,
  tv_id: 1440,
  tv_name: 'Tokyo Ghoul',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/8/20809.jpg',
  ep_id: 129613,
  season_no: 1,
  ep_no: 9,
  ep_name: 'Birdcage',
  watched: true },
{ user_id: 3,
  tv_id: 1440,
  tv_name: 'Tokyo Ghoul',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/8/20809.jpg',
  ep_id: 129614,
  season_no: 1,
  ep_no: 10,
  ep_name: 'Aogiri',
  watched: true },
{ user_id: 3,
  tv_id: 1440,
  tv_name: 'Tokyo Ghoul',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/8/20809.jpg',
  ep_id: 129615,
  season_no: 1,
  ep_no: 11,
  ep_name: 'High Spirits',
  watched: true },
{ user_id: 3,
  tv_id: 1440,
  tv_name: 'Tokyo Ghoul',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/8/20809.jpg',
  ep_id: 129616,
  season_no: 1,
  ep_no: 12,
  ep_name: 'Ghoul',
  watched: true },
{ user_id: 3,
  tv_id: 1440,
  tv_name: 'Tokyo Ghoul',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/8/20809.jpg',
  ep_id: 129617,
  season_no: 2,
  ep_no: 1,
  ep_name: 'New Surge',
  watched: true },
{ user_id: 3,
  tv_id: 1440,
  tv_name: 'Tokyo Ghoul',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/8/20809.jpg',
  ep_id: 129618,
  season_no: 2,
  ep_no: 2,
  ep_name: 'Dancing Flowers',
  watched: true },
{ user_id: 3,
  tv_id: 1440,
  tv_name: 'Tokyo Ghoul',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/8/20809.jpg',
  ep_id: 129619,
  season_no: 2,
  ep_no: 3,
  ep_name: 'Hangman',
  watched: true },
{ user_id: 3,
  tv_id: 1440,
  tv_name: 'Tokyo Ghoul',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/8/20809.jpg',
  ep_id: 129620,
  season_no: 2,
  ep_no: 4,
  ep_name: 'Deeper Layers',
  watched: true },
  { user_id: 3,
  tv_id: 2790,
  tv_name: 'The Good Place',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/165/414887.jpg',
  ep_id: 934977,
  season_no: 1,
  ep_no: 1,
  ep_name: 'Everything Is Fine',
  watched: true },
{ user_id: 3,
  tv_id: 2790,
  tv_name: 'The Good Place',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/165/414887.jpg',
  ep_id: 834857,
  season_no: 1,
  ep_no: 2,
  ep_name: 'Flying',
  watched: true },
{ user_id: 3,
  tv_id: 2790,
  tv_name: 'The Good Place',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/165/414887.jpg',
  ep_id: 834858,
  season_no: 1,
  ep_no: 3,
  ep_name: 'Tahani Al-Jamil',
  watched: true },
{ user_id: 3,
  tv_id: 2790,
  tv_name: 'The Good Place',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/165/414887.jpg',
  ep_id: 911462,
  season_no: 1,
  ep_no: 4,
  ep_name: 'Jason Mendoza',
  watched: true },
{ user_id: 3,
  tv_id: 2790,
  tv_name: 'The Good Place',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/165/414887.jpg',
  ep_id: 911463,
  season_no: 1,
  ep_no: 5,
  ep_name: 'Category 55 Emergency Doomsday Crisis',
  watched: true },
{ user_id: 3,
  tv_id: 2790,
  tv_name: 'The Good Place',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/165/414887.jpg',
  ep_id: 923234,
  season_no: 1,
  ep_no: 6,
  ep_name: 'What We Owe to Each Other',
  watched: true },
{ user_id: 3,
  tv_id: 2790,
  tv_name: 'The Good Place',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/165/414887.jpg',
  ep_id: 923235,
  season_no: 1,
  ep_no: 7,
  ep_name: 'The Eternal Shriek',
  watched: true },
{ user_id: 3,
  tv_id: 2790,
  tv_name: 'The Good Place',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/165/414887.jpg',
  ep_id: 923236,
  season_no: 1,
  ep_no: 8,
  ep_name: 'Most Improved Player',
  watched: true },
{ user_id: 3,
  tv_id: 2790,
  tv_name: 'The Good Place',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/165/414887.jpg',
  ep_id: 923237,
  season_no: 1,
  ep_no: 9,
  ep_name: '...Someone Like Me as a Member',
  watched: true },
{ user_id: 3,
  tv_id: 2790,
  tv_name: 'The Good Place',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/165/414887.jpg',
  ep_id: 987249,
  season_no: 1,
  ep_no: 10,
  ep_name: 'Chidi\'s Choice',
  watched: true },
{ user_id: 3,
  tv_id: 2790,
  tv_name: 'The Good Place',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/165/414887.jpg',
  ep_id: 998011,
  season_no: 1,
  ep_no: 11,
  ep_name: 'What\'s My Motivation',
  watched: true },
{ user_id: 3,
  tv_id: 2790,
  tv_name: 'The Good Place',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/165/414887.jpg',
  ep_id: 1009996,
  season_no: 1,
  ep_no: 12,
  ep_name: 'Mindy St. Claire',
  watched: true },
{ user_id: 3,
  tv_id: 2790,
  tv_name: 'The Good Place',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/165/414887.jpg',
  ep_id: 1009997,
  season_no: 1,
  ep_no: 13,
  ep_name: 'Michael\'s Gambit',
  watched: true },
{ user_id: 3,
  tv_id: 2790,
  tv_name: 'The Good Place',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/165/414887.jpg',
  ep_id: 1215810,
  season_no: 2,
  ep_no: 1,
  ep_name: 'Everything Is Great! Part 1',
  watched: true },
{ user_id: 3,
  tv_id: 2790,
  tv_name: 'The Good Place',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/165/414887.jpg',
  ep_id: 1215811,
  season_no: 2,
  ep_no: 2,
  ep_name: 'Everything Is Great! Part 2',
  watched: true },
{ user_id: 3,
  tv_id: 2790,
  tv_name: 'The Good Place',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/165/414887.jpg',
  ep_id: 1215812,
  season_no: 2,
  ep_no: 3,
  ep_name: 'Dance Dance Resolution',
  watched: true },
{ user_id: 3,
  tv_id: 2790,
  tv_name: 'The Good Place',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/165/414887.jpg',
  ep_id: 1215813,
  season_no: 2,
  ep_no: 4,
  ep_name: 'Team Cockroach',
  watched: true },
{ user_id: 3,
  tv_id: 2790,
  tv_name: 'The Good Place',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/165/414887.jpg',
  ep_id: 1215814,
  season_no: 2,
  ep_no: 5,
  ep_name: 'Existential Crisis',
  watched: true },
{ user_id: 3,
  tv_id: 2790,
  tv_name: 'The Good Place',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/165/414887.jpg',
  ep_id: 1215815,
  season_no: 2,
  ep_no: 6,
  ep_name: 'The Trolley Problem',
  watched: true },
{ user_id: 3,
  tv_id: 2790,
  tv_name: 'The Good Place',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/165/414887.jpg',
  ep_id: 1215817,
  season_no: 2,
  ep_no: 7,
  ep_name: 'Janet and Michael',
  watched: true },
{ user_id: 3,
  tv_id: 2790,
  tv_name: 'The Good Place',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/165/414887.jpg',
  ep_id: 1215818,
  season_no: 2,
  ep_no: 8,
  ep_name: 'Derek',
  watched: true },
{ user_id: 3,
  tv_id: 2790,
  tv_name: 'The Good Place',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/165/414887.jpg',
  ep_id: 1215819,
  season_no: 2,
  ep_no: 9,
  ep_name: 'Leap to Faith',
  watched: true },
{ user_id: 3,
  tv_id: 2790,
  tv_name: 'The Good Place',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/165/414887.jpg',
  ep_id: 1373758,
  season_no: 2,
  ep_no: 10,
  ep_name: 'Best Self',
  watched: true },
{ user_id: 3,
  tv_id: 2790,
  tv_name: 'The Good Place',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/165/414887.jpg',
  ep_id: 1373762,
  season_no: 2,
  ep_no: 11,
  ep_name: 'Rhonda, Diana, Jake, and Trent',
  watched: true },
{ user_id: 3,
  tv_id: 2790,
  tv_name: 'The Good Place',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/165/414887.jpg',
  ep_id: 1373768,
  season_no: 2,
  ep_no: 12,
  ep_name: 'The Burrito',
  watched: true },
{ user_id: 3,
  tv_id: 2790,
  tv_name: 'The Good Place',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/165/414887.jpg',
  ep_id: 1373769,
  season_no: 2,
  ep_no: 13,
  ep_name: 'Somewhere Else',
  watched: true },
{ user_id: 3,
  tv_id: 2790,
  tv_name: 'The Good Place',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/165/414887.jpg',
  ep_id: 1473822,
  season_no: 3,
  ep_no: 1,
  ep_name: 'Everything Is Bonzer! Part 1',
  watched: true },
{ user_id: 3,
  tv_id: 2790,
  tv_name: 'The Good Place',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/165/414887.jpg',
  ep_id: 1473823,
  season_no: 3,
  ep_no: 2,
  ep_name: 'Everything Is Bonzer! Part 2',
  watched: true },
{ user_id: 3,
  tv_id: 2790,
  tv_name: 'The Good Place',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/165/414887.jpg',
  ep_id: 1473824,
  season_no: 3,
  ep_no: 3,
  ep_name: 'The Brainy Bunch',
  watched: true }
      ])
    .then(() => {
      return knex.raw(`SELECT setval('${table}_id_seq', (SELECT MAX(id) FROM ${table}));`)
    })
};
