const table = 'episodes'
exports.seed = knex => {
  return knex(table)
    .insert([{ user_id: 4,
  tv_id: 13615,
  tv_name: 'Boku no Hero Academia',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/65/164727.jpg',
  ep_id: 634175,
  season_no: 1,
  ep_no: 1,
  ep_name: 'Izuku Midoriya: Origin',
  watched: true },
{ user_id: 4,
  tv_id: 13615,
  tv_name: 'Boku no Hero Academia',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/65/164727.jpg',
  ep_id: 634177,
  season_no: 1,
  ep_no: 2,
  ep_name: 'What It Takes to Be a Hero',
  watched: true },
{ user_id: 4,
  tv_id: 13615,
  tv_name: 'Boku no Hero Academia',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/65/164727.jpg',
  ep_id: 634178,
  season_no: 1,
  ep_no: 3,
  ep_name: 'Roaring Muscles',
  watched: true },
{ user_id: 4,
  tv_id: 13615,
  tv_name: 'Boku no Hero Academia',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/65/164727.jpg',
  ep_id: 677463,
  season_no: 1,
  ep_no: 4,
  ep_name: 'Starting Line',
  watched: true },
{ user_id: 4,
  tv_id: 13615,
  tv_name: 'Boku no Hero Academia',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/65/164727.jpg',
  ep_id: 677464,
  season_no: 1,
  ep_no: 5,
  ep_name: 'What I Can Do for Now',
  watched: true },
{ user_id: 4,
  tv_id: 13615,
  tv_name: 'Boku no Hero Academia',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/65/164727.jpg',
  ep_id: 677465,
  season_no: 1,
  ep_no: 6,
  ep_name: 'Rage, You Damned Nerd',
  watched: true },
{ user_id: 4,
  tv_id: 13615,
  tv_name: 'Boku no Hero Academia',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/65/164727.jpg',
  ep_id: 677466,
  season_no: 1,
  ep_no: 7,
  ep_name: 'Deku vs. Kacchan',
  watched: true },
{ user_id: 4,
  tv_id: 13615,
  tv_name: 'Boku no Hero Academia',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/65/164727.jpg',
  ep_id: 677467,
  season_no: 1,
  ep_no: 8,
  ep_name: 'Bakugo\'s Starting Line',
  watched: true },
{ user_id: 4,
  tv_id: 13615,
  tv_name: 'Boku no Hero Academia',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/65/164727.jpg',
  ep_id: 677468,
  season_no: 1,
  ep_no: 9,
  ep_name: 'Yeah, Just Do Your Best, Lida!',
  watched: true },
{ user_id: 4,
  tv_id: 13615,
  tv_name: 'Boku no Hero Academia',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/65/164727.jpg',
  ep_id: 677469,
  season_no: 1,
  ep_no: 10,
  ep_name: 'Encounter with the Unknown',
  watched: true },
{ user_id: 4,
  tv_id: 13615,
  tv_name: 'Boku no Hero Academia',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/65/164727.jpg',
  ep_id: 677470,
  season_no: 1,
  ep_no: 11,
  ep_name: 'Game Over',
  watched: true },
{ user_id: 4,
  tv_id: 13615,
  tv_name: 'Boku no Hero Academia',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/65/164727.jpg',
  ep_id: 677471,
  season_no: 1,
  ep_no: 12,
  ep_name: 'All Might',
  watched: true },
{ user_id: 4,
  tv_id: 13615,
  tv_name: 'Boku no Hero Academia',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/65/164727.jpg',
  ep_id: 677472,
  season_no: 1,
  ep_no: 13,
  ep_name: 'In Each of Our Hearts',
  watched: true },
{ user_id: 4,
  tv_id: 13615,
  tv_name: 'Boku no Hero Academia',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/65/164727.jpg',
  ep_id: 1065209,
  season_no: 2,
  ep_no: 1,
  ep_name: 'That\'s the Idea, Ochako',
  watched: true },
{ user_id: 4,
  tv_id: 13615,
  tv_name: 'Boku no Hero Academia',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/65/164727.jpg',
  ep_id: 1105639,
  season_no: 2,
  ep_no: 2,
  ep_name: 'Roaring Sports Festival',
  watched: true },
{ user_id: 4,
  tv_id: 13615,
  tv_name: 'Boku no Hero Academia',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/65/164727.jpg',
  ep_id: 1105640,
  season_no: 2,
  ep_no: 3,
  ep_name: 'In Their Own Quirky Ways',
  watched: true },
{ user_id: 4,
  tv_id: 13615,
  tv_name: 'Boku no Hero Academia',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/65/164727.jpg',
  ep_id: 1105641,
  season_no: 2,
  ep_no: 4,
  ep_name: 'Strategy, Strategy, Strategy',
  watched: true },
{ user_id: 4,
  tv_id: 13615,
  tv_name: 'Boku no Hero Academia',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/65/164727.jpg',
  ep_id: 1121014,
  season_no: 2,
  ep_no: 5,
  ep_name: 'Cavalry Battle Finale',
  watched: true },
{ user_id: 4,
  tv_id: 13615,
  tv_name: 'Boku no Hero Academia',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/65/164727.jpg',
  ep_id: 1121015,
  season_no: 2,
  ep_no: 6,
  ep_name: 'The Boy Born with Everything',
  watched: true },
{ user_id: 4,
  tv_id: 13615,
  tv_name: 'Boku no Hero Academia',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/65/164727.jpg',
  ep_id: 1121016,
  season_no: 2,
  ep_no: 7,
  ep_name: 'Victory or Defeat',
  watched: true },
{ user_id: 4,
  tv_id: 13615,
  tv_name: 'Boku no Hero Academia',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/65/164727.jpg',
  ep_id: 1121017,
  season_no: 2,
  ep_no: 8,
  ep_name: 'Battle on, Challengers!',
  watched: true },
{ user_id: 4,
  tv_id: 13615,
  tv_name: 'Boku no Hero Academia',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/65/164727.jpg',
  ep_id: 1121018,
  season_no: 2,
  ep_no: 9,
  ep_name: 'Bakugo vs. Uraraka',
  watched: true },
{ user_id: 4,
  tv_id: 13615,
  tv_name: 'Boku no Hero Academia',
  image:
   'http://static.tvmaze.com/uploads/images/medium_portrait/65/164727.jpg',
  ep_id: 1121019,
  season_no: 2,
  ep_no: 10,
  ep_name: 'Shoto Todoroki: Origin',
  watched: true }, { user_id: 4,
    tv_id: 138,
    tv_name: 'The Leftovers',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/107/267799.jpg',
    ep_id: 10729,
    season_no: 1,
    ep_no: 1,
    ep_name: 'Pilot',
    watched: true },
  { user_id: 4,
    tv_id: 138,
    tv_name: 'The Leftovers',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/107/267799.jpg',
    ep_id: 10730,
    season_no: 1,
    ep_no: 2,
    ep_name: 'Penguin One, Us Zero',
    watched: true },
  { user_id: 4,
    tv_id: 138,
    tv_name: 'The Leftovers',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/107/267799.jpg',
    ep_id: 10731,
    season_no: 1,
    ep_no: 3,
    ep_name: 'Two Boats and a Helicopter',
    watched: true },
  { user_id: 4,
    tv_id: 138,
    tv_name: 'The Leftovers',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/107/267799.jpg',
    ep_id: 10732,
    season_no: 1,
    ep_no: 4,
    ep_name: 'B.J. and the A.C.',
    watched: true },
  { user_id: 4,
    tv_id: 138,
    tv_name: 'The Leftovers',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/107/267799.jpg',
    ep_id: 10733,
    season_no: 1,
    ep_no: 5,
    ep_name: 'Gladys',
    watched: true },
  { user_id: 4,
    tv_id: 138,
    tv_name: 'The Leftovers',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/107/267799.jpg',
    ep_id: 10734,
    season_no: 1,
    ep_no: 6,
    ep_name: 'Guest',
    watched: true },
  { user_id: 4,
    tv_id: 138,
    tv_name: 'The Leftovers',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/107/267799.jpg',
    ep_id: 10735,
    season_no: 1,
    ep_no: 7,
    ep_name: 'Solace for Tired Feet',
    watched: true },
  { user_id: 4,
    tv_id: 138,
    tv_name: 'The Leftovers',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/107/267799.jpg',
    ep_id: 10736,
    season_no: 1,
    ep_no: 8,
    ep_name: 'Cairo',
    watched: true },
  { user_id: 4,
    tv_id: 138,
    tv_name: 'The Leftovers',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/107/267799.jpg',
    ep_id: 10737,
    season_no: 1,
    ep_no: 9,
    ep_name: 'The Garveys at Their Best',
    watched: true },
  { user_id: 4,
    tv_id: 138,
    tv_name: 'The Leftovers',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/107/267799.jpg',
    ep_id: 10738,
    season_no: 1,
    ep_no: 10,
    ep_name: 'The Prodigal Son Returns',
    watched: true },
  { user_id: 4,
    tv_id: 138,
    tv_name: 'The Leftovers',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/107/267799.jpg',
    ep_id: 201568,
    season_no: 2,
    ep_no: 1,
    ep_name: 'Axis Mundi',
    watched: true },
  { user_id: 4,
    tv_id: 138,
    tv_name: 'The Leftovers',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/107/267799.jpg',
    ep_id: 203443,
    season_no: 2,
    ep_no: 2,
    ep_name: 'A Matter of Geography',
    watched: true },
  { user_id: 4,
    tv_id: 138,
    tv_name: 'The Leftovers',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/107/267799.jpg',
    ep_id: 203444,
    season_no: 2,
    ep_no: 3,
    ep_name: 'Off Ramp',
    watched: true },
  { user_id: 4,
    tv_id: 138,
    tv_name: 'The Leftovers',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/107/267799.jpg',
    ep_id: 271073,
    season_no: 2,
    ep_no: 4,
    ep_name: 'Orange Sticker',
    watched: true },
  { user_id: 4,
    tv_id: 138,
    tv_name: 'The Leftovers',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/107/267799.jpg',
    ep_id: 350692,
    season_no: 2,
    ep_no: 5,
    ep_name: 'No Room at the Inn',
    watched: true },
  { user_id: 4,
    tv_id: 138,
    tv_name: 'The Leftovers',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/107/267799.jpg',
    ep_id: 350694,
    season_no: 2,
    ep_no: 6,
    ep_name: 'Lens',
    watched: true },
  { user_id: 4,
    tv_id: 138,
    tv_name: 'The Leftovers',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/107/267799.jpg',
    ep_id: 351058,
    season_no: 2,
    ep_no: 7,
    ep_name: 'A Most Powerful Adversary',
    watched: true },
  { user_id: 4,
    tv_id: 138,
    tv_name: 'The Leftovers',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/107/267799.jpg',
    ep_id: 395615,
    season_no: 2,
    ep_no: 8,
    ep_name: 'International Assassin',
    watched: true },
  { user_id: 4,
    tv_id: 138,
    tv_name: 'The Leftovers',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/107/267799.jpg',
    ep_id: 395616,
    season_no: 2,
    ep_no: 9,
    ep_name: 'Ten Thirteen',
    watched: true },
  { user_id: 4,
    tv_id: 138,
    tv_name: 'The Leftovers',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/107/267799.jpg',
    ep_id: 414652,
    season_no: 2,
    ep_no: 10,
    ep_name: 'I Live Here Now',
    watched: true },
  { user_id: 4,
    tv_id: 138,
    tv_name: 'The Leftovers',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/107/267799.jpg',
    ep_id: 1048508,
    season_no: 3,
    ep_no: 1,
    ep_name: 'The Book of Kevin',
    watched: true },
  { user_id: 4,
    tv_id: 138,
    tv_name: 'The Leftovers',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/107/267799.jpg',
    ep_id: 1093338,
    season_no: 3,
    ep_no: 2,
    ep_name: 'Don\'t Be Ridiculous',
    watched: true },
  { user_id: 4,
    tv_id: 138,
    tv_name: 'The Leftovers',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/107/267799.jpg',
    ep_id: 1093339,
    season_no: 3,
    ep_no: 3,
    ep_name: 'Crazy Whitefella Thinking',
    watched: true }, { user_id: 4,
    tv_id: 12036,
    tv_name: 'Altered Carbon',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/358572.jpg',
    ep_id: 1367519,
    season_no: 1,
    ep_no: 1,
    ep_name: 'Out of the Past',
    watched: true },
  { user_id: 4,
    tv_id: 12036,
    tv_name: 'Altered Carbon',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/358572.jpg',
    ep_id: 1389593,
    season_no: 1,
    ep_no: 2,
    ep_name: 'Fallen Angel',
    watched: true },
  { user_id: 4,
    tv_id: 12036,
    tv_name: 'Altered Carbon',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/358572.jpg',
    ep_id: 1389596,
    season_no: 1,
    ep_no: 3,
    ep_name: 'In a Lonely Place',
    watched: true },
  { user_id: 4,
    tv_id: 12036,
    tv_name: 'Altered Carbon',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/358572.jpg',
    ep_id: 1389597,
    season_no: 1,
    ep_no: 4,
    ep_name: 'Force of Evil',
    watched: true },
  { user_id: 4,
    tv_id: 12036,
    tv_name: 'Altered Carbon',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/358572.jpg',
    ep_id: 1389598,
    season_no: 1,
    ep_no: 5,
    ep_name: 'The Wrong Man',
    watched: true },
  { user_id: 4,
    tv_id: 12036,
    tv_name: 'Altered Carbon',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/358572.jpg',
    ep_id: 1389599,
    season_no: 1,
    ep_no: 6,
    ep_name: 'Man with My Face',
    watched: true },
  { user_id: 4,
    tv_id: 12036,
    tv_name: 'Altered Carbon',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/358572.jpg',
    ep_id: 1389600,
    season_no: 1,
    ep_no: 7,
    ep_name: 'Nora Inu',
    watched: true },
  { user_id: 4,
    tv_id: 12036,
    tv_name: 'Altered Carbon',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/358572.jpg',
    ep_id: 1389601,
    season_no: 1,
    ep_no: 8,
    ep_name: 'Clash by Night',
    watched: true },
  { user_id: 4,
    tv_id: 12036,
    tv_name: 'Altered Carbon',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/358572.jpg',
    ep_id: 1389602,
    season_no: 1,
    ep_no: 9,
    ep_name: 'Rage in Heaven',
    watched: true },
  { user_id: 4,
    tv_id: 12036,
    tv_name: 'Altered Carbon',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/358572.jpg',
    ep_id: 1389603,
    season_no: 1,
    ep_no: 10,
    ep_name: 'The Killers',
    watched: true }, { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11393,
    season_no: 1,
    ep_no: 1,
    ep_name: 'Pilot',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11394,
    season_no: 1,
    ep_no: 2,
    ep_name: 'The Same Old Story',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11395,
    season_no: 1,
    ep_no: 3,
    ep_name: 'The Ghost Network',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11396,
    season_no: 1,
    ep_no: 4,
    ep_name: 'The Arrival',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11397,
    season_no: 1,
    ep_no: 5,
    ep_name: 'Power Hungry',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11398,
    season_no: 1,
    ep_no: 6,
    ep_name: 'The Cure',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11399,
    season_no: 1,
    ep_no: 7,
    ep_name: 'In Which We Meet Mr. Jones',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11400,
    season_no: 1,
    ep_no: 8,
    ep_name: 'The Equation',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11401,
    season_no: 1,
    ep_no: 9,
    ep_name: 'The Dreamscape',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11402,
    season_no: 1,
    ep_no: 10,
    ep_name: 'Safe',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11403,
    season_no: 1,
    ep_no: 11,
    ep_name: 'Bound',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11404,
    season_no: 1,
    ep_no: 12,
    ep_name: 'The No-Brainer',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11405,
    season_no: 1,
    ep_no: 13,
    ep_name: 'The Transformation',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11406,
    season_no: 1,
    ep_no: 14,
    ep_name: 'Ability',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11407,
    season_no: 1,
    ep_no: 15,
    ep_name: 'Inner Child',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11408,
    season_no: 1,
    ep_no: 16,
    ep_name: 'Unleashed',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11409,
    season_no: 1,
    ep_no: 17,
    ep_name: 'Bad Dreams',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11410,
    season_no: 1,
    ep_no: 18,
    ep_name: 'Midnight',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11411,
    season_no: 1,
    ep_no: 19,
    ep_name: 'The Road Not Taken',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11412,
    season_no: 1,
    ep_no: 20,
    ep_name: 'There\'s More than One of Everything',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11413,
    season_no: 2,
    ep_no: 1,
    ep_name: 'A New Day in the Old Town',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11414,
    season_no: 2,
    ep_no: 2,
    ep_name: 'Night of Desirable Objects',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11415,
    season_no: 2,
    ep_no: 3,
    ep_name: 'Fracture',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11416,
    season_no: 2,
    ep_no: 4,
    ep_name: 'Momentum Deferred',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11417,
    season_no: 2,
    ep_no: 5,
    ep_name: 'Dream Logic',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11418,
    season_no: 2,
    ep_no: 6,
    ep_name: 'Earthling',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11419,
    season_no: 2,
    ep_no: 7,
    ep_name: 'Of Human Action',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11420,
    season_no: 2,
    ep_no: 8,
    ep_name: 'August',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11421,
    season_no: 2,
    ep_no: 9,
    ep_name: 'Snakehead',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11422,
    season_no: 2,
    ep_no: 10,
    ep_name: 'Grey Matters',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11423,
    season_no: 2,
    ep_no: 11,
    ep_name: 'Unearthed',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11424,
    season_no: 2,
    ep_no: 12,
    ep_name: 'Johari Window',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11425,
    season_no: 2,
    ep_no: 13,
    ep_name: 'What Lies Below',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11426,
    season_no: 2,
    ep_no: 14,
    ep_name: 'The Bishop Revival',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11427,
    season_no: 2,
    ep_no: 15,
    ep_name: 'Jacksonville',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11428,
    season_no: 2,
    ep_no: 16,
    ep_name: 'Peter',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11429,
    season_no: 2,
    ep_no: 17,
    ep_name: 'Olivia. In the Lab. With the Revolver.',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11430,
    season_no: 2,
    ep_no: 18,
    ep_name: 'White Tulip',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11431,
    season_no: 2,
    ep_no: 19,
    ep_name: 'The Man from the Other Side',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11432,
    season_no: 2,
    ep_no: 20,
    ep_name: 'Brown Betty',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11433,
    season_no: 2,
    ep_no: 21,
    ep_name: 'Northwest Passage',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11434,
    season_no: 2,
    ep_no: 22,
    ep_name: 'Over There: Part 1',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11435,
    season_no: 2,
    ep_no: 23,
    ep_name: 'Over There: Part 2',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11436,
    season_no: 3,
    ep_no: 1,
    ep_name: 'Olivia',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11437,
    season_no: 3,
    ep_no: 2,
    ep_name: 'The Box',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11438,
    season_no: 3,
    ep_no: 3,
    ep_name: 'The Plateau',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11439,
    season_no: 3,
    ep_no: 4,
    ep_name: 'Do Shapeshifters Dream of Electric Sheep?',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11440,
    season_no: 3,
    ep_no: 5,
    ep_name: 'Amber 31422',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11441,
    season_no: 3,
    ep_no: 6,
    ep_name: '6955 kHz',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11442,
    season_no: 3,
    ep_no: 7,
    ep_name: 'The Abducted',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11443,
    season_no: 3,
    ep_no: 8,
    ep_name: 'Entrada',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11444,
    season_no: 3,
    ep_no: 9,
    ep_name: 'Marionette',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11445,
    season_no: 3,
    ep_no: 10,
    ep_name: 'The Firefly',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11446,
    season_no: 3,
    ep_no: 11,
    ep_name: 'Reciprocity',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11447,
    season_no: 3,
    ep_no: 12,
    ep_name: 'Concentrate and Ask Again',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11448,
    season_no: 3,
    ep_no: 13,
    ep_name: 'Immortality',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11449,
    season_no: 3,
    ep_no: 14,
    ep_name: '6B',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11450,
    season_no: 3,
    ep_no: 15,
    ep_name: 'Subject 13',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11451,
    season_no: 3,
    ep_no: 16,
    ep_name: 'Os',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11452,
    season_no: 3,
    ep_no: 17,
    ep_name: 'Stowaway',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11453,
    season_no: 3,
    ep_no: 18,
    ep_name: 'Bloodline',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11454,
    season_no: 3,
    ep_no: 19,
    ep_name: 'Lysergic Acid Diethylamide',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11455,
    season_no: 3,
    ep_no: 20,
    ep_name: '6:02 AM EST',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11456,
    season_no: 3,
    ep_no: 21,
    ep_name: 'The Last Sam Weiss',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11457,
    season_no: 3,
    ep_no: 22,
    ep_name: 'The Day We Died',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11458,
    season_no: 4,
    ep_no: 1,
    ep_name: 'Neither Here Nor There',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11459,
    season_no: 4,
    ep_no: 2,
    ep_name: 'One Night in October',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11460,
    season_no: 4,
    ep_no: 3,
    ep_name: 'Alone in the World',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11461,
    season_no: 4,
    ep_no: 4,
    ep_name: 'Subject 9',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11462,
    season_no: 4,
    ep_no: 5,
    ep_name: 'Novation',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11463,
    season_no: 4,
    ep_no: 6,
    ep_name: 'And Those We\'ve Left Behind',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11464,
    season_no: 4,
    ep_no: 7,
    ep_name: 'Wallflower',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11465,
    season_no: 4,
    ep_no: 8,
    ep_name: 'Back to Where You\'ve Never Been',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11466,
    season_no: 4,
    ep_no: 9,
    ep_name: 'Enemy of My Enemy',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11467,
    season_no: 4,
    ep_no: 10,
    ep_name: 'Forced Perspective',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11468,
    season_no: 4,
    ep_no: 11,
    ep_name: 'Making Angels',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11469,
    season_no: 4,
    ep_no: 12,
    ep_name: 'Welcome to Westfield',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11470,
    season_no: 4,
    ep_no: 13,
    ep_name: 'A Better Human Being',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11471,
    season_no: 4,
    ep_no: 14,
    ep_name: 'The End of All Things',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11472,
    season_no: 4,
    ep_no: 15,
    ep_name: 'A Short Story About Love',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11473,
    season_no: 4,
    ep_no: 16,
    ep_name: 'Nothing as It Seems',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11474,
    season_no: 4,
    ep_no: 17,
    ep_name: 'Everything in Its Right Place',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11475,
    season_no: 4,
    ep_no: 18,
    ep_name: 'The Consultant',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11476,
    season_no: 4,
    ep_no: 19,
    ep_name: 'Letters of Transit',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11477,
    season_no: 4,
    ep_no: 20,
    ep_name: 'Worlds Apart',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11478,
    season_no: 4,
    ep_no: 21,
    ep_name: 'Brave New World: Part 1',
    watched: true },
  { user_id: 4,
    tv_id: 158,
    tv_name: 'Fringe',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2245.jpg',
    ep_id: 11479,
    season_no: 4,
    ep_no: 22,
    ep_name: 'Brave New World: Part 2',
    watched: true }, { user_id: 4,
    tv_id: 1371,
    tv_name: 'Westworld',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/152/381152.jpg',
    ep_id: 869671,
    season_no: 1,
    ep_no: 1,
    ep_name: 'The Original',
    watched: true },
  { user_id: 4,
    tv_id: 1371,
    tv_name: 'Westworld',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/152/381152.jpg',
    ep_id: 911201,
    season_no: 1,
    ep_no: 2,
    ep_name: 'Chestnut',
    watched: true },
  { user_id: 4,
    tv_id: 1371,
    tv_name: 'Westworld',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/152/381152.jpg',
    ep_id: 911204,
    season_no: 1,
    ep_no: 3,
    ep_name: 'The Stray',
    watched: true },
  { user_id: 4,
    tv_id: 1371,
    tv_name: 'Westworld',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/152/381152.jpg',
    ep_id: 911205,
    season_no: 1,
    ep_no: 4,
    ep_name: 'Dissonance Theory',
    watched: true },
  { user_id: 4,
    tv_id: 1371,
    tv_name: 'Westworld',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/152/381152.jpg',
    ep_id: 927174,
    season_no: 1,
    ep_no: 5,
    ep_name: 'Contrapasso',
    watched: true },
  { user_id: 4,
    tv_id: 1371,
    tv_name: 'Westworld',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/152/381152.jpg',
    ep_id: 932057,
    season_no: 1,
    ep_no: 6,
    ep_name: 'The Adversary',
    watched: true },
  { user_id: 4,
    tv_id: 1371,
    tv_name: 'Westworld',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/152/381152.jpg',
    ep_id: 938404,
    season_no: 1,
    ep_no: 7,
    ep_name: 'Trompe L\'Oeil',
    watched: true },
  { user_id: 4,
    tv_id: 1371,
    tv_name: 'Westworld',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/152/381152.jpg',
    ep_id: 943065,
    season_no: 1,
    ep_no: 8,
    ep_name: 'Trace Decay',
    watched: true },
  { user_id: 4,
    tv_id: 1371,
    tv_name: 'Westworld',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/152/381152.jpg',
    ep_id: 943066,
    season_no: 1,
    ep_no: 9,
    ep_name: 'The Well-Tempered Clavier',
    watched: true },
  { user_id: 4,
    tv_id: 1371,
    tv_name: 'Westworld',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/152/381152.jpg',
    ep_id: 943067,
    season_no: 1,
    ep_no: 10,
    ep_name: 'The Bicameral Mind',
    watched: true },
  { user_id: 4,
    tv_id: 1371,
    tv_name: 'Westworld',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/152/381152.jpg',
    ep_id: 1214222,
    season_no: 2,
    ep_no: 1,
    ep_name: 'Journey Into Night',
    watched: true },
  { user_id: 4,
    tv_id: 1371,
    tv_name: 'Westworld',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/152/381152.jpg',
    ep_id: 1440915,
    season_no: 2,
    ep_no: 2,
    ep_name: 'Reunion',
    watched: true },
  { user_id: 4,
    tv_id: 1371,
    tv_name: 'Westworld',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/152/381152.jpg',
    ep_id: 1440916,
    season_no: 2,
    ep_no: 3,
    ep_name: 'Virtù e Fortuna',
    watched: true },
  { user_id: 4,
    tv_id: 1371,
    tv_name: 'Westworld',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/152/381152.jpg',
    ep_id: 1440917,
    season_no: 2,
    ep_no: 4,
    ep_name: 'The Riddle of the Sphinx',
    watched: true }
      ])
    .then(() => {
      return knex.raw(`SELECT setval('${table}_id_seq', (SELECT MAX(id) FROM ${table}));`)
    })
};
