const table = 'episodes'
exports.seed = knex => {
  return knex(table)
    .insert([{ user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4952,
    season_no: 1,
    ep_no: 1,
    ep_name: 'Winter is Coming',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4953,
    season_no: 1,
    ep_no: 2,
    ep_name: 'The Kingsroad',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4954,
    season_no: 1,
    ep_no: 3,
    ep_name: 'Lord Snow',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4955,
    season_no: 1,
    ep_no: 4,
    ep_name: 'Cripples, Bastards, and Broken Things',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4956,
    season_no: 1,
    ep_no: 5,
    ep_name: 'The Wolf and the Lion',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4957,
    season_no: 1,
    ep_no: 6,
    ep_name: 'A Golden Crown',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4958,
    season_no: 1,
    ep_no: 7,
    ep_name: 'You Win or You Die',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4959,
    season_no: 1,
    ep_no: 8,
    ep_name: 'The Pointy End',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4960,
    season_no: 1,
    ep_no: 9,
    ep_name: 'Baelor',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4961,
    season_no: 1,
    ep_no: 10,
    ep_name: 'Fire and Blood',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4962,
    season_no: 2,
    ep_no: 1,
    ep_name: 'The North Remembers',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4963,
    season_no: 2,
    ep_no: 2,
    ep_name: 'The Night Lands',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4964,
    season_no: 2,
    ep_no: 3,
    ep_name: 'What is Dead May Never Die',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4965,
    season_no: 2,
    ep_no: 4,
    ep_name: 'Garden of Bones',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4966,
    season_no: 2,
    ep_no: 5,
    ep_name: 'The Ghost of Harrenhal',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4967,
    season_no: 2,
    ep_no: 6,
    ep_name: 'The Old Gods and the New',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4968,
    season_no: 2,
    ep_no: 7,
    ep_name: 'A Man Without Honor',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4969,
    season_no: 2,
    ep_no: 8,
    ep_name: 'The Prince of Winterfell',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4970,
    season_no: 2,
    ep_no: 9,
    ep_name: 'Blackwater',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4971,
    season_no: 2,
    ep_no: 10,
    ep_name: 'Valar Morghulis',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4972,
    season_no: 3,
    ep_no: 1,
    ep_name: 'Valar Dohaeris',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4973,
    season_no: 3,
    ep_no: 2,
    ep_name: 'Dark Wings, Dark Words',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4974,
    season_no: 3,
    ep_no: 3,
    ep_name: 'Walk of Punishment',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4975,
    season_no: 3,
    ep_no: 4,
    ep_name: 'And Now His Watch is Ended',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4976,
    season_no: 3,
    ep_no: 5,
    ep_name: 'Kissed by Fire',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4977,
    season_no: 3,
    ep_no: 6,
    ep_name: 'The Climb',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4978,
    season_no: 3,
    ep_no: 7,
    ep_name: 'The Bear and the Maiden Fair',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4979,
    season_no: 3,
    ep_no: 8,
    ep_name: 'Second Sons',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4980,
    season_no: 3,
    ep_no: 9,
    ep_name: 'The Rains of Castamere',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4981,
    season_no: 3,
    ep_no: 10,
    ep_name: 'Mhysa',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4982,
    season_no: 4,
    ep_no: 1,
    ep_name: 'Two Swords',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4983,
    season_no: 4,
    ep_no: 2,
    ep_name: 'The Lion and the Rose',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4984,
    season_no: 4,
    ep_no: 3,
    ep_name: 'Breaker of Chains',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4985,
    season_no: 4,
    ep_no: 4,
    ep_name: 'Oathkeeper',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4986,
    season_no: 4,
    ep_no: 5,
    ep_name: 'First of His Name',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4987,
    season_no: 4,
    ep_no: 6,
    ep_name: 'The Laws of Gods and Men',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4988,
    season_no: 4,
    ep_no: 7,
    ep_name: 'Mockingbird',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4989,
    season_no: 4,
    ep_no: 8,
    ep_name: 'The Mountain and the Viper',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4990,
    season_no: 4,
    ep_no: 9,
    ep_name: 'The Watchers on the Wall',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 4991,
    season_no: 4,
    ep_no: 10,
    ep_name: 'The Children',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 116522,
    season_no: 5,
    ep_no: 1,
    ep_name: 'The Wars to Come',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 144328,
    season_no: 5,
    ep_no: 2,
    ep_name: 'The House of Black and White',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 144329,
    season_no: 5,
    ep_no: 3,
    ep_name: 'High Sparrow',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 144330,
    season_no: 5,
    ep_no: 4,
    ep_name: 'Sons of the Harpy',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 151777,
    season_no: 5,
    ep_no: 5,
    ep_name: 'Kill the Boy',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 152766,
    season_no: 5,
    ep_no: 6,
    ep_name: 'Unbowed, Unbent, Unbroken',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 153327,
    season_no: 5,
    ep_no: 7,
    ep_name: 'The Gift',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 155299,
    season_no: 5,
    ep_no: 8,
    ep_name: 'Hardhome',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 160040,
    season_no: 5,
    ep_no: 9,
    ep_name: 'The Dance of Dragons',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 162186,
    season_no: 5,
    ep_no: 10,
    ep_name: 'Mother\'s Mercy',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 560813,
    season_no: 6,
    ep_no: 1,
    ep_name: 'The Red Woman',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 664672,
    season_no: 6,
    ep_no: 2,
    ep_name: 'Home',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 664673,
    season_no: 6,
    ep_no: 3,
    ep_name: 'Oathbreaker',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 664674,
    season_no: 6,
    ep_no: 4,
    ep_name: 'Book of the Stranger',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 664675,
    season_no: 6,
    ep_no: 5,
    ep_name: 'The Door',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 664676,
    season_no: 6,
    ep_no: 6,
    ep_name: 'Blood of My Blood',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 717449,
    season_no: 6,
    ep_no: 7,
    ep_name: 'The Broken Man',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 729573,
    season_no: 6,
    ep_no: 8,
    ep_name: 'No One',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 729574,
    season_no: 6,
    ep_no: 9,
    ep_name: 'Battle of the Bastards',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 729575,
    season_no: 6,
    ep_no: 10,
    ep_name: 'The Winds of Winter',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 937256,
    season_no: 7,
    ep_no: 1,
    ep_name: 'Dragonstone',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 1221410,
    season_no: 7,
    ep_no: 2,
    ep_name: 'Stormborn',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 1221411,
    season_no: 7,
    ep_no: 3,
    ep_name: 'The Queen\'s Justice',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 1221412,
    season_no: 7,
    ep_no: 4,
    ep_name: 'The Spoils of War',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 1221413,
    season_no: 7,
    ep_no: 5,
    ep_name: 'Eastwatch',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 1221414,
    season_no: 7,
    ep_no: 6,
    ep_name: 'Beyond the Wall',
    watched: true },
  { user_id: 5,
    tv_id: 82,
    tv_name: 'Game of Thrones',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/143/359013.jpg',
    ep_id: 1221415,
    season_no: 7,
    ep_no: 7,
    ep_name: 'The Dragon and the Wolf',
    watched: true },{ user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12192,
    season_no: 1,
    ep_no: 1,
    ep_name: 'Pilot',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12193,
    season_no: 1,
    ep_no: 2,
    ep_name: 'Cat\'s in the Bag...',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12194,
    season_no: 1,
    ep_no: 3,
    ep_name: '...and the Bag\'s in the River',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12195,
    season_no: 1,
    ep_no: 4,
    ep_name: 'Cancer Man',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12196,
    season_no: 1,
    ep_no: 5,
    ep_name: 'Gray Matter',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12197,
    season_no: 1,
    ep_no: 6,
    ep_name: 'Crazy Handful of Nothin\'',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12198,
    season_no: 1,
    ep_no: 7,
    ep_name: 'A No-Rough-Stuff-Type Deal',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12199,
    season_no: 2,
    ep_no: 1,
    ep_name: 'Seven Thirty-Seven',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12200,
    season_no: 2,
    ep_no: 2,
    ep_name: 'Grilled',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12201,
    season_no: 2,
    ep_no: 3,
    ep_name: 'Bit by a Dead Bee',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12202,
    season_no: 2,
    ep_no: 4,
    ep_name: 'Down',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12203,
    season_no: 2,
    ep_no: 5,
    ep_name: 'Breakage',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12204,
    season_no: 2,
    ep_no: 6,
    ep_name: 'Peekaboo',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12205,
    season_no: 2,
    ep_no: 7,
    ep_name: 'Negro Y Azul',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12206,
    season_no: 2,
    ep_no: 8,
    ep_name: 'Better Call Saul',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12207,
    season_no: 2,
    ep_no: 9,
    ep_name: '4 Days Out',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12208,
    season_no: 2,
    ep_no: 10,
    ep_name: 'Over',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12209,
    season_no: 2,
    ep_no: 11,
    ep_name: 'Mandala',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12210,
    season_no: 2,
    ep_no: 12,
    ep_name: 'Phoenix',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12211,
    season_no: 2,
    ep_no: 13,
    ep_name: 'ABQ',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12212,
    season_no: 3,
    ep_no: 1,
    ep_name: 'No Más',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12213,
    season_no: 3,
    ep_no: 2,
    ep_name: 'Caballo sin Nombre',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12214,
    season_no: 3,
    ep_no: 3,
    ep_name: 'I.F.T.',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12215,
    season_no: 3,
    ep_no: 4,
    ep_name: 'Green Light',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12216,
    season_no: 3,
    ep_no: 5,
    ep_name: 'Más',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12217,
    season_no: 3,
    ep_no: 6,
    ep_name: 'Sunset',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12218,
    season_no: 3,
    ep_no: 7,
    ep_name: 'One Minute',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12219,
    season_no: 3,
    ep_no: 8,
    ep_name: 'I See You',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12220,
    season_no: 3,
    ep_no: 9,
    ep_name: 'Kafkaesque',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12221,
    season_no: 3,
    ep_no: 10,
    ep_name: 'Fly',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12222,
    season_no: 3,
    ep_no: 11,
    ep_name: 'Abiquiu',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12223,
    season_no: 3,
    ep_no: 12,
    ep_name: 'Half Measures',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12224,
    season_no: 3,
    ep_no: 13,
    ep_name: 'Full Measure',
    watched: true },{ user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12238,
    season_no: 5,
    ep_no: 1,
    ep_name: 'Live Free or Die',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12239,
    season_no: 5,
    ep_no: 2,
    ep_name: 'Madrigal',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12240,
    season_no: 5,
    ep_no: 3,
    ep_name: 'Hazard Pay',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12241,
    season_no: 5,
    ep_no: 4,
    ep_name: 'Fifty-One',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12242,
    season_no: 5,
    ep_no: 5,
    ep_name: 'Dead Freight',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12243,
    season_no: 5,
    ep_no: 6,
    ep_name: 'Buyout',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12244,
    season_no: 5,
    ep_no: 7,
    ep_name: 'Say My Name',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12245,
    season_no: 5,
    ep_no: 8,
    ep_name: 'Gliding Over All',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12246,
    season_no: 5,
    ep_no: 9,
    ep_name: 'Blood Money',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12247,
    season_no: 5,
    ep_no: 10,
    ep_name: 'Buried',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12248,
    season_no: 5,
    ep_no: 11,
    ep_name: 'Confessions',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12249,
    season_no: 5,
    ep_no: 12,
    ep_name: 'Rabid Dog',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12250,
    season_no: 5,
    ep_no: 13,
    ep_name: 'To\'hajiilee',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12251,
    season_no: 5,
    ep_no: 14,
    ep_name: 'Ozymandias',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12252,
    season_no: 5,
    ep_no: 15,
    ep_name: 'Granite State',
    watched: true },
  { user_id: 5,
    tv_id: 169,
    tv_name: 'Breaking Bad',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2400.jpg',
    ep_id: 12253,
    season_no: 5,
    ep_no: 16,
    ep_name: 'Felina',
    watched: true },
    { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12558,
    season_no: 2,
    ep_no: 1,
    ep_name: 'Pawnee Zoo',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12559,
    season_no: 2,
    ep_no: 2,
    ep_name: 'The Stakeout',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12560,
    season_no: 2,
    ep_no: 3,
    ep_name: 'Beauty Pageant',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12561,
    season_no: 2,
    ep_no: 4,
    ep_name: 'Practice Date',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12562,
    season_no: 2,
    ep_no: 5,
    ep_name: 'Sister City',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12563,
    season_no: 2,
    ep_no: 6,
    ep_name: 'KaBOOM!',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12564,
    season_no: 2,
    ep_no: 7,
    ep_name: 'Greg Pikitis',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12565,
    season_no: 2,
    ep_no: 8,
    ep_name: 'Ron and Tammy',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12566,
    season_no: 2,
    ep_no: 9,
    ep_name: 'The Camel',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12567,
    season_no: 2,
    ep_no: 10,
    ep_name: 'Hunting Trip',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12568,
    season_no: 2,
    ep_no: 11,
    ep_name: 'The Fourth Floor',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12569,
    season_no: 2,
    ep_no: 12,
    ep_name: 'Christmas Scandal',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12570,
    season_no: 2,
    ep_no: 13,
    ep_name: 'The Set Up',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12571,
    season_no: 2,
    ep_no: 14,
    ep_name: 'Leslie\'s House',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12572,
    season_no: 2,
    ep_no: 15,
    ep_name: 'Sweetums',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12573,
    season_no: 2,
    ep_no: 16,
    ep_name: 'Galentine\'s Day',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12574,
    season_no: 2,
    ep_no: 17,
    ep_name: 'Woman of the Year',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12575,
    season_no: 2,
    ep_no: 18,
    ep_name: 'The Possum',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12576,
    season_no: 2,
    ep_no: 19,
    ep_name: 'Park Safety',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12577,
    season_no: 2,
    ep_no: 20,
    ep_name: 'Summer Catalog',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12578,
    season_no: 2,
    ep_no: 21,
    ep_name: '94 Meetings',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12579,
    season_no: 2,
    ep_no: 22,
    ep_name: 'Telethon',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12580,
    season_no: 2,
    ep_no: 23,
    ep_name: 'The Master Plan',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12581,
    season_no: 2,
    ep_no: 24,
    ep_name: 'Freddy Spaghetti',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12582,
    season_no: 3,
    ep_no: 1,
    ep_name: 'Go Big or Go Home',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12583,
    season_no: 3,
    ep_no: 2,
    ep_name: 'Flu Season',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12584,
    season_no: 3,
    ep_no: 3,
    ep_name: 'Time Capsule',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12585,
    season_no: 3,
    ep_no: 4,
    ep_name: 'Ron and Tammy II',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12586,
    season_no: 3,
    ep_no: 5,
    ep_name: 'Media Blitz',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12587,
    season_no: 3,
    ep_no: 6,
    ep_name: 'Indianapolis',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12588,
    season_no: 3,
    ep_no: 7,
    ep_name: 'Harvest Festival',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12589,
    season_no: 3,
    ep_no: 8,
    ep_name: 'Camping',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12590,
    season_no: 3,
    ep_no: 9,
    ep_name: 'Fancy Party',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12591,
    season_no: 3,
    ep_no: 10,
    ep_name: 'Soulmates',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12592,
    season_no: 3,
    ep_no: 11,
    ep_name: 'Jerry\'s Painting',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12593,
    season_no: 3,
    ep_no: 12,
    ep_name: 'Eagleton',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12594,
    season_no: 3,
    ep_no: 13,
    ep_name: 'The Fight',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12595,
    season_no: 3,
    ep_no: 14,
    ep_name: 'Road Trip',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12596,
    season_no: 3,
    ep_no: 15,
    ep_name: 'The Bubble',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12597,
    season_no: 3,
    ep_no: 16,
    ep_name: 'Li\'l Sebastian',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12598,
    season_no: 4,
    ep_no: 1,
    ep_name: 'I\'m Leslie Knope',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12599,
    season_no: 4,
    ep_no: 2,
    ep_name: 'Ron and Tammys',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12600,
    season_no: 4,
    ep_no: 3,
    ep_name: 'Born & Raised',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12601,
    season_no: 4,
    ep_no: 4,
    ep_name: 'Pawnee Rangers',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12602,
    season_no: 4,
    ep_no: 5,
    ep_name: 'Meet n Greet',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12603,
    season_no: 4,
    ep_no: 6,
    ep_name: 'End of the World',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12604,
    season_no: 4,
    ep_no: 7,
    ep_name: 'The Treaty',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12605,
    season_no: 4,
    ep_no: 8,
    ep_name: 'Smallest Park',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12606,
    season_no: 4,
    ep_no: 9,
    ep_name: 'The Trial of Leslie Knope',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12607,
    season_no: 4,
    ep_no: 10,
    ep_name: 'Citizen Knope',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12608,
    season_no: 4,
    ep_no: 11,
    ep_name: 'The Comeback Kid',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12609,
    season_no: 4,
    ep_no: 12,
    ep_name: 'Campaign Ad',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12610,
    season_no: 4,
    ep_no: 13,
    ep_name: 'Bowling for Votes',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12611,
    season_no: 4,
    ep_no: 14,
    ep_name: 'Operation Ann',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12612,
    season_no: 4,
    ep_no: 15,
    ep_name: 'Dave Returns',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12613,
    season_no: 4,
    ep_no: 16,
    ep_name: 'Sweet Sixteen',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12614,
    season_no: 4,
    ep_no: 17,
    ep_name: 'Campaign Shake-Up',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12615,
    season_no: 4,
    ep_no: 18,
    ep_name: 'Lucky',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12616,
    season_no: 4,
    ep_no: 19,
    ep_name: 'Live Ammo',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12617,
    season_no: 4,
    ep_no: 20,
    ep_name: 'The Debate',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12618,
    season_no: 4,
    ep_no: 21,
    ep_name: 'Bus Tour',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12619,
    season_no: 4,
    ep_no: 22,
    ep_name: 'Win, Lose, or Draw',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12620,
    season_no: 5,
    ep_no: 1,
    ep_name: 'Ms. Knope Goes to Washington',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12621,
    season_no: 5,
    ep_no: 2,
    ep_name: 'Soda Tax',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12622,
    season_no: 5,
    ep_no: 3,
    ep_name: 'How a Bill Becomes a Law',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12623,
    season_no: 5,
    ep_no: 4,
    ep_name: 'Sex Education',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12624,
    season_no: 5,
    ep_no: 5,
    ep_name: 'Halloween Surprise',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12625,
    season_no: 5,
    ep_no: 6,
    ep_name: 'Ben\'s Parents',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12626,
    season_no: 5,
    ep_no: 7,
    ep_name: 'Leslie vs. April',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12627,
    season_no: 5,
    ep_no: 8,
    ep_name: 'Pawnee Commons',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12628,
    season_no: 5,
    ep_no: 9,
    ep_name: 'Ron and Diane',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12629,
    season_no: 5,
    ep_no: 10,
    ep_name: 'Two Parties',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12630,
    season_no: 5,
    ep_no: 11,
    ep_name: 'Women in Garbage',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12631,
    season_no: 5,
    ep_no: 12,
    ep_name: 'Ann\'s Decision',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12632,
    season_no: 5,
    ep_no: 13,
    ep_name: 'Emergency Response',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12633,
    season_no: 5,
    ep_no: 14,
    ep_name: 'Leslie and Ben',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12634,
    season_no: 5,
    ep_no: 15,
    ep_name: 'Correspondents\' Lunch',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12635,
    season_no: 5,
    ep_no: 16,
    ep_name: 'Bailout',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12636,
    season_no: 5,
    ep_no: 17,
    ep_name: 'Partridge',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12637,
    season_no: 5,
    ep_no: 18,
    ep_name: 'Animal Control',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12638,
    season_no: 5,
    ep_no: 19,
    ep_name: 'Article Two',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12639,
    season_no: 5,
    ep_no: 20,
    ep_name: 'Jerry\'s Retirement',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12640,
    season_no: 5,
    ep_no: 21,
    ep_name: 'Swing Vote',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12641,
    season_no: 5,
    ep_no: 22,
    ep_name: 'Are You Better Off?',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12642,
    season_no: 6,
    ep_no: 1,
    ep_name: 'London (1)',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12643,
    season_no: 6,
    ep_no: 2,
    ep_name: 'London (2)',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12644,
    season_no: 6,
    ep_no: 3,
    ep_name: 'The Pawnee-Eagleton Tip Off Classic',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12645,
    season_no: 6,
    ep_no: 4,
    ep_name: 'Doppelgängers',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12646,
    season_no: 6,
    ep_no: 5,
    ep_name: 'Gin It Up!',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12647,
    season_no: 6,
    ep_no: 6,
    ep_name: 'Filibuster',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12648,
    season_no: 6,
    ep_no: 7,
    ep_name: 'Recall Vote',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12649,
    season_no: 6,
    ep_no: 8,
    ep_name: 'Fluoride',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12650,
    season_no: 6,
    ep_no: 9,
    ep_name: 'The Cones of Dunshire',
    watched: true },
  { user_id: 5,
    tv_id: 174,
    tv_name: 'Parks and Recreation',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/2439.jpg',
    ep_id: 12651,
    season_no: 6,
    ep_no: 10,
    ep_name: 'Second Chunce',
    watched: true }, { user_id: 5,
    tv_id: 335,
    tv_name: 'Sherlock',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5311.jpg',
    ep_id: 32178,
    season_no: 1,
    ep_no: 1,
    ep_name: 'A Study in Pink',
    watched: true },
  { user_id: 5,
    tv_id: 335,
    tv_name: 'Sherlock',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5311.jpg',
    ep_id: 32179,
    season_no: 1,
    ep_no: 2,
    ep_name: 'The Blind Banker',
    watched: true },
  { user_id: 5,
    tv_id: 335,
    tv_name: 'Sherlock',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5311.jpg',
    ep_id: 32180,
    season_no: 1,
    ep_no: 3,
    ep_name: 'The Great Game',
    watched: true },
  { user_id: 5,
    tv_id: 335,
    tv_name: 'Sherlock',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5311.jpg',
    ep_id: 32181,
    season_no: 2,
    ep_no: 1,
    ep_name: 'A Scandal in Belgravia',
    watched: true },
  { user_id: 5,
    tv_id: 335,
    tv_name: 'Sherlock',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5311.jpg',
    ep_id: 32182,
    season_no: 2,
    ep_no: 2,
    ep_name: 'The Hounds of Baskerville',
    watched: true },
  { user_id: 5,
    tv_id: 335,
    tv_name: 'Sherlock',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5311.jpg',
    ep_id: 32183,
    season_no: 2,
    ep_no: 3,
    ep_name: 'The Reichenbach Fall',
    watched: true },
  { user_id: 5,
    tv_id: 335,
    tv_name: 'Sherlock',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5311.jpg',
    ep_id: 32184,
    season_no: 3,
    ep_no: 1,
    ep_name: 'The Empty Hearse',
    watched: true },
  { user_id: 5,
    tv_id: 335,
    tv_name: 'Sherlock',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5311.jpg',
    ep_id: 32185,
    season_no: 3,
    ep_no: 2,
    ep_name: 'The Sign of Three',
    watched: true },
  { user_id: 5,
    tv_id: 335,
    tv_name: 'Sherlock',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5311.jpg',
    ep_id: 32186,
    season_no: 3,
    ep_no: 3,
    ep_name: 'His Last Vow',
    watched: true },
  { user_id: 5,
    tv_id: 335,
    tv_name: 'Sherlock',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5311.jpg',
    ep_id: 941297,
    season_no: 4,
    ep_no: 1,
    ep_name: 'The Six Thatchers',
    watched: true },
  { user_id: 5,
    tv_id: 335,
    tv_name: 'Sherlock',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5311.jpg',
    ep_id: 941298,
    season_no: 4,
    ep_no: 2,
    ep_name: 'The Lying Detective',
    watched: true },
  { user_id: 5,
    tv_id: 335,
    tv_name: 'Sherlock',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5311.jpg',
    ep_id: 1004191,
    season_no: 4,
    ep_no: 3,
    ep_name: 'The Final Problem',
    watched: true },
    { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4095,
    season_no: 1,
    ep_no: 1,
    ep_name: 'Days Gone Bye',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4096,
    season_no: 1,
    ep_no: 2,
    ep_name: 'Guts',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4097,
    season_no: 1,
    ep_no: 3,
    ep_name: 'Tell It to the Frogs',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4098,
    season_no: 1,
    ep_no: 4,
    ep_name: 'Vatos',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4099,
    season_no: 1,
    ep_no: 5,
    ep_name: 'Wildfire',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4100,
    season_no: 1,
    ep_no: 6,
    ep_name: 'TS-19',
    watched: true },
    { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4101,
    season_no: 2,
    ep_no: 1,
    ep_name: 'What Lies Ahead',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4102,
    season_no: 2,
    ep_no: 2,
    ep_name: 'Bloodletting',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4103,
    season_no: 2,
    ep_no: 3,
    ep_name: 'Save the Last One',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4104,
    season_no: 2,
    ep_no: 4,
    ep_name: 'Cherokee Rose',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4105,
    season_no: 2,
    ep_no: 5,
    ep_name: 'Chupacabra',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4106,
    season_no: 2,
    ep_no: 6,
    ep_name: 'Secrets',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4107,
    season_no: 2,
    ep_no: 7,
    ep_name: 'Pretty Much Dead Already',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4108,
    season_no: 2,
    ep_no: 8,
    ep_name: 'Nebraska',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4109,
    season_no: 2,
    ep_no: 9,
    ep_name: 'Triggerfinger',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4110,
    season_no: 2,
    ep_no: 10,
    ep_name: '18 Miles Out',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4111,
    season_no: 2,
    ep_no: 11,
    ep_name: 'Judge, Jury, Executioner',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4112,
    season_no: 2,
    ep_no: 12,
    ep_name: 'Better Angels',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4113,
    season_no: 2,
    ep_no: 13,
    ep_name: 'Beside the Dying Fire',
    watched: true },
    { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4114,
    season_no: 3,
    ep_no: 1,
    ep_name: 'Seed',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4115,
    season_no: 3,
    ep_no: 2,
    ep_name: 'Sick',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4116,
    season_no: 3,
    ep_no: 3,
    ep_name: 'Walk with Me',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4117,
    season_no: 3,
    ep_no: 4,
    ep_name: 'Killer Within',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4118,
    season_no: 3,
    ep_no: 5,
    ep_name: 'Say the Word',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4119,
    season_no: 3,
    ep_no: 6,
    ep_name: 'Hounded',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4120,
    season_no: 3,
    ep_no: 7,
    ep_name: 'When the Dead Come Knocking',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4121,
    season_no: 3,
    ep_no: 8,
    ep_name: 'Made to Suffer',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4122,
    season_no: 3,
    ep_no: 9,
    ep_name: 'The Suicide King',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4123,
    season_no: 3,
    ep_no: 10,
    ep_name: 'Home',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4124,
    season_no: 3,
    ep_no: 11,
    ep_name: 'I Ain\'t a Judas',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4125,
    season_no: 3,
    ep_no: 12,
    ep_name: 'Clear',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4126,
    season_no: 3,
    ep_no: 13,
    ep_name: 'Arrow on the Doorpost',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4127,
    season_no: 3,
    ep_no: 14,
    ep_name: 'Prey',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4128,
    season_no: 3,
    ep_no: 15,
    ep_name: 'This Sorrowful Life',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4129,
    season_no: 3,
    ep_no: 16,
    ep_name: 'Welcome to the Tombs',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4130,
    season_no: 4,
    ep_no: 1,
    ep_name: '30 Days Without an Accident',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4131,
    season_no: 4,
    ep_no: 2,
    ep_name: 'Infected',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4132,
    season_no: 4,
    ep_no: 3,
    ep_name: 'Isolation',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4133,
    season_no: 4,
    ep_no: 4,
    ep_name: 'Indifference',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4134,
    season_no: 4,
    ep_no: 5,
    ep_name: 'Internment',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4135,
    season_no: 4,
    ep_no: 6,
    ep_name: 'Live Bait',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4136,
    season_no: 4,
    ep_no: 7,
    ep_name: 'Dead Weight',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4137,
    season_no: 4,
    ep_no: 8,
    ep_name: 'Too Far Gone',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4138,
    season_no: 4,
    ep_no: 9,
    ep_name: 'After',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4139,
    season_no: 4,
    ep_no: 10,
    ep_name: 'Inmates',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4140,
    season_no: 4,
    ep_no: 11,
    ep_name: 'Claimed',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4141,
    season_no: 4,
    ep_no: 12,
    ep_name: 'Still',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4142,
    season_no: 4,
    ep_no: 13,
    ep_name: 'Alone',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4143,
    season_no: 4,
    ep_no: 14,
    ep_name: 'The Grove',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4144,
    season_no: 4,
    ep_no: 15,
    ep_name: 'Us',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4145,
    season_no: 4,
    ep_no: 16,
    ep_name: 'A',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4146,
    season_no: 5,
    ep_no: 1,
    ep_name: 'No Sanctuary',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4147,
    season_no: 5,
    ep_no: 2,
    ep_name: 'Strangers',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4148,
    season_no: 5,
    ep_no: 3,
    ep_name: 'Four Walls and a Roof',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 14103,
    season_no: 5,
    ep_no: 4,
    ep_name: 'Slabtown',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 15852,
    season_no: 5,
    ep_no: 5,
    ep_name: 'Self Help',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 15853,
    season_no: 5,
    ep_no: 6,
    ep_name: 'Consumed',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 15854,
    season_no: 5,
    ep_no: 7,
    ep_name: 'Crossed',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 15855,
    season_no: 5,
    ep_no: 8,
    ep_name: 'Coda',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 15856,
    season_no: 5,
    ep_no: 9,
    ep_name: 'What Happened and What\'s Going On',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 15857,
    season_no: 5,
    ep_no: 10,
    ep_name: 'Them',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 15858,
    season_no: 5,
    ep_no: 11,
    ep_name: 'The Distance',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 15859,
    season_no: 5,
    ep_no: 12,
    ep_name: 'Remember',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 15860,
    season_no: 5,
    ep_no: 13,
    ep_name: 'Forget',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 15861,
    season_no: 5,
    ep_no: 14,
    ep_name: 'Spend',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 15862,
    season_no: 5,
    ep_no: 15,
    ep_name: 'Try',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 15863,
    season_no: 5,
    ep_no: 16,
    ep_name: 'Conquer',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 185066,
    season_no: 6,
    ep_no: 1,
    ep_name: 'First Time Again',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 185067,
    season_no: 6,
    ep_no: 2,
    ep_name: 'JSS',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 185068,
    season_no: 6,
    ep_no: 3,
    ep_name: 'Thank You',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 185069,
    season_no: 6,
    ep_no: 4,
    ep_name: 'Here\'s Not Here',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 185070,
    season_no: 6,
    ep_no: 5,
    ep_name: 'Now',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 185071,
    season_no: 6,
    ep_no: 6,
    ep_name: 'Always Accountable',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 185072,
    season_no: 6,
    ep_no: 7,
    ep_name: 'Heads Up',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 185073,
    season_no: 6,
    ep_no: 8,
    ep_name: 'Start to Finish',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 384350,
    season_no: 6,
    ep_no: 9,
    ep_name: 'No Way Out',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 483068,
    season_no: 6,
    ep_no: 10,
    ep_name: 'The Next World',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 483069,
    season_no: 6,
    ep_no: 11,
    ep_name: 'Knots Untie',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 628794,
    season_no: 6,
    ep_no: 12,
    ep_name: 'Not Tomorrow Yet',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 638714,
    season_no: 6,
    ep_no: 13,
    ep_name: 'The Same Boat',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 639987,
    season_no: 6,
    ep_no: 14,
    ep_name: 'Twice as Far',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 639988,
    season_no: 6,
    ep_no: 15,
    ep_name: 'East',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 639999,
    season_no: 6,
    ep_no: 16,
    ep_name: 'Last Day on Earth',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 707345,
    season_no: 7,
    ep_no: 1,
    ep_name: 'The Day Will Come When You Won\'t Be',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 895793,
    season_no: 7,
    ep_no: 2,
    ep_name: 'The Well',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 895794,
    season_no: 7,
    ep_no: 3,
    ep_name: 'The Cell',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 895795,
    season_no: 7,
    ep_no: 4,
    ep_name: 'Service',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 895796,
    season_no: 7,
    ep_no: 5,
    ep_name: 'Go Getters',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 895797,
    season_no: 7,
    ep_no: 6,
    ep_name: 'Swear',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 895798,
    season_no: 7,
    ep_no: 7,
    ep_name: 'Sing Me a Song',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 895799,
    season_no: 7,
    ep_no: 8,
    ep_name: 'Hearts Still Beating',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 1013811,
    season_no: 7,
    ep_no: 9,
    ep_name: 'Rock in the Road',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 1055161,
    season_no: 7,
    ep_no: 10,
    ep_name: 'New Best Friends',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 1063327,
    season_no: 7,
    ep_no: 11,
    ep_name: 'Hostiles and Calamities',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 1063328,
    season_no: 7,
    ep_no: 12,
    ep_name: 'Say Yes',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 1063329,
    season_no: 7,
    ep_no: 13,
    ep_name: 'Bury Me Here',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 1063330,
    season_no: 7,
    ep_no: 14,
    ep_name: 'The Other Side',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 1063331,
    season_no: 7,
    ep_no: 15,
    ep_name: 'Something They Need',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 1063332,
    season_no: 7,
    ep_no: 16,
    ep_name: 'The First Day of the Rest of Your Life',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 1254265,
    season_no: 8,
    ep_no: 1,
    ep_name: 'Mercy',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 1319895,
    season_no: 8,
    ep_no: 2,
    ep_name: 'The Damned',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 1320243,
    season_no: 8,
    ep_no: 3,
    ep_name: 'Monsters',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 1335911,
    season_no: 8,
    ep_no: 4,
    ep_name: 'Some Guy',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 1335912,
    season_no: 8,
    ep_no: 5,
    ep_name: 'The Big Scary U',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 1336334,
    season_no: 8,
    ep_no: 6,
    ep_name: 'The King, the Widow, and Rick',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 1336335,
    season_no: 8,
    ep_no: 7,
    ep_name: 'Time for After',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 1336336,
    season_no: 8,
    ep_no: 8,
    ep_name: 'How It\'s Gotta Be',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 1371551,
    season_no: 8,
    ep_no: 9,
    ep_name: 'Honor',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 1406101,
    season_no: 8,
    ep_no: 10,
    ep_name: 'The Lost and the Plunderers',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 1409522,
    season_no: 8,
    ep_no: 11,
    ep_name: 'Dead or Alive Or',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 1409523,
    season_no: 8,
    ep_no: 12,
    ep_name: 'The Key',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 1409524,
    season_no: 8,
    ep_no: 13,
    ep_name: 'Do Not Send Us Astray',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 1409525,
    season_no: 8,
    ep_no: 14,
    ep_name: 'Still Gotta Mean Something',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 1409526,
    season_no: 8,
    ep_no: 15,
    ep_name: 'Worth',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 1409696,
    season_no: 8,
    ep_no: 16,
    ep_name: 'Wrath',
    watched: true },
  { user_id: 5,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 1499273,
    season_no: 9,
    ep_no: 1,
    ep_name: 'A New Beginning',
    watched: true }  
    ])
    .then(() => {
      return knex.raw(`SELECT setval('${table}_id_seq', (SELECT MAX(id) FROM ${table}));`)
    })
};
