const table = 'episodes'
exports.seed = knex => {
  return knex(table)
    .insert([{ user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 21348,
    season_no: 1,
    ep_no: 1,
    ep_name: 'Myanmar',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 21349,
    season_no: 1,
    ep_no: 2,
    ep_name: 'Los Angeles',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 21350,
    season_no: 1,
    ep_no: 3,
    ep_name: 'Colombia',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 21351,
    season_no: 1,
    ep_no: 4,
    ep_name: 'Quebec, Canada',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 21352,
    season_no: 1,
    ep_no: 5,
    ep_name: 'Morocco',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 21353,
    season_no: 1,
    ep_no: 6,
    ep_name: 'Libya',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 21354,
    season_no: 1,
    ep_no: 7,
    ep_name: 'Peru',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 21355,
    season_no: 1,
    ep_no: 8,
    ep_name: 'Congo',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 21356,
    season_no: 2,
    ep_no: 1,
    ep_name: 'Jerusalem',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 21357,
    season_no: 2,
    ep_no: 2,
    ep_name: 'Spain',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 21358,
    season_no: 2,
    ep_no: 3,
    ep_name: 'New Mexico',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 21359,
    season_no: 2,
    ep_no: 4,
    ep_name: 'Copenhagen',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 21360,
    season_no: 2,
    ep_no: 5,
    ep_name: 'Sicily',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 21361,
    season_no: 2,
    ep_no: 6,
    ep_name: 'South Africa',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 21362,
    season_no: 2,
    ep_no: 7,
    ep_name: 'Tokyo',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 21363,
    season_no: 2,
    ep_no: 8,
    ep_name: 'Detroit',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 21364,
    season_no: 3,
    ep_no: 1,
    ep_name: 'Punjab, India',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 21365,
    season_no: 3,
    ep_no: 2,
    ep_name: 'Las Vegas',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 21366,
    season_no: 3,
    ep_no: 3,
    ep_name: 'Lyon, France',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 21367,
    season_no: 3,
    ep_no: 4,
    ep_name: 'Mexico City',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 21368,
    season_no: 3,
    ep_no: 5,
    ep_name: 'Russia',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 21369,
    season_no: 3,
    ep_no: 6,
    ep_name: 'Mississippi Delta',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 21370,
    season_no: 3,
    ep_no: 7,
    ep_name: 'Thailand',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 21371,
    season_no: 3,
    ep_no: 8,
    ep_name: 'Brazil',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 21372,
    season_no: 4,
    ep_no: 1,
    ep_name: 'Shanghai',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 21373,
    season_no: 4,
    ep_no: 2,
    ep_name: 'The Bronx',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 21374,
    season_no: 4,
    ep_no: 3,
    ep_name: 'Paraguay',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 21375,
    season_no: 4,
    ep_no: 4,
    ep_name: 'Vietnam',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 21376,
    season_no: 4,
    ep_no: 5,
    ep_name: 'Tanzania',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 39421,
    season_no: 4,
    ep_no: 6,
    ep_name: 'Iran',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 39422,
    season_no: 4,
    ep_no: 7,
    ep_name: 'Massachusetts',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 39423,
    season_no: 4,
    ep_no: 8,
    ep_name: 'Jamaica',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 153995,
    season_no: 5,
    ep_no: 1,
    ep_name: 'South Korea',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 154024,
    season_no: 5,
    ep_no: 2,
    ep_name: 'Miami',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 154025,
    season_no: 5,
    ep_no: 3,
    ep_name: 'Scotland',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 154026,
    season_no: 5,
    ep_no: 4,
    ep_name: 'Madagascar',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 154027,
    season_no: 5,
    ep_no: 5,
    ep_name: 'New Jersey',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 154028,
    season_no: 5,
    ep_no: 6,
    ep_name: 'Budapest',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 154029,
    season_no: 5,
    ep_no: 7,
    ep_name: 'Hawaii',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 154030,
    season_no: 5,
    ep_no: 8,
    ep_name: 'Beirut',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 220055,
    season_no: 6,
    ep_no: 1,
    ep_name: 'Cuba',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 220056,
    season_no: 6,
    ep_no: 2,
    ep_name: 'Marseille, France',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 220057,
    season_no: 6,
    ep_no: 3,
    ep_name: 'Okinawa, Japan',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 220059,
    season_no: 6,
    ep_no: 4,
    ep_name: 'Bay Area',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 220058,
    season_no: 6,
    ep_no: 5,
    ep_name: 'Ethiopia',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 220060,
    season_no: 6,
    ep_no: 6,
    ep_name: 'Borneo',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 220061,
    season_no: 6,
    ep_no: 7,
    ep_name: 'Istanbul',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 220062,
    season_no: 6,
    ep_no: 8,
    ep_name: 'Charleston, S.C.',
    watched: true },{ user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 919428,
    season_no: 8,
    ep_no: 2,
    ep_name: 'Nashville',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 919429,
    season_no: 8,
    ep_no: 3,
    ep_name: 'Sichuan with Eric Ripert',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 919430,
    season_no: 8,
    ep_no: 4,
    ep_name: 'London',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 919431,
    season_no: 8,
    ep_no: 5,
    ep_name: 'Houston',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 919432,
    season_no: 8,
    ep_no: 6,
    ep_name: 'Japan with Masa',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 1004048,
    season_no: 8,
    ep_no: 7,
    ep_name: 'Buenos Aires',
    watched: true },{ user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 1138876,
    season_no: 9,
    ep_no: 4,
    ep_name: 'Queens',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 1138877,
    season_no: 9,
    ep_no: 5,
    ep_name: 'Antarctica',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 1138878,
    season_no: 9,
    ep_no: 6,
    ep_name: 'Oman',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 1138879,
    season_no: 9,
    ep_no: 7,
    ep_name: 'Trinidad',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 1138880,
    season_no: 9,
    ep_no: 8,
    ep_name: 'Porto, Portugal',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 1304418,
    season_no: 10,
    ep_no: 1,
    ep_name: 'Singapore',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 1314879,
    season_no: 10,
    ep_no: 2,
    ep_name: 'French Alps',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 1314881,
    season_no: 10,
    ep_no: 3,
    ep_name: 'Lagos, Nigeria',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 1314882,
    season_no: 10,
    ep_no: 4,
    ep_name: 'Pittsburgh',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 1314884,
    season_no: 10,
    ep_no: 5,
    ep_name: 'Sri Lanka',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 1314886,
    season_no: 10,
    ep_no: 6,
    ep_name: 'Puerto Rico',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 1314888,
    season_no: 10,
    ep_no: 7,
    ep_name: 'Seattle',
    watched: true },{ user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 1444084,
    season_no: 11,
    ep_no: 8,
    ep_name: 'Bhutan',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 1532907,
    season_no: 12,
    ep_no: 1,
    ep_name: 'Kenya',
    watched: true },
  { user_id: 6,
    tv_id: 255,
    tv_name: 'Anthony Bourdain: Parts Unknown',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/4660.jpg',
    ep_id: 1079685,
    season_no: 12,
    ep_no: 2,
    ep_name: 'Asturias, Spain',
    watched: true },
    { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 33873,
    season_no: 39,
    ep_no: 1,
    ep_name: 'Tina Fey / Arcade Fire',
    watched: true },
  { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 33874,
    season_no: 39,
    ep_no: 2,
    ep_name: 'Miley Cyrus',
    watched: true },
  { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 33875,
    season_no: 39,
    ep_no: 3,
    ep_name: 'Bruce Willis / Katy Perry',
    watched: true },
  { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 33876,
    season_no: 39,
    ep_no: 4,
    ep_name: 'Edward Norton / Janelle Monáe',
    watched: true },
  { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 33877,
    season_no: 39,
    ep_no: 5,
    ep_name: 'Kerry Washington / Eminem',
    watched: true },
  { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 33878,
    season_no: 39,
    ep_no: 6,
    ep_name: 'Lady Gaga',
    watched: true },
  { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 33879,
    season_no: 39,
    ep_no: 7,
    ep_name: 'Josh Hutcherson / HAIM',
    watched: true },
  { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 33880,
    season_no: 39,
    ep_no: 8,
    ep_name: 'Paul Rudd / One Direction',
    watched: true },
  { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 33881,
    season_no: 39,
    ep_no: 9,
    ep_name: 'John Goodman / Kings of Leon',
    watched: true },
  { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 33882,
    season_no: 39,
    ep_no: 10,
    ep_name: 'Jimmy Fallon / Justin Timberlake',
    watched: true },
  { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 33883,
    season_no: 39,
    ep_no: 11,
    ep_name: 'Drake',
    watched: true },
  { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 33884,
    season_no: 39,
    ep_no: 12,
    ep_name: 'Jonah Hill / Bastille',
    watched: true },
  { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 33885,
    season_no: 39,
    ep_no: 13,
    ep_name: 'Melissa McCarthy / Imagine Dragons',
    watched: true },
  { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 33886,
    season_no: 39,
    ep_no: 14,
    ep_name: 'Jim Parsons / Beck',
    watched: true },
  { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 33887,
    season_no: 39,
    ep_no: 15,
    ep_name: 'Lena Dunham / The National',
    watched: true },
  { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 33888,
    season_no: 39,
    ep_no: 16,
    ep_name: 'Louis C.K. / Sam Smith',
    watched: true },
  { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 33889,
    season_no: 39,
    ep_no: 17,
    ep_name: 'Anna Kendrick / Pharell',
    watched: true },
  { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 33890,
    season_no: 39,
    ep_no: 18,
    ep_name: 'Seth Rogen / Ed Sheeran',
    watched: true },
  { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 33891,
    season_no: 39,
    ep_no: 19,
    ep_name: 'Andrew Garfield / Coldplay',
    watched: true },
  { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 33892,
    season_no: 39,
    ep_no: 20,
    ep_name: 'Charlize Theron / The Black Keys',
    watched: true },
  { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 33893,
    season_no: 39,
    ep_no: 21,
    ep_name: 'Andy Samberg / St. Vincent',
    watched: true }, { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 938120,
    season_no: 42,
    ep_no: 1,
    ep_name: 'Margot Robbie / The Weeknd',
    watched: true },
  { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 944500,
    season_no: 42,
    ep_no: 2,
    ep_name: 'Lin-Manuel Miranda / Twenty One Pilots',
    watched: true },
  { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 954385,
    season_no: 42,
    ep_no: 3,
    ep_name: 'Emily Blunt / Bruno Mars',
    watched: true },
  { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 954987,
    season_no: 42,
    ep_no: 4,
    ep_name: 'Tom Hanks / Lady Gaga',
    watched: true },
  { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 970295,
    season_no: 42,
    ep_no: 5,
    ep_name: 'Benedict Cumberbatch / Solange',
    watched: true },
  { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 981086,
    season_no: 42,
    ep_no: 6,
    ep_name: 'Dave Chappelle / A Tribe Called Quest',
    watched: true },
  { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 985708,
    season_no: 42,
    ep_no: 7,
    ep_name: 'Kristen Wiig / The xx',
    watched: true },
  { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 993868,
    season_no: 42,
    ep_no: 8,
    ep_name: 'Emma Stone / Shawn Mendes',
    watched: true },
  { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 1000225,
    season_no: 42,
    ep_no: 9,
    ep_name: 'John Cena / Maren Morris',
    watched: true },
  { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 1004451,
    season_no: 42,
    ep_no: 10,
    ep_name: 'Casey Affleck / Chance The Rapper',
    watched: true },
  { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 1017347,
    season_no: 42,
    ep_no: 11,
    ep_name: 'Felicity Jones / Sturgill Simpson',
    watched: true },
  { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 1038738,
    season_no: 42,
    ep_no: 12,
    ep_name: 'Aziz Ansari / Big Sean',
    watched: true },
  { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 1046897,
    season_no: 42,
    ep_no: 13,
    ep_name: 'Kristen Stewart / Alessia Cara',
    watched: true },
  { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 1048338,
    season_no: 42,
    ep_no: 14,
    ep_name: 'Alec Baldwin / Ed Sheeran',
    watched: true },
  { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 1066675,
    season_no: 42,
    ep_no: 15,
    ep_name: 'Octavia Spencer / Father John Misty',
    watched: true },
  { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 1081252,
    season_no: 42,
    ep_no: 16,
    ep_name: 'Scarlett Johansson / Lorde',
    watched: true },
  { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 1094733,
    season_no: 42,
    ep_no: 17,
    ep_name: 'Louis C.K. / The Chainsmokers',
    watched: true },
  { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 1101229,
    season_no: 42,
    ep_no: 18,
    ep_name: 'Jimmy Fallon / Harry Styles',
    watched: true },
  { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 1101230,
    season_no: 42,
    ep_no: 19,
    ep_name: 'Chris Pine / LCD Soundsystem',
    watched: true },
  { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 1101231,
    season_no: 42,
    ep_no: 20,
    ep_name: 'Melissa McCarthy / HAIM',
    watched: true },
  { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 1101232,
    season_no: 42,
    ep_no: 21,
    ep_name: 'Dwayne Johnson / Katy Perry',
    watched: true },
    { user_id: 6,
    tv_id: 361,
    tv_name: 'Saturday Night Live',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/2/5468.jpg',
    ep_id: 1520911,
    season_no: 44,
    ep_no: 1,
    ep_name: 'Adam Driver/Kanye West',
    watched: true },
    { user_id: 6,
    tv_id: 320,
    tv_name: 'The Fall',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/75/188991.jpg',
    ep_id: 31375,
    season_no: 1,
    ep_no: 1,
    ep_name: 'Dark Descent',
    watched: true },
  { user_id: 6,
    tv_id: 320,
    tv_name: 'The Fall',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/75/188991.jpg',
    ep_id: 31376,
    season_no: 1,
    ep_no: 2,
    ep_name: 'Darkness Visible',
    watched: true },
  { user_id: 6,
    tv_id: 320,
    tv_name: 'The Fall',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/75/188991.jpg',
    ep_id: 31377,
    season_no: 1,
    ep_no: 3,
    ep_name: 'Insolence & Wine',
    watched: true },
  { user_id: 6,
    tv_id: 320,
    tv_name: 'The Fall',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/75/188991.jpg',
    ep_id: 31378,
    season_no: 1,
    ep_no: 4,
    ep_name: 'My Adventurous Song',
    watched: true },
  { user_id: 6,
    tv_id: 320,
    tv_name: 'The Fall',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/75/188991.jpg',
    ep_id: 31379,
    season_no: 1,
    ep_no: 5,
    ep_name: 'The Vast Abyss',
    watched: true },
  { user_id: 6,
    tv_id: 320,
    tv_name: 'The Fall',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/75/188991.jpg',
    ep_id: 31380,
    season_no: 2,
    ep_no: 1,
    ep_name: 'These Troublesome Disguises',
    watched: true },
  { user_id: 6,
    tv_id: 320,
    tv_name: 'The Fall',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/75/188991.jpg',
    ep_id: 40396,
    season_no: 2,
    ep_no: 2,
    ep_name: 'Night Darkens the Streets',
    watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493182,
      season_no: 1,
      ep_no: 1,
      ep_name: 'Noodlin\'',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493183,
      season_no: 1,
      ep_no: 2,
      ep_name: 'Squeal Like a Pig',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493184,
      season_no: 1,
      ep_no: 3,
      ep_name: 'Memory Lane',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493185,
      season_no: 1,
      ep_no: 4,
      ep_name: 'Spain',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493186,
      season_no: 1,
      ep_no: 5,
      ep_name: 'Rotten',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493187,
      season_no: 1,
      ep_no: 6,
      ep_name: 'René',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493188,
      season_no: 1,
      ep_no: 7,
      ep_name: 'Simplicity',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493189,
      season_no: 1,
      ep_no: 8,
      ep_name: 'Gluttony',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493190,
      season_no: 1,
      ep_no: 9,
      ep_name: 'Chef',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493191,
      season_no: 1,
      ep_no: 10,
      ep_name: 'Japan',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493192,
      season_no: 1,
      ep_no: 11,
      ep_name: 'New York',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493193,
      season_no: 1,
      ep_no: 12,
      ep_name: 'Fresh',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493194,
      season_no: 1,
      ep_no: 13,
      ep_name: 'Soy',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493195,
      season_no: 1,
      ep_no: 14,
      ep_name: 'Sweet Spot',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493196,
      season_no: 1,
      ep_no: 15,
      ep_name: 'Smoke',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493197,
      season_no: 1,
      ep_no: 16,
      ep_name: 'Buddies',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493198,
      season_no: 2,
      ep_no: 1,
      ep_name: 'Southerners',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493199,
      season_no: 2,
      ep_no: 2,
      ep_name: 'Seeds',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493200,
      season_no: 2,
      ep_no: 3,
      ep_name: 'Rice',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493201,
      season_no: 2,
      ep_no: 4,
      ep_name: 'Louisiana',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493202,
      season_no: 2,
      ep_no: 5,
      ep_name: 'Preserve',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493203,
      season_no: 2,
      ep_no: 6,
      ep_name: 'Roots',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493204,
      season_no: 2,
      ep_no: 7,
      ep_name: 'Low Country BBQ',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493205,
      season_no: 2,
      ep_no: 8,
      ep_name: 'Senegal',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493206,
      season_no: 2,
      ep_no: 9,
      ep_name: 'London',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493207,
      season_no: 2,
      ep_no: 10,
      ep_name: 'Sea/Salt',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493208,
      season_no: 2,
      ep_no: 11,
      ep_name: 'Curry',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493209,
      season_no: 2,
      ep_no: 12,
      ep_name: 'Italian',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493210,
      season_no: 2,
      ep_no: 13,
      ep_name: 'British Classics',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493211,
      season_no: 2,
      ep_no: 14,
      ep_name: 'Farmer',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493212,
      season_no: 2,
      ep_no: 15,
      ep_name: 'Leftovers',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493214,
      season_no: 3,
      ep_no: 1,
      ep_name: 'NYC Origin',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493215,
      season_no: 3,
      ep_no: 2,
      ep_name: 'American',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493216,
      season_no: 3,
      ep_no: 3,
      ep_name: 'Argentina',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493217,
      season_no: 3,
      ep_no: 4,
      ep_name: 'Louisville',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493218,
      season_no: 3,
      ep_no: 5,
      ep_name: 'Kentucky',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493219,
      season_no: 3,
      ep_no: 6,
      ep_name: 'Latitude',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493220,
      season_no: 3,
      ep_no: 7,
      ep_name: 'Impermanence',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493222,
      season_no: 3,
      ep_no: 9,
      ep_name: 'Winter',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493223,
      season_no: 3,
      ep_no: 10,
      ep_name: 'Spring',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493224,
      season_no: 3,
      ep_no: 11,
      ep_name: 'Creation',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493225,
      season_no: 3,
      ep_no: 12,
      ep_name: 'France',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493226,
      season_no: 3,
      ep_no: 13,
      ep_name: 'Traditions',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493227,
      season_no: 3,
      ep_no: 14,
      ep_name: 'Locality',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493228,
      season_no: 3,
      ep_no: 15,
      ep_name: 'Documentation',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493229,
      season_no: 3,
      ep_no: 16,
      ep_name: 'Fäviken',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493230,
      season_no: 4,
      ep_no: 1,
      ep_name: 'Prune',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493231,
      season_no: 4,
      ep_no: 2,
      ep_name: 'Garbage',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493232,
      season_no: 4,
      ep_no: 3,
      ep_name: 'Rome',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493233,
      season_no: 4,
      ep_no: 4,
      ep_name: 'Hunger',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493234,
      season_no: 4,
      ep_no: 5,
      ep_name: 'Past',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493235,
      season_no: 4,
      ep_no: 6,
      ep_name: 'Hustle',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493238,
      season_no: 4,
      ep_no: 9,
      ep_name: 'Fire',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493239,
      season_no: 4,
      ep_no: 10,
      ep_name: 'Legacy',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493240,
      season_no: 4,
      ep_no: 11,
      ep_name: 'Ocean',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493241,
      season_no: 4,
      ep_no: 12,
      ep_name: 'Strawberry',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493242,
      season_no: 4,
      ep_no: 13,
      ep_name: 'Balance',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493243,
      season_no: 4,
      ep_no: 14,
      ep_name: 'Restrictions',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 493244,
      season_no: 4,
      ep_no: 15,
      ep_name: 'New Orleans',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 986605,
      season_no: 5,
      ep_no: 1,
      ep_name: 'Eggs',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 986606,
      season_no: 5,
      ep_no: 2,
      ep_name: 'Legends',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 986607,
      season_no: 5,
      ep_no: 3,
      ep_name: 'Fried',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 986608,
      season_no: 5,
      ep_no: 4,
      ep_name: 'LudoBird',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 986609,
      season_no: 5,
      ep_no: 5,
      ep_name: 'Strip Malls',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 986610,
      season_no: 5,
      ep_no: 6,
      ep_name: 'La Mer',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 986611,
      season_no: 5,
      ep_no: 7,
      ep_name: 'Le Végétale',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 986612,
      season_no: 5,
      ep_no: 8,
      ep_name: 'Joie De Vivre',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 986613,
      season_no: 5,
      ep_no: 9,
      ep_name: 'Tous Au Bistro',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 986614,
      season_no: 5,
      ep_no: 10,
      ep_name: 'Instinct vs. Discipline',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 986615,
      season_no: 5,
      ep_no: 11,
      ep_name: 'LudoBites',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 1349631,
      season_no: 5,
      ep_no: 13,
      ep_name: 'Dessert',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 1349632,
      season_no: 5,
      ep_no: 14,
      ep_name: 'Birds',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 1362605,
      season_no: 6,
      ep_no: 1,
      ep_name: 'Genesis',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 1362606,
      season_no: 6,
      ep_no: 2,
      ep_name: 'Threshold',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 1362607,
      season_no: 6,
      ep_no: 3,
      ep_name: 'Mentor',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 1363821,
      season_no: 6,
      ep_no: 4,
      ep_name: 'Family',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 1363822,
      season_no: 6,
      ep_no: 5,
      ep_name: 'Risk',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 1368270,
      season_no: 6,
      ep_no: 6,
      ep_name: 'Unexpected',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 1372325,
      season_no: 6,
      ep_no: 7,
      ep_name: 'Classics',
      watched: true },
    { user_id: 6,
      tv_id: 9085,
      tv_name: 'The Mind of a Chef',
      image:
       'http://static.tvmaze.com/uploads/images/medium_portrait/32/80261.jpg',
      ep_id: 1376615,
      season_no: 6,
      ep_no: 8,
      ep_name: 'Multiverse',
      watched: true },
      { user_id: 6,
    tv_id: 11962,
    tv_name: 'Cooked',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/45/113944.jpg',
    ep_id: 576979,
    season_no: 1,
    ep_no: 1,
    ep_name: 'Fire',
    watched: true },
  { user_id: 6,
    tv_id: 11962,
    tv_name: 'Cooked',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/45/113944.jpg',
    ep_id: 583113,
    season_no: 1,
    ep_no: 2,
    ep_name: 'Water',
    watched: true },
  { user_id: 6,
    tv_id: 11962,
    tv_name: 'Cooked',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/45/113944.jpg',
    ep_id: 583114,
    season_no: 1,
    ep_no: 3,
    ep_name: 'Air',
    watched: true }


    ])
    .then(() => {
      return knex.raw(`SELECT setval('${table}_id_seq', (SELECT MAX(id) FROM ${table}));`)
    })
};
