const table = 'episodes'
exports.seed = knex => {
  return knex(table)
    .insert([
      { user_id: 7,
    tv_id: 1371,
    tv_name: 'Westworld',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/152/381152.jpg',
    ep_id: 869671,
    season_no: 1,
    ep_no: 1,
    ep_name: 'The Original',
    watched: true },
  { user_id: 7,
    tv_id: 1371,
    tv_name: 'Westworld',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/152/381152.jpg',
    ep_id: 911201,
    season_no: 1,
    ep_no: 2,
    ep_name: 'Chestnut',
    watched: true },
  { user_id: 7,
    tv_id: 1371,
    tv_name: 'Westworld',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/152/381152.jpg',
    ep_id: 911204,
    season_no: 1,
    ep_no: 3,
    ep_name: 'The Stray',
    watched: true },
  { user_id: 7,
    tv_id: 1371,
    tv_name: 'Westworld',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/152/381152.jpg',
    ep_id: 911205,
    season_no: 1,
    ep_no: 4,
    ep_name: 'Dissonance Theory',
    watched: true },
  { user_id: 7,
    tv_id: 1371,
    tv_name: 'Westworld',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/152/381152.jpg',
    ep_id: 927174,
    season_no: 1,
    ep_no: 5,
    ep_name: 'Contrapasso',
    watched: true },
  { user_id: 7,
    tv_id: 1371,
    tv_name: 'Westworld',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/152/381152.jpg',
    ep_id: 932057,
    season_no: 1,
    ep_no: 6,
    ep_name: 'The Adversary',
    watched: true },
  { user_id: 7,
    tv_id: 1371,
    tv_name: 'Westworld',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/152/381152.jpg',
    ep_id: 938404,
    season_no: 1,
    ep_no: 7,
    ep_name: 'Trompe L\'Oeil',
    watched: true },
  { user_id: 7,
    tv_id: 1371,
    tv_name: 'Westworld',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/152/381152.jpg',
    ep_id: 943065,
    season_no: 1,
    ep_no: 8,
    ep_name: 'Trace Decay',
    watched: true },
  { user_id: 7,
    tv_id: 1371,
    tv_name: 'Westworld',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/152/381152.jpg',
    ep_id: 943066,
    season_no: 1,
    ep_no: 9,
    ep_name: 'The Well-Tempered Clavier',
    watched: true },
  { user_id: 7,
    tv_id: 1371,
    tv_name: 'Westworld',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/152/381152.jpg',
    ep_id: 943067,
    season_no: 1,
    ep_no: 10,
    ep_name: 'The Bicameral Mind',
    watched: true },
  { user_id: 7,
    tv_id: 1371,
    tv_name: 'Westworld',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/152/381152.jpg',
    ep_id: 1214222,
    season_no: 2,
    ep_no: 1,
    ep_name: 'Journey Into Night',
    watched: true },
  { user_id: 7,
    tv_id: 1371,
    tv_name: 'Westworld',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/152/381152.jpg',
    ep_id: 1440915,
    season_no: 2,
    ep_no: 2,
    ep_name: 'Reunion',
    watched: true },
  { user_id: 7,
    tv_id: 1371,
    tv_name: 'Westworld',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/152/381152.jpg',
    ep_id: 1440916,
    season_no: 2,
    ep_no: 3,
    ep_name: 'Virtù e Fortuna',
    watched: true },
  { user_id: 7,
    tv_id: 1371,
    tv_name: 'Westworld',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/152/381152.jpg',
    ep_id: 1440917,
    season_no: 2,
    ep_no: 4,
    ep_name: 'The Riddle of the Sphinx',
    watched: true },
  { user_id: 7,
    tv_id: 1371,
    tv_name: 'Westworld',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/152/381152.jpg',
    ep_id: 1446362,
    season_no: 2,
    ep_no: 5,
    ep_name: 'Akane No Mai',
    watched: true },
  { user_id: 7,
    tv_id: 1371,
    tv_name: 'Westworld',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/152/381152.jpg',
    ep_id: 1453278,
    season_no: 2,
    ep_no: 6,
    ep_name: 'Phase Space',
    watched: true },
    { user_id: 7,
    tv_id: 216,
    tv_name: 'Rick and Morty',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/3603.jpg',
    ep_id: 14308,
    season_no: 1,
    ep_no: 1,
    ep_name: 'Pilot',
    watched: true },
  { user_id: 7,
    tv_id: 216,
    tv_name: 'Rick and Morty',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/3603.jpg',
    ep_id: 14309,
    season_no: 1,
    ep_no: 2,
    ep_name: 'Lawnmower Dog',
    watched: true },
  { user_id: 7,
    tv_id: 216,
    tv_name: 'Rick and Morty',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/3603.jpg',
    ep_id: 14310,
    season_no: 1,
    ep_no: 3,
    ep_name: 'Anatomy Park',
    watched: true },
  { user_id: 7,
    tv_id: 216,
    tv_name: 'Rick and Morty',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/3603.jpg',
    ep_id: 14311,
    season_no: 1,
    ep_no: 4,
    ep_name: 'M. Night Shaym-Aliens!',
    watched: true },
  { user_id: 7,
    tv_id: 216,
    tv_name: 'Rick and Morty',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/3603.jpg',
    ep_id: 14312,
    season_no: 1,
    ep_no: 5,
    ep_name: 'Meeseeks and Destroy',
    watched: true },
  { user_id: 7,
    tv_id: 216,
    tv_name: 'Rick and Morty',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/3603.jpg',
    ep_id: 14313,
    season_no: 1,
    ep_no: 6,
    ep_name: 'Rick Potion #9',
    watched: true },
  { user_id: 7,
    tv_id: 216,
    tv_name: 'Rick and Morty',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/3603.jpg',
    ep_id: 14314,
    season_no: 1,
    ep_no: 7,
    ep_name: 'Raising Gazorpazorp',
    watched: true },
  { user_id: 7,
    tv_id: 216,
    tv_name: 'Rick and Morty',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/3603.jpg',
    ep_id: 14315,
    season_no: 1,
    ep_no: 8,
    ep_name: 'Rixty Minutes',
    watched: true },
  { user_id: 7,
    tv_id: 216,
    tv_name: 'Rick and Morty',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/3603.jpg',
    ep_id: 14316,
    season_no: 1,
    ep_no: 9,
    ep_name: 'Something Ricked This Way Comes',
    watched: true },
  { user_id: 7,
    tv_id: 216,
    tv_name: 'Rick and Morty',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/3603.jpg',
    ep_id: 14317,
    season_no: 1,
    ep_no: 10,
    ep_name: 'Close Rick-Counters of the Rick Kind',
    watched: true },
  { user_id: 7,
    tv_id: 216,
    tv_name: 'Rick and Morty',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/3603.jpg',
    ep_id: 14318,
    season_no: 1,
    ep_no: 11,
    ep_name: 'Ricksy Business',
    watched: true },
  { user_id: 7,
    tv_id: 216,
    tv_name: 'Rick and Morty',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/3603.jpg',
    ep_id: 157166,
    season_no: 2,
    ep_no: 1,
    ep_name: 'A Rickle in Time',
    watched: true },
  { user_id: 7,
    tv_id: 216,
    tv_name: 'Rick and Morty',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/3603.jpg',
    ep_id: 183053,
    season_no: 2,
    ep_no: 2,
    ep_name: 'Mortynight Run',
    watched: true },
  { user_id: 7,
    tv_id: 216,
    tv_name: 'Rick and Morty',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/3603.jpg',
    ep_id: 201178,
    season_no: 2,
    ep_no: 3,
    ep_name: 'Auto Erotic Assimilation',
    watched: true },
  { user_id: 7,
    tv_id: 216,
    tv_name: 'Rick and Morty',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/3603.jpg',
    ep_id: 201179,
    season_no: 2,
    ep_no: 4,
    ep_name: 'Total Rickall',
    watched: true },
  { user_id: 7,
    tv_id: 216,
    tv_name: 'Rick and Morty',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/3603.jpg',
    ep_id: 201180,
    season_no: 2,
    ep_no: 5,
    ep_name: 'Get Schwifty',
    watched: true },
  { user_id: 7,
    tv_id: 216,
    tv_name: 'Rick and Morty',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/3603.jpg',
    ep_id: 201181,
    season_no: 2,
    ep_no: 6,
    ep_name: 'The Ricks Must Be Crazy',
    watched: true },
  { user_id: 7,
    tv_id: 216,
    tv_name: 'Rick and Morty',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/3603.jpg',
    ep_id: 211831,
    season_no: 2,
    ep_no: 7,
    ep_name: 'Big Trouble in Little Sanchez',
    watched: true },
  { user_id: 7,
    tv_id: 216,
    tv_name: 'Rick and Morty',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/3603.jpg',
    ep_id: 211832,
    season_no: 2,
    ep_no: 8,
    ep_name: 'Interdimensional Cable 2: Tempting Fate',
    watched: true },
  { user_id: 7,
    tv_id: 216,
    tv_name: 'Rick and Morty',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/3603.jpg',
    ep_id: 211833,
    season_no: 2,
    ep_no: 9,
    ep_name: 'Look Who\'s Purging Now',
    watched: true },
  { user_id: 7,
    tv_id: 216,
    tv_name: 'Rick and Morty',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/3603.jpg',
    ep_id: 211834,
    season_no: 2,
    ep_no: 10,
    ep_name: 'The Wedding Squanchers',
    watched: true },
  { user_id: 7,
    tv_id: 216,
    tv_name: 'Rick and Morty',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/3603.jpg',
    ep_id: 1119144,
    season_no: 3,
    ep_no: 1,
    ep_name: 'The Rickshank Rickdemption',
    watched: true },
  { user_id: 7,
    tv_id: 216,
    tv_name: 'Rick and Morty',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/3603.jpg',
    ep_id: 1144079,
    season_no: 3,
    ep_no: 2,
    ep_name: 'Rickmancing the Stone',
    watched: true },
  { user_id: 7,
    tv_id: 216,
    tv_name: 'Rick and Morty',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/3603.jpg',
    ep_id: 1247370,
    season_no: 3,
    ep_no: 3,
    ep_name: 'Pickle Rick',
    watched: true },
  { user_id: 7,
    tv_id: 216,
    tv_name: 'Rick and Morty',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/3603.jpg',
    ep_id: 1247371,
    season_no: 3,
    ep_no: 4,
    ep_name: 'Vindicators 3: The Return of Worldender',
    watched: true },
  { user_id: 7,
    tv_id: 216,
    tv_name: 'Rick and Morty',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/3603.jpg',
    ep_id: 1264543,
    season_no: 3,
    ep_no: 5,
    ep_name: 'The Whirly Dirly Conspiracy',
    watched: true },
  { user_id: 7,
    tv_id: 216,
    tv_name: 'Rick and Morty',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/3603.jpg',
    ep_id: 1264544,
    season_no: 3,
    ep_no: 6,
    ep_name: 'Rest and Ricklaxation',
    watched: true },
  { user_id: 7,
    tv_id: 216,
    tv_name: 'Rick and Morty',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/3603.jpg',
    ep_id: 1269493,
    season_no: 3,
    ep_no: 7,
    ep_name: 'The Ricklantis Mixup',
    watched: true },
  { user_id: 7,
    tv_id: 216,
    tv_name: 'Rick and Morty',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/3603.jpg',
    ep_id: 1269494,
    season_no: 3,
    ep_no: 8,
    ep_name: 'Morty\'s Mind Blowers',
    watched: true },
  { user_id: 7,
    tv_id: 216,
    tv_name: 'Rick and Morty',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/3603.jpg',
    ep_id: 1285112,
    season_no: 3,
    ep_no: 9,
    ep_name: 'The ABC\'s of Beth',
    watched: true },
  { user_id: 7,
    tv_id: 216,
    tv_name: 'Rick and Morty',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/1/3603.jpg',
    ep_id: 1285113,
    season_no: 3,
    ep_no: 10,
    ep_name: 'The Rickchurian Mortydate',
    watched: true }, { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7819,
    season_no: 1,
    ep_no: 1,
    ep_name: 'Pilot',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7820,
    season_no: 1,
    ep_no: 2,
    ep_name: 'The Thing You Love Most',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7821,
    season_no: 1,
    ep_no: 3,
    ep_name: 'Snow Falls',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7822,
    season_no: 1,
    ep_no: 4,
    ep_name: 'The Price of Gold',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7823,
    season_no: 1,
    ep_no: 5,
    ep_name: 'That Still Small Voice',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7824,
    season_no: 1,
    ep_no: 6,
    ep_name: 'The Shepherd',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7825,
    season_no: 1,
    ep_no: 7,
    ep_name: 'The Heart is a Lonely Hunter',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7826,
    season_no: 1,
    ep_no: 8,
    ep_name: 'Desperate Souls',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7827,
    season_no: 1,
    ep_no: 9,
    ep_name: 'True North',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7828,
    season_no: 1,
    ep_no: 10,
    ep_name: '7:15 A.M.',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7829,
    season_no: 1,
    ep_no: 11,
    ep_name: 'Fruit of the Poisonous Tree',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7830,
    season_no: 1,
    ep_no: 12,
    ep_name: 'Skin Deep',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7831,
    season_no: 1,
    ep_no: 13,
    ep_name: 'What Happened to Frederick',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7832,
    season_no: 1,
    ep_no: 14,
    ep_name: 'Dreamy',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7833,
    season_no: 1,
    ep_no: 15,
    ep_name: 'Red-Handed',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7834,
    season_no: 1,
    ep_no: 16,
    ep_name: 'Heart of Darkness',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7835,
    season_no: 1,
    ep_no: 17,
    ep_name: 'Hat Trick',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7836,
    season_no: 1,
    ep_no: 18,
    ep_name: 'The Stable Boy',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7837,
    season_no: 1,
    ep_no: 19,
    ep_name: 'The Return',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7838,
    season_no: 1,
    ep_no: 20,
    ep_name: 'The Stranger',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7839,
    season_no: 1,
    ep_no: 21,
    ep_name: 'An Apple Red as Blood',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7840,
    season_no: 1,
    ep_no: 22,
    ep_name: 'A Land Without Magic',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7841,
    season_no: 2,
    ep_no: 1,
    ep_name: 'Broken',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7842,
    season_no: 2,
    ep_no: 2,
    ep_name: 'We Are Both',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7843,
    season_no: 2,
    ep_no: 3,
    ep_name: 'Lady of the Lake',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7844,
    season_no: 2,
    ep_no: 4,
    ep_name: 'The Crocodile',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7845,
    season_no: 2,
    ep_no: 5,
    ep_name: 'The Doctor',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7846,
    season_no: 2,
    ep_no: 6,
    ep_name: 'Tallahassee',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7847,
    season_no: 2,
    ep_no: 7,
    ep_name: 'Child of the Moon',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7848,
    season_no: 2,
    ep_no: 8,
    ep_name: 'Into the Deep',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7849,
    season_no: 2,
    ep_no: 9,
    ep_name: 'Queen of Hearts',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7850,
    season_no: 2,
    ep_no: 10,
    ep_name: 'The Cricket Game',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7851,
    season_no: 2,
    ep_no: 11,
    ep_name: 'The Outsider',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7852,
    season_no: 2,
    ep_no: 12,
    ep_name: 'In the Name of the Brother',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7853,
    season_no: 2,
    ep_no: 13,
    ep_name: 'Tiny',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7854,
    season_no: 2,
    ep_no: 14,
    ep_name: 'Manhattan',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7855,
    season_no: 2,
    ep_no: 15,
    ep_name: 'The Queen is Dead',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7856,
    season_no: 2,
    ep_no: 16,
    ep_name: 'The Miller\'s Daughter',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7857,
    season_no: 2,
    ep_no: 17,
    ep_name: 'Welcome to Storybrooke',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7858,
    season_no: 2,
    ep_no: 18,
    ep_name: 'Selfless, Brave and True',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7859,
    season_no: 2,
    ep_no: 19,
    ep_name: 'Lacey',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7860,
    season_no: 2,
    ep_no: 20,
    ep_name: 'The Evil Queen',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7861,
    season_no: 2,
    ep_no: 21,
    ep_name: 'Second Star to the Right',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7862,
    season_no: 2,
    ep_no: 22,
    ep_name: 'And Straight on \'til Morning',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7863,
    season_no: 3,
    ep_no: 1,
    ep_name: 'The Heart of the Truest Believer',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7864,
    season_no: 3,
    ep_no: 2,
    ep_name: 'Lost Girl',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7865,
    season_no: 3,
    ep_no: 3,
    ep_name: 'Quite a Common Fairy',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7866,
    season_no: 3,
    ep_no: 4,
    ep_name: 'Nasty Habits',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7867,
    season_no: 3,
    ep_no: 5,
    ep_name: 'Good Form',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7868,
    season_no: 3,
    ep_no: 6,
    ep_name: 'Ariel',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7869,
    season_no: 3,
    ep_no: 7,
    ep_name: 'Dark Hollow',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7870,
    season_no: 3,
    ep_no: 8,
    ep_name: 'Think Lovely Thoughts',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7871,
    season_no: 3,
    ep_no: 9,
    ep_name: 'Save Henry',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7872,
    season_no: 3,
    ep_no: 10,
    ep_name: 'The New Neverland',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7873,
    season_no: 3,
    ep_no: 11,
    ep_name: 'Going Home',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7874,
    season_no: 3,
    ep_no: 12,
    ep_name: 'New York City Serenade',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7875,
    season_no: 3,
    ep_no: 13,
    ep_name: 'Witch Hunt',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7876,
    season_no: 3,
    ep_no: 14,
    ep_name: 'The Tower',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7877,
    season_no: 3,
    ep_no: 15,
    ep_name: 'Quiet Minds',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7878,
    season_no: 3,
    ep_no: 16,
    ep_name: 'It\'s Not Easy Being Green',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7879,
    season_no: 3,
    ep_no: 17,
    ep_name: 'The Jolly Roger',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7880,
    season_no: 3,
    ep_no: 18,
    ep_name: 'Bleeding Through',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7881,
    season_no: 3,
    ep_no: 19,
    ep_name: 'A Curious Thing',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7882,
    season_no: 3,
    ep_no: 20,
    ep_name: 'Kansas',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7883,
    season_no: 3,
    ep_no: 21,
    ep_name: 'Snow Drifts',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7884,
    season_no: 3,
    ep_no: 22,
    ep_name: 'There\'s No Place Like Home',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7885,
    season_no: 4,
    ep_no: 1,
    ep_name: 'A Tale of Two Sisters',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7886,
    season_no: 4,
    ep_no: 2,
    ep_name: 'White Out',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7887,
    season_no: 4,
    ep_no: 3,
    ep_name: 'Rocky Road',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7888,
    season_no: 4,
    ep_no: 4,
    ep_name: 'The Apprentice',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7889,
    season_no: 4,
    ep_no: 5,
    ep_name: 'Breaking Glass',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 7890,
    season_no: 4,
    ep_no: 6,
    ep_name: 'Family Business',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 13856,
    season_no: 4,
    ep_no: 7,
    ep_name: 'The Snow Queen',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 14072,
    season_no: 4,
    ep_no: 8,
    ep_name: 'Smash the Mirror, Part 1',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 40888,
    season_no: 4,
    ep_no: 9,
    ep_name: 'Smash the Mirror, Part 2',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 14073,
    season_no: 4,
    ep_no: 10,
    ep_name: 'Fall',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 41024,
    season_no: 4,
    ep_no: 11,
    ep_name: 'Shattered Sight',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 57522,
    season_no: 4,
    ep_no: 12,
    ep_name: 'Heroes and Villains',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 140723,
    season_no: 4,
    ep_no: 13,
    ep_name: 'Darkness on the Edge of Town',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 109554,
    season_no: 4,
    ep_no: 14,
    ep_name: 'Unforgiven',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 109555,
    season_no: 4,
    ep_no: 15,
    ep_name: 'Enter the Dragon',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 109556,
    season_no: 4,
    ep_no: 16,
    ep_name: 'Poor Unfortunate Soul',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 118428,
    season_no: 4,
    ep_no: 17,
    ep_name: 'Best Laid Plans',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 128872,
    season_no: 4,
    ep_no: 18,
    ep_name: 'Heart of Gold',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 140335,
    season_no: 4,
    ep_no: 19,
    ep_name: 'Sympathy for the De Vil',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 142389,
    season_no: 4,
    ep_no: 20,
    ep_name: 'Lily',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 152767,
    season_no: 4,
    ep_no: 21,
    ep_name: 'Mother',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 152768,
    season_no: 4,
    ep_no: 22,
    ep_name: 'Operation Mongoose, Part 1',
    watched: true },
  { user_id: 7,
    tv_id: 111,
    tv_name: 'Once Upon a Time',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/127/319360.jpg',
    ep_id: 152769,
    season_no: 4,
    ep_no: 23,
    ep_name: 'Operation Mongoose, Part 2',
    watched: true }, { user_id: 7,
    tv_id: 172,
    tv_name: 'Suits',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/160/402351.jpg',
    ep_id: 12493,
    season_no: 1,
    ep_no: 1,
    ep_name: 'Pilot',
    watched: true },
  { user_id: 7,
    tv_id: 172,
    tv_name: 'Suits',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/160/402351.jpg',
    ep_id: 12495,
    season_no: 1,
    ep_no: 2,
    ep_name: 'Errors and Omissions',
    watched: true },
  { user_id: 7,
    tv_id: 172,
    tv_name: 'Suits',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/160/402351.jpg',
    ep_id: 12496,
    season_no: 1,
    ep_no: 3,
    ep_name: 'Inside Track',
    watched: true },
  { user_id: 7,
    tv_id: 172,
    tv_name: 'Suits',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/160/402351.jpg',
    ep_id: 12497,
    season_no: 1,
    ep_no: 4,
    ep_name: 'Dirty Little Secrets',
    watched: true },
  { user_id: 7,
    tv_id: 172,
    tv_name: 'Suits',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/160/402351.jpg',
    ep_id: 12498,
    season_no: 1,
    ep_no: 5,
    ep_name: 'Bail Out',
    watched: true },
  { user_id: 7,
    tv_id: 172,
    tv_name: 'Suits',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/160/402351.jpg',
    ep_id: 12499,
    season_no: 1,
    ep_no: 6,
    ep_name: 'Tricks of the Trade',
    watched: true },
  { user_id: 7,
    tv_id: 172,
    tv_name: 'Suits',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/160/402351.jpg',
    ep_id: 12500,
    season_no: 1,
    ep_no: 7,
    ep_name: 'Play the Man',
    watched: true },
  { user_id: 7,
    tv_id: 172,
    tv_name: 'Suits',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/160/402351.jpg',
    ep_id: 12501,
    season_no: 1,
    ep_no: 8,
    ep_name: 'Identity Crisis',
    watched: true },
  { user_id: 7,
    tv_id: 172,
    tv_name: 'Suits',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/160/402351.jpg',
    ep_id: 12502,
    season_no: 1,
    ep_no: 9,
    ep_name: 'Undefeated',
    watched: true },
  { user_id: 7,
    tv_id: 172,
    tv_name: 'Suits',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/160/402351.jpg',
    ep_id: 12503,
    season_no: 1,
    ep_no: 10,
    ep_name: 'The Shelf Life',
    watched: true },
  { user_id: 7,
    tv_id: 172,
    tv_name: 'Suits',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/160/402351.jpg',
    ep_id: 12504,
    season_no: 1,
    ep_no: 11,
    ep_name: 'Rules of the Game',
    watched: true },
  { user_id: 7,
    tv_id: 172,
    tv_name: 'Suits',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/160/402351.jpg',
    ep_id: 12505,
    season_no: 1,
    ep_no: 12,
    ep_name: 'Dog Fight',
    watched: true },
  { user_id: 7,
    tv_id: 172,
    tv_name: 'Suits',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/160/402351.jpg',
    ep_id: 12506,
    season_no: 2,
    ep_no: 1,
    ep_name: 'She Knows',
    watched: true },
  { user_id: 7,
    tv_id: 172,
    tv_name: 'Suits',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/160/402351.jpg',
    ep_id: 12507,
    season_no: 2,
    ep_no: 2,
    ep_name: 'The Choice',
    watched: true },
  { user_id: 7,
    tv_id: 172,
    tv_name: 'Suits',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/160/402351.jpg',
    ep_id: 12508,
    season_no: 2,
    ep_no: 3,
    ep_name: 'Meet the New Boss',
    watched: true },
  { user_id: 7,
    tv_id: 172,
    tv_name: 'Suits',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/160/402351.jpg',
    ep_id: 12509,
    season_no: 2,
    ep_no: 4,
    ep_name: 'Discovery',
    watched: true },
  { user_id: 7,
    tv_id: 172,
    tv_name: 'Suits',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/160/402351.jpg',
    ep_id: 12510,
    season_no: 2,
    ep_no: 5,
    ep_name: 'Break Point',
    watched: true },
  { user_id: 7,
    tv_id: 172,
    tv_name: 'Suits',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/160/402351.jpg',
    ep_id: 12511,
    season_no: 2,
    ep_no: 6,
    ep_name: 'All In',
    watched: true },
  { user_id: 7,
    tv_id: 172,
    tv_name: 'Suits',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/160/402351.jpg',
    ep_id: 12512,
    season_no: 2,
    ep_no: 7,
    ep_name: 'Sucker Punch',
    watched: true },
  { user_id: 7,
    tv_id: 172,
    tv_name: 'Suits',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/160/402351.jpg',
    ep_id: 12513,
    season_no: 2,
    ep_no: 8,
    ep_name: 'Rewind',
    watched: true },
  { user_id: 7,
    tv_id: 172,
    tv_name: 'Suits',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/160/402351.jpg',
    ep_id: 12514,
    season_no: 2,
    ep_no: 9,
    ep_name: 'Asterisk',
    watched: true },
  { user_id: 7,
    tv_id: 172,
    tv_name: 'Suits',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/160/402351.jpg',
    ep_id: 12515,
    season_no: 2,
    ep_no: 10,
    ep_name: 'High Noon',
    watched: true },
  { user_id: 7,
    tv_id: 172,
    tv_name: 'Suits',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/160/402351.jpg',
    ep_id: 12516,
    season_no: 2,
    ep_no: 11,
    ep_name: 'Blind-Sided',
    watched: true },
  { user_id: 7,
    tv_id: 172,
    tv_name: 'Suits',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/160/402351.jpg',
    ep_id: 12517,
    season_no: 2,
    ep_no: 12,
    ep_name: 'Blood in the Water',
    watched: true },
  { user_id: 7,
    tv_id: 172,
    tv_name: 'Suits',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/160/402351.jpg',
    ep_id: 12518,
    season_no: 2,
    ep_no: 13,
    ep_name: 'Zane vs. Zane',
    watched: true },
  { user_id: 7,
    tv_id: 172,
    tv_name: 'Suits',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/160/402351.jpg',
    ep_id: 12519,
    season_no: 2,
    ep_no: 14,
    ep_name: 'He\'s Back',
    watched: true },
  { user_id: 7,
    tv_id: 172,
    tv_name: 'Suits',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/160/402351.jpg',
    ep_id: 12520,
    season_no: 2,
    ep_no: 15,
    ep_name: 'Normandy',
    watched: true },
  { user_id: 7,
    tv_id: 172,
    tv_name: 'Suits',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/160/402351.jpg',
    ep_id: 12521,
    season_no: 2,
    ep_no: 16,
    ep_name: 'War',
    watched: true },
  { user_id: 7,
    tv_id: 172,
    tv_name: 'Suits',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/160/402351.jpg',
    ep_id: 12522,
    season_no: 3,
    ep_no: 1,
    ep_name: 'The Arrangement',
    watched: true },
  { user_id: 7,
    tv_id: 172,
    tv_name: 'Suits',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/160/402351.jpg',
    ep_id: 12523,
    season_no: 3,
    ep_no: 2,
    ep_name: 'I Want You to Want Me',
    watched: true },
  { user_id: 7,
    tv_id: 172,
    tv_name: 'Suits',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/160/402351.jpg',
    ep_id: 12524,
    season_no: 3,
    ep_no: 3,
    ep_name: 'Unfinished Business',
    watched: true }, { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 414,
    season_no: 1,
    ep_no: 1,
    ep_name: 'Pilot',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 415,
    season_no: 1,
    ep_no: 2,
    ep_name: 'Bears Will Be Bears',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 416,
    season_no: 1,
    ep_no: 3,
    ep_name: 'Beeware',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 417,
    season_no: 1,
    ep_no: 4,
    ep_name: 'Lonelyhearts',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 418,
    season_no: 1,
    ep_no: 5,
    ep_name: 'Danse Macabre',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 419,
    season_no: 1,
    ep_no: 6,
    ep_name: 'The Three Bad Wolves',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 420,
    season_no: 1,
    ep_no: 7,
    ep_name: 'Let Your Hair Down',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 421,
    season_no: 1,
    ep_no: 8,
    ep_name: 'Game Ogre',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 422,
    season_no: 1,
    ep_no: 9,
    ep_name: 'Of Mouse and Man',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 423,
    season_no: 1,
    ep_no: 10,
    ep_name: 'Organ Grinder',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 424,
    season_no: 1,
    ep_no: 11,
    ep_name: 'Tarantella',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 425,
    season_no: 1,
    ep_no: 12,
    ep_name: 'Last Grimm Standing',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 426,
    season_no: 1,
    ep_no: 13,
    ep_name: 'Three Coins in a Fuchsbau',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 427,
    season_no: 1,
    ep_no: 14,
    ep_name: 'Plumed Serpent',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 428,
    season_no: 1,
    ep_no: 15,
    ep_name: 'Island of Dreams',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 429,
    season_no: 1,
    ep_no: 16,
    ep_name: 'The Thing with Feathers',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 430,
    season_no: 1,
    ep_no: 17,
    ep_name: 'Love Sick',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 431,
    season_no: 1,
    ep_no: 18,
    ep_name: 'Cat and Mouse',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 432,
    season_no: 1,
    ep_no: 19,
    ep_name: 'Leave It to Beavers',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 433,
    season_no: 1,
    ep_no: 20,
    ep_name: 'Happily Ever Aftermath',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 434,
    season_no: 1,
    ep_no: 21,
    ep_name: 'Big Feet',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 435,
    season_no: 1,
    ep_no: 22,
    ep_name: 'Woman in Black',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 436,
    season_no: 2,
    ep_no: 1,
    ep_name: 'Bad Teeth',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 437,
    season_no: 2,
    ep_no: 2,
    ep_name: 'The Kiss',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 438,
    season_no: 2,
    ep_no: 3,
    ep_name: 'Bad Moon Rising',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 439,
    season_no: 2,
    ep_no: 4,
    ep_name: 'Quill',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 440,
    season_no: 2,
    ep_no: 5,
    ep_name: 'The Good Shepherd',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 441,
    season_no: 2,
    ep_no: 6,
    ep_name: 'Over My Dead Body',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 442,
    season_no: 2,
    ep_no: 7,
    ep_name: 'The Bottle Imp',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 443,
    season_no: 2,
    ep_no: 8,
    ep_name: 'The Other Side',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 444,
    season_no: 2,
    ep_no: 9,
    ep_name: 'La Llorona',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 445,
    season_no: 2,
    ep_no: 10,
    ep_name: 'The Hour of Death',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 446,
    season_no: 2,
    ep_no: 11,
    ep_name: 'To Protect and Serve Man',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 447,
    season_no: 2,
    ep_no: 12,
    ep_name: 'Season of the Hexenbiest',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 448,
    season_no: 2,
    ep_no: 13,
    ep_name: 'Face Off',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 449,
    season_no: 2,
    ep_no: 14,
    ep_name: 'Natural Born Wesen',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 450,
    season_no: 2,
    ep_no: 15,
    ep_name: 'Mr. Sandman',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 451,
    season_no: 2,
    ep_no: 16,
    ep_name: 'Nameless',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 452,
    season_no: 2,
    ep_no: 17,
    ep_name: 'One Angry Fuchsbau',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 453,
    season_no: 2,
    ep_no: 18,
    ep_name: 'Volcanalis',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 454,
    season_no: 2,
    ep_no: 19,
    ep_name: 'Endangered',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 455,
    season_no: 2,
    ep_no: 20,
    ep_name: 'Kiss of the Muse',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 456,
    season_no: 2,
    ep_no: 21,
    ep_name: 'The Waking Dead',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 457,
    season_no: 2,
    ep_no: 22,
    ep_name: 'Goodnight, Sweet Grimm',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 458,
    season_no: 3,
    ep_no: 1,
    ep_name: 'The Ungrateful Dead',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 459,
    season_no: 3,
    ep_no: 2,
    ep_name: 'PTZD',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 460,
    season_no: 3,
    ep_no: 3,
    ep_name: 'A Dish Best Served Cold',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 461,
    season_no: 3,
    ep_no: 4,
    ep_name: 'One Night Stand',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 462,
    season_no: 3,
    ep_no: 5,
    ep_name: 'El Cucuy',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 463,
    season_no: 3,
    ep_no: 6,
    ep_name: 'Stories We Tell Our Young',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 464,
    season_no: 3,
    ep_no: 7,
    ep_name: 'Cold Blooded',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 465,
    season_no: 3,
    ep_no: 8,
    ep_name: 'Twelve Days of Krampus',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 466,
    season_no: 3,
    ep_no: 9,
    ep_name: 'Red Menace',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 467,
    season_no: 3,
    ep_no: 10,
    ep_name: 'Eyes of the Beholder',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 468,
    season_no: 3,
    ep_no: 11,
    ep_name: 'The Good Soldier',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 469,
    season_no: 3,
    ep_no: 12,
    ep_name: 'The Wild Hunt',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 470,
    season_no: 3,
    ep_no: 13,
    ep_name: 'Revelation',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 471,
    season_no: 3,
    ep_no: 14,
    ep_name: 'Mommy Dearest',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 472,
    season_no: 3,
    ep_no: 15,
    ep_name: 'Once We Were Gods',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 473,
    season_no: 3,
    ep_no: 16,
    ep_name: 'The Show Must Go On',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 474,
    season_no: 3,
    ep_no: 17,
    ep_name: 'Synchronicity',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 475,
    season_no: 3,
    ep_no: 18,
    ep_name: 'The Law of Sacrifice',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 476,
    season_no: 3,
    ep_no: 19,
    ep_name: 'Nobody Knows the Trubel I\'ve Seen',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 477,
    season_no: 3,
    ep_no: 20,
    ep_name: 'My Fair Wesen',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 478,
    season_no: 3,
    ep_no: 21,
    ep_name: 'The Inheritance',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 479,
    season_no: 3,
    ep_no: 22,
    ep_name: 'Blond Ambition',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 480,
    season_no: 4,
    ep_no: 1,
    ep_name: 'Thanks for the Memories',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 15834,
    season_no: 4,
    ep_no: 2,
    ep_name: 'Octopus Head',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 15835,
    season_no: 4,
    ep_no: 3,
    ep_name: 'Last Fight',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 38894,
    season_no: 4,
    ep_no: 4,
    ep_name: 'Dyin\' on a Prayer',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 40377,
    season_no: 4,
    ep_no: 5,
    ep_name: 'Cry Luison',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 481,
    season_no: 4,
    ep_no: 6,
    ep_name: 'Highway of Tears',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 41108,
    season_no: 4,
    ep_no: 7,
    ep_name: 'The Grimm Who Stole Christmas',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 45796,
    season_no: 4,
    ep_no: 8,
    ep_name: 'Chupacabra',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 100857,
    season_no: 4,
    ep_no: 9,
    ep_name: 'Wesenrein',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 109516,
    season_no: 4,
    ep_no: 10,
    ep_name: 'Tribunal',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 117528,
    season_no: 4,
    ep_no: 11,
    ep_name: 'Death Do Us Part',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 118507,
    season_no: 4,
    ep_no: 12,
    ep_name: 'Maréchaussée',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 123091,
    season_no: 4,
    ep_no: 13,
    ep_name: 'Trial by Fire',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 129671,
    season_no: 4,
    ep_no: 14,
    ep_name: 'Bad Luck',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 129672,
    season_no: 4,
    ep_no: 15,
    ep_name: 'Double Date',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 129673,
    season_no: 4,
    ep_no: 16,
    ep_name: 'Heartbreaker',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 129674,
    season_no: 4,
    ep_no: 17,
    ep_name: 'Hibernaculum',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 140693,
    season_no: 4,
    ep_no: 18,
    ep_name: 'Mishipeshu',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 142271,
    season_no: 4,
    ep_no: 19,
    ep_name: 'Iron Hans',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 144059,
    season_no: 4,
    ep_no: 20,
    ep_name: 'You Don\'t Know Jack',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 144060,
    season_no: 4,
    ep_no: 21,
    ep_name: 'Headache',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 144061,
    season_no: 4,
    ep_no: 22,
    ep_name: 'Cry Havoc',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 181896,
    season_no: 5,
    ep_no: 1,
    ep_name: 'The Grimm Identity',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 200216,
    season_no: 5,
    ep_no: 2,
    ep_name: 'Clear and Wesen Danger',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 202016,
    season_no: 5,
    ep_no: 3,
    ep_name: 'Lost Boys',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 202017,
    season_no: 5,
    ep_no: 4,
    ep_name: 'Maiden Quest',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 350684,
    season_no: 5,
    ep_no: 5,
    ep_name: 'The Rat King',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 350687,
    season_no: 5,
    ep_no: 6,
    ep_name: 'Wesen Nacht',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 453281,
    season_no: 5,
    ep_no: 7,
    ep_name: 'Eve of Destruction',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 502656,
    season_no: 5,
    ep_no: 8,
    ep_name: 'A Reptile Dysfunction',
    watched: true },
  { user_id: 7,
    tv_id: 10,
    tv_name: 'Grimm',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg',
    ep_id: 502657,
    season_no: 5,
    ep_no: 9,
    ep_name: 'Star-Crossed',
    watched: true } 
    ])
    .then(() => {
      return knex.raw(`SELECT setval('${table}_id_seq', (SELECT MAX(id) FROM ${table}));`)
    })
};
