const table = 'episodes'
exports.seed = knex => {
  return knex(table)
    .insert([
      { user_id: 8,
    tv_id: 13417,
    tv_name: 'Ozark',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/407569.jpg',
    ep_id: 1183167,
    season_no: 1,
    ep_no: 1,
    ep_name: 'Sugarwood',
    watched: true },
  { user_id: 8,
    tv_id: 13417,
    tv_name: 'Ozark',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/407569.jpg',
    ep_id: 1249842,
    season_no: 1,
    ep_no: 2,
    ep_name: 'Blue Cat',
    watched: true },
  { user_id: 8,
    tv_id: 13417,
    tv_name: 'Ozark',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/407569.jpg',
    ep_id: 1254801,
    season_no: 1,
    ep_no: 3,
    ep_name: 'My Dripping Sleep',
    watched: true },
  { user_id: 8,
    tv_id: 13417,
    tv_name: 'Ozark',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/407569.jpg',
    ep_id: 1254802,
    season_no: 1,
    ep_no: 4,
    ep_name: 'Tonight We Improvise',
    watched: true },
  { user_id: 8,
    tv_id: 13417,
    tv_name: 'Ozark',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/407569.jpg',
    ep_id: 1254803,
    season_no: 1,
    ep_no: 5,
    ep_name: 'Ruling Days',
    watched: true },
  { user_id: 8,
    tv_id: 13417,
    tv_name: 'Ozark',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/407569.jpg',
    ep_id: 1254804,
    season_no: 1,
    ep_no: 6,
    ep_name: 'Book of Ruth',
    watched: true },
  { user_id: 8,
    tv_id: 13417,
    tv_name: 'Ozark',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/407569.jpg',
    ep_id: 1254805,
    season_no: 1,
    ep_no: 7,
    ep_name: 'Nest Box',
    watched: true },
  { user_id: 8,
    tv_id: 13417,
    tv_name: 'Ozark',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/407569.jpg',
    ep_id: 1254806,
    season_no: 1,
    ep_no: 8,
    ep_name: 'Kaleidoscope',
    watched: true },
  { user_id: 8,
    tv_id: 13417,
    tv_name: 'Ozark',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/407569.jpg',
    ep_id: 1254807,
    season_no: 1,
    ep_no: 9,
    ep_name: 'Coffee, Black',
    watched: true },
  { user_id: 8,
    tv_id: 13417,
    tv_name: 'Ozark',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/407569.jpg',
    ep_id: 1254808,
    season_no: 1,
    ep_no: 10,
    ep_name: 'The Toll',
    watched: true },
  { user_id: 8,
    tv_id: 13417,
    tv_name: 'Ozark',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/407569.jpg',
    ep_id: 1479665,
    season_no: 2,
    ep_no: 1,
    ep_name: 'Reparations',
    watched: true },
  { user_id: 8,
    tv_id: 13417,
    tv_name: 'Ozark',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/407569.jpg',
    ep_id: 1518598,
    season_no: 2,
    ep_no: 2,
    ep_name: 'The Precious Blood of Jesus',
    watched: true },
  { user_id: 8,
    tv_id: 13417,
    tv_name: 'Ozark',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/407569.jpg',
    ep_id: 1518988,
    season_no: 2,
    ep_no: 3,
    ep_name: 'Once a Langmore...',
    watched: true },
  { user_id: 8,
    tv_id: 13417,
    tv_name: 'Ozark',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/407569.jpg',
    ep_id: 1518989,
    season_no: 2,
    ep_no: 4,
    ep_name: 'Stag',
    watched: true },
  { user_id: 8,
    tv_id: 13417,
    tv_name: 'Ozark',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/407569.jpg',
    ep_id: 1518990,
    season_no: 2,
    ep_no: 5,
    ep_name: 'Game Day',
    watched: true },
  { user_id: 8,
    tv_id: 13417,
    tv_name: 'Ozark',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/407569.jpg',
    ep_id: 1518991,
    season_no: 2,
    ep_no: 6,
    ep_name: 'Outer Darkness',
    watched: true },
  { user_id: 8,
    tv_id: 13417,
    tv_name: 'Ozark',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/407569.jpg',
    ep_id: 1518992,
    season_no: 2,
    ep_no: 7,
    ep_name: 'One Way Out',
    watched: true },
    { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4245,
    season_no: 1,
    ep_no: 1,
    ep_name: 'Pilot',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4246,
    season_no: 1,
    ep_no: 2,
    ep_name: 'Seeds',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4247,
    season_no: 1,
    ep_no: 3,
    ep_name: 'Fun Town',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4248,
    season_no: 1,
    ep_no: 4,
    ep_name: 'Patch Over',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4249,
    season_no: 1,
    ep_no: 5,
    ep_name: 'Giving Back',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4250,
    season_no: 1,
    ep_no: 6,
    ep_name: 'AK-51',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4251,
    season_no: 1,
    ep_no: 7,
    ep_name: 'Old Bones',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4252,
    season_no: 1,
    ep_no: 8,
    ep_name: 'The Pull',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4253,
    season_no: 1,
    ep_no: 9,
    ep_name: 'Hell Followed',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4254,
    season_no: 1,
    ep_no: 10,
    ep_name: 'Better Half',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4255,
    season_no: 1,
    ep_no: 11,
    ep_name: 'Capybara',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4256,
    season_no: 1,
    ep_no: 12,
    ep_name: 'The Sleep of Babies',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4257,
    season_no: 1,
    ep_no: 13,
    ep_name: 'The Revelator',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4258,
    season_no: 2,
    ep_no: 1,
    ep_name: 'Albification',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4259,
    season_no: 2,
    ep_no: 2,
    ep_name: 'Small Tears',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4260,
    season_no: 2,
    ep_no: 3,
    ep_name: 'Fix',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4261,
    season_no: 2,
    ep_no: 4,
    ep_name: 'Eureka',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4262,
    season_no: 2,
    ep_no: 5,
    ep_name: 'Smite',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4263,
    season_no: 2,
    ep_no: 6,
    ep_name: 'Falx Cerebri',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4264,
    season_no: 2,
    ep_no: 7,
    ep_name: 'Gilead',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4265,
    season_no: 2,
    ep_no: 8,
    ep_name: 'Potlatch',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4266,
    season_no: 2,
    ep_no: 9,
    ep_name: 'Fa Guan',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4267,
    season_no: 2,
    ep_no: 10,
    ep_name: 'Balm',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4268,
    season_no: 2,
    ep_no: 11,
    ep_name: 'Service',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4269,
    season_no: 2,
    ep_no: 12,
    ep_name: 'The Culling',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4270,
    season_no: 2,
    ep_no: 13,
    ep_name: 'Na Trioblóidi',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4271,
    season_no: 3,
    ep_no: 1,
    ep_name: 'SO',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4272,
    season_no: 3,
    ep_no: 2,
    ep_name: 'Oiled',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4273,
    season_no: 3,
    ep_no: 3,
    ep_name: 'Caregiver',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4274,
    season_no: 3,
    ep_no: 4,
    ep_name: 'Home',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4275,
    season_no: 3,
    ep_no: 5,
    ep_name: 'Turning and Turning',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4276,
    season_no: 3,
    ep_no: 6,
    ep_name: 'The Push',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4277,
    season_no: 3,
    ep_no: 7,
    ep_name: 'Widening Gyre',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4278,
    season_no: 3,
    ep_no: 8,
    ep_name: 'Lochan Mor',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4279,
    season_no: 3,
    ep_no: 9,
    ep_name: 'Turas',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4280,
    season_no: 3,
    ep_no: 10,
    ep_name: 'Firinne',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4281,
    season_no: 3,
    ep_no: 11,
    ep_name: 'Bainne',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4282,
    season_no: 3,
    ep_no: 12,
    ep_name: 'June Wedding',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4283,
    season_no: 3,
    ep_no: 13,
    ep_name: 'NS',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4284,
    season_no: 4,
    ep_no: 1,
    ep_name: 'Out',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4285,
    season_no: 4,
    ep_no: 2,
    ep_name: 'Booster',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4286,
    season_no: 4,
    ep_no: 3,
    ep_name: 'Dorylus',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4287,
    season_no: 4,
    ep_no: 4,
    ep_name: 'Una Venta',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4288,
    season_no: 4,
    ep_no: 5,
    ep_name: 'Brick',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4289,
    season_no: 4,
    ep_no: 6,
    ep_name: 'With An X',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4290,
    season_no: 4,
    ep_no: 7,
    ep_name: 'Fruit for the Crows',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4291,
    season_no: 4,
    ep_no: 8,
    ep_name: 'Family Recipe',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4292,
    season_no: 4,
    ep_no: 9,
    ep_name: 'Kiss',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4293,
    season_no: 4,
    ep_no: 10,
    ep_name: 'Hands',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4294,
    season_no: 4,
    ep_no: 11,
    ep_name: 'Call of Duty',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4295,
    season_no: 4,
    ep_no: 12,
    ep_name: 'Burnt and Purged Away',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4296,
    season_no: 4,
    ep_no: 13,
    ep_name: 'To Be, Act 1',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4297,
    season_no: 4,
    ep_no: 14,
    ep_name: 'To Be, Act 2',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4298,
    season_no: 5,
    ep_no: 1,
    ep_name: 'Sovereign',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4299,
    season_no: 5,
    ep_no: 2,
    ep_name: 'Authority Vested',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4300,
    season_no: 5,
    ep_no: 3,
    ep_name: 'Laying Pipe',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4301,
    season_no: 5,
    ep_no: 4,
    ep_name: 'Stolen Huffy',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4302,
    season_no: 5,
    ep_no: 5,
    ep_name: 'Orca Shrugged',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4303,
    season_no: 5,
    ep_no: 6,
    ep_name: 'Small World',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4304,
    season_no: 5,
    ep_no: 7,
    ep_name: 'Toad\'s Wild Ride',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4305,
    season_no: 5,
    ep_no: 8,
    ep_name: 'Ablation',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4306,
    season_no: 5,
    ep_no: 9,
    ep_name: 'Andare Pescare',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4307,
    season_no: 5,
    ep_no: 10,
    ep_name: 'Crucifixed',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4308,
    season_no: 5,
    ep_no: 11,
    ep_name: 'To Thine Own Self',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4309,
    season_no: 5,
    ep_no: 12,
    ep_name: 'Darthy',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4310,
    season_no: 5,
    ep_no: 13,
    ep_name: 'J\'ai Obtenu Cette',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4311,
    season_no: 6,
    ep_no: 1,
    ep_name: 'Straw',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4312,
    season_no: 6,
    ep_no: 2,
    ep_name: 'One One Six',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4313,
    season_no: 6,
    ep_no: 3,
    ep_name: 'Poenitentia',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4314,
    season_no: 6,
    ep_no: 4,
    ep_name: 'Wolfsangel',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4315,
    season_no: 6,
    ep_no: 5,
    ep_name: 'The Mad King',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4316,
    season_no: 6,
    ep_no: 6,
    ep_name: 'Salvage',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4317,
    season_no: 6,
    ep_no: 7,
    ep_name: 'Sweet and Vaded',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4318,
    season_no: 6,
    ep_no: 8,
    ep_name: 'Los Fantasmas',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4319,
    season_no: 6,
    ep_no: 9,
    ep_name: 'John 8:32',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4320,
    season_no: 6,
    ep_no: 10,
    ep_name: 'Huang Wu',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4321,
    season_no: 6,
    ep_no: 11,
    ep_name: 'Aon Rud Persanta',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4322,
    season_no: 6,
    ep_no: 12,
    ep_name: 'You Are My Sunshine',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4323,
    season_no: 6,
    ep_no: 13,
    ep_name: 'A Mother\'s Work',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4324,
    season_no: 7,
    ep_no: 1,
    ep_name: 'Black Widower',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4325,
    season_no: 7,
    ep_no: 2,
    ep_name: 'Toil and Till',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4326,
    season_no: 7,
    ep_no: 3,
    ep_name: 'Playing with Monsters',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4327,
    season_no: 7,
    ep_no: 4,
    ep_name: 'Poor Little Lambs',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4328,
    season_no: 7,
    ep_no: 5,
    ep_name: 'Some Strange Eruption',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4329,
    season_no: 7,
    ep_no: 6,
    ep_name: 'Smoke \'em if You Got \'em',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4330,
    season_no: 7,
    ep_no: 7,
    ep_name: 'Greensleeves',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4331,
    season_no: 7,
    ep_no: 8,
    ep_name: 'The Separation of Crows',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4332,
    season_no: 7,
    ep_no: 9,
    ep_name: 'What A Piece Of Work Is Man',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4333,
    season_no: 7,
    ep_no: 10,
    ep_name: 'Faith and Despondency',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 4334,
    season_no: 7,
    ep_no: 11,
    ep_name: 'Suits of Woe',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 14417,
    season_no: 7,
    ep_no: 12,
    ep_name: 'Red Rose',
    watched: true },
  { user_id: 8,
    tv_id: 76,
    tv_name: 'Sons of Anarchy',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/0/537.jpg',
    ep_id: 15832,
    season_no: 7,
    ep_no: 13,
    ep_name: 'Papa\'s Goods',
    watched: true }, { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4095,
    season_no: 1,
    ep_no: 1,
    ep_name: 'Days Gone Bye',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4096,
    season_no: 1,
    ep_no: 2,
    ep_name: 'Guts',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4097,
    season_no: 1,
    ep_no: 3,
    ep_name: 'Tell It to the Frogs',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4098,
    season_no: 1,
    ep_no: 4,
    ep_name: 'Vatos',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4099,
    season_no: 1,
    ep_no: 5,
    ep_name: 'Wildfire',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4100,
    season_no: 1,
    ep_no: 6,
    ep_name: 'TS-19',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4101,
    season_no: 2,
    ep_no: 1,
    ep_name: 'What Lies Ahead',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4102,
    season_no: 2,
    ep_no: 2,
    ep_name: 'Bloodletting',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4103,
    season_no: 2,
    ep_no: 3,
    ep_name: 'Save the Last One',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4104,
    season_no: 2,
    ep_no: 4,
    ep_name: 'Cherokee Rose',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4105,
    season_no: 2,
    ep_no: 5,
    ep_name: 'Chupacabra',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4106,
    season_no: 2,
    ep_no: 6,
    ep_name: 'Secrets',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4107,
    season_no: 2,
    ep_no: 7,
    ep_name: 'Pretty Much Dead Already',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4108,
    season_no: 2,
    ep_no: 8,
    ep_name: 'Nebraska',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4109,
    season_no: 2,
    ep_no: 9,
    ep_name: 'Triggerfinger',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4110,
    season_no: 2,
    ep_no: 10,
    ep_name: '18 Miles Out',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4111,
    season_no: 2,
    ep_no: 11,
    ep_name: 'Judge, Jury, Executioner',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4112,
    season_no: 2,
    ep_no: 12,
    ep_name: 'Better Angels',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4113,
    season_no: 2,
    ep_no: 13,
    ep_name: 'Beside the Dying Fire',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4114,
    season_no: 3,
    ep_no: 1,
    ep_name: 'Seed',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4115,
    season_no: 3,
    ep_no: 2,
    ep_name: 'Sick',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4116,
    season_no: 3,
    ep_no: 3,
    ep_name: 'Walk with Me',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4117,
    season_no: 3,
    ep_no: 4,
    ep_name: 'Killer Within',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4118,
    season_no: 3,
    ep_no: 5,
    ep_name: 'Say the Word',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4119,
    season_no: 3,
    ep_no: 6,
    ep_name: 'Hounded',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4120,
    season_no: 3,
    ep_no: 7,
    ep_name: 'When the Dead Come Knocking',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4121,
    season_no: 3,
    ep_no: 8,
    ep_name: 'Made to Suffer',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4122,
    season_no: 3,
    ep_no: 9,
    ep_name: 'The Suicide King',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4123,
    season_no: 3,
    ep_no: 10,
    ep_name: 'Home',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4124,
    season_no: 3,
    ep_no: 11,
    ep_name: 'I Ain\'t a Judas',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4125,
    season_no: 3,
    ep_no: 12,
    ep_name: 'Clear',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4126,
    season_no: 3,
    ep_no: 13,
    ep_name: 'Arrow on the Doorpost',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4127,
    season_no: 3,
    ep_no: 14,
    ep_name: 'Prey',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4128,
    season_no: 3,
    ep_no: 15,
    ep_name: 'This Sorrowful Life',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4129,
    season_no: 3,
    ep_no: 16,
    ep_name: 'Welcome to the Tombs',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4130,
    season_no: 4,
    ep_no: 1,
    ep_name: '30 Days Without an Accident',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4131,
    season_no: 4,
    ep_no: 2,
    ep_name: 'Infected',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4132,
    season_no: 4,
    ep_no: 3,
    ep_name: 'Isolation',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4133,
    season_no: 4,
    ep_no: 4,
    ep_name: 'Indifference',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4134,
    season_no: 4,
    ep_no: 5,
    ep_name: 'Internment',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4135,
    season_no: 4,
    ep_no: 6,
    ep_name: 'Live Bait',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4136,
    season_no: 4,
    ep_no: 7,
    ep_name: 'Dead Weight',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4137,
    season_no: 4,
    ep_no: 8,
    ep_name: 'Too Far Gone',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4138,
    season_no: 4,
    ep_no: 9,
    ep_name: 'After',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4139,
    season_no: 4,
    ep_no: 10,
    ep_name: 'Inmates',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4140,
    season_no: 4,
    ep_no: 11,
    ep_name: 'Claimed',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4141,
    season_no: 4,
    ep_no: 12,
    ep_name: 'Still',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4142,
    season_no: 4,
    ep_no: 13,
    ep_name: 'Alone',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4143,
    season_no: 4,
    ep_no: 14,
    ep_name: 'The Grove',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4144,
    season_no: 4,
    ep_no: 15,
    ep_name: 'Us',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4145,
    season_no: 4,
    ep_no: 16,
    ep_name: 'A',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4146,
    season_no: 5,
    ep_no: 1,
    ep_name: 'No Sanctuary',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4147,
    season_no: 5,
    ep_no: 2,
    ep_name: 'Strangers',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 4148,
    season_no: 5,
    ep_no: 3,
    ep_name: 'Four Walls and a Roof',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 14103,
    season_no: 5,
    ep_no: 4,
    ep_name: 'Slabtown',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 15852,
    season_no: 5,
    ep_no: 5,
    ep_name: 'Self Help',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 15853,
    season_no: 5,
    ep_no: 6,
    ep_name: 'Consumed',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 15854,
    season_no: 5,
    ep_no: 7,
    ep_name: 'Crossed',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 15855,
    season_no: 5,
    ep_no: 8,
    ep_name: 'Coda',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 15856,
    season_no: 5,
    ep_no: 9,
    ep_name: 'What Happened and What\'s Going On',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 15857,
    season_no: 5,
    ep_no: 10,
    ep_name: 'Them',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 15858,
    season_no: 5,
    ep_no: 11,
    ep_name: 'The Distance',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 15859,
    season_no: 5,
    ep_no: 12,
    ep_name: 'Remember',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 15860,
    season_no: 5,
    ep_no: 13,
    ep_name: 'Forget',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 15861,
    season_no: 5,
    ep_no: 14,
    ep_name: 'Spend',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 15862,
    season_no: 5,
    ep_no: 15,
    ep_name: 'Try',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 15863,
    season_no: 5,
    ep_no: 16,
    ep_name: 'Conquer',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 185066,
    season_no: 6,
    ep_no: 1,
    ep_name: 'First Time Again',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 185067,
    season_no: 6,
    ep_no: 2,
    ep_name: 'JSS',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 185068,
    season_no: 6,
    ep_no: 3,
    ep_name: 'Thank You',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 185069,
    season_no: 6,
    ep_no: 4,
    ep_name: 'Here\'s Not Here',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 185070,
    season_no: 6,
    ep_no: 5,
    ep_name: 'Now',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 185071,
    season_no: 6,
    ep_no: 6,
    ep_name: 'Always Accountable',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 185072,
    season_no: 6,
    ep_no: 7,
    ep_name: 'Heads Up',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 185073,
    season_no: 6,
    ep_no: 8,
    ep_name: 'Start to Finish',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 384350,
    season_no: 6,
    ep_no: 9,
    ep_name: 'No Way Out',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 483068,
    season_no: 6,
    ep_no: 10,
    ep_name: 'The Next World',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 483069,
    season_no: 6,
    ep_no: 11,
    ep_name: 'Knots Untie',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 628794,
    season_no: 6,
    ep_no: 12,
    ep_name: 'Not Tomorrow Yet',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 638714,
    season_no: 6,
    ep_no: 13,
    ep_name: 'The Same Boat',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 639987,
    season_no: 6,
    ep_no: 14,
    ep_name: 'Twice as Far',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 639988,
    season_no: 6,
    ep_no: 15,
    ep_name: 'East',
    watched: true },
  { user_id: 8,
    tv_id: 73,
    tv_name: 'The Walking Dead',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/166/417471.jpg',
    ep_id: 639999,
    season_no: 6,
    ep_no: 16,
    ep_name: 'Last Day on Earth',
    watched: true }, { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1567,
    season_no: 1,
    ep_no: 1,
    ep_name: 'Pilot',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1568,
    season_no: 1,
    ep_no: 2,
    ep_name: 'Home Invasion',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1569,
    season_no: 1,
    ep_no: 3,
    ep_name: 'Murder House',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1570,
    season_no: 1,
    ep_no: 4,
    ep_name: 'Halloween Part 1',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1571,
    season_no: 1,
    ep_no: 5,
    ep_name: 'Halloween Part 2',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1572,
    season_no: 1,
    ep_no: 6,
    ep_name: 'Piggy, Piggy',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1573,
    season_no: 1,
    ep_no: 7,
    ep_name: 'Open House',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1574,
    season_no: 1,
    ep_no: 8,
    ep_name: 'Rubber Man',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1575,
    season_no: 1,
    ep_no: 9,
    ep_name: 'Spooky Little Girl',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1576,
    season_no: 1,
    ep_no: 10,
    ep_name: 'Smoldering Children',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1577,
    season_no: 1,
    ep_no: 11,
    ep_name: 'Birth',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1578,
    season_no: 1,
    ep_no: 12,
    ep_name: 'Afterbirth',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1579,
    season_no: 2,
    ep_no: 1,
    ep_name: 'Welcome to Briarcliff',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1580,
    season_no: 2,
    ep_no: 2,
    ep_name: 'Tricks and Treats',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1581,
    season_no: 2,
    ep_no: 3,
    ep_name: 'Nor\'easter',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1582,
    season_no: 2,
    ep_no: 4,
    ep_name: 'I Am Anne Frank Part 1',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1583,
    season_no: 2,
    ep_no: 5,
    ep_name: 'I Am Anne Frank Part 2',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1584,
    season_no: 2,
    ep_no: 6,
    ep_name: 'Origins of Monstrosity',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1585,
    season_no: 2,
    ep_no: 7,
    ep_name: 'Dark Cousin',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1586,
    season_no: 2,
    ep_no: 8,
    ep_name: 'Unholy Night',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1587,
    season_no: 2,
    ep_no: 9,
    ep_name: 'The Coat Hanger',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1588,
    season_no: 2,
    ep_no: 10,
    ep_name: 'The Name Game',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1589,
    season_no: 2,
    ep_no: 11,
    ep_name: 'Spilt Milk',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1590,
    season_no: 2,
    ep_no: 12,
    ep_name: 'Continuum',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1591,
    season_no: 2,
    ep_no: 13,
    ep_name: 'Madness Ends',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1592,
    season_no: 3,
    ep_no: 1,
    ep_name: 'Bitchcraft',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1593,
    season_no: 3,
    ep_no: 2,
    ep_name: 'Boy Parts',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1594,
    season_no: 3,
    ep_no: 3,
    ep_name: 'The Replacements',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1595,
    season_no: 3,
    ep_no: 4,
    ep_name: 'Fearful Pranks Ensue',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1596,
    season_no: 3,
    ep_no: 5,
    ep_name: 'Burn, Witch. Burn!',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1597,
    season_no: 3,
    ep_no: 6,
    ep_name: 'The Axeman Cometh',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1598,
    season_no: 3,
    ep_no: 7,
    ep_name: 'The Dead',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1599,
    season_no: 3,
    ep_no: 8,
    ep_name: 'The Sacred Taking',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1600,
    season_no: 3,
    ep_no: 9,
    ep_name: 'Head',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1601,
    season_no: 3,
    ep_no: 10,
    ep_name: 'The Magical Delights of Stevie Nicks',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1602,
    season_no: 3,
    ep_no: 11,
    ep_name: 'Protect the Coven',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1603,
    season_no: 3,
    ep_no: 12,
    ep_name: 'Go to Hell',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1604,
    season_no: 3,
    ep_no: 13,
    ep_name: 'The Seven Wonders',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1605,
    season_no: 4,
    ep_no: 1,
    ep_name: 'Monsters Among Us',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1606,
    season_no: 4,
    ep_no: 2,
    ep_name: 'Massacres and Matinees',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1607,
    season_no: 4,
    ep_no: 3,
    ep_name: 'Edward Mordrake (1)',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1608,
    season_no: 4,
    ep_no: 4,
    ep_name: 'Edward Mordrake (2)',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1609,
    season_no: 4,
    ep_no: 5,
    ep_name: 'Pink Cupcakes',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 11226,
    season_no: 4,
    ep_no: 6,
    ep_name: 'Bullseye',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 14881,
    season_no: 4,
    ep_no: 7,
    ep_name: 'Test of Strength',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 14882,
    season_no: 4,
    ep_no: 8,
    ep_name: 'Blood Bath',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 45257,
    season_no: 4,
    ep_no: 9,
    ep_name: 'Tupperware Party Massacre',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 14883,
    season_no: 4,
    ep_no: 10,
    ep_name: 'Orphans',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 14885,
    season_no: 4,
    ep_no: 11,
    ep_name: 'Magical Thinking',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 14886,
    season_no: 4,
    ep_no: 12,
    ep_name: 'Show Stoppers',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 14887,
    season_no: 4,
    ep_no: 13,
    ep_name: 'Curtain Call',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 202975,
    season_no: 5,
    ep_no: 1,
    ep_name: 'Checking In',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 202976,
    season_no: 5,
    ep_no: 2,
    ep_name: 'Chutes and Ladders',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 202977,
    season_no: 5,
    ep_no: 3,
    ep_name: 'Mommy',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 203248,
    season_no: 5,
    ep_no: 4,
    ep_name: 'Devil\'s Night',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 203249,
    season_no: 5,
    ep_no: 5,
    ep_name: 'Room Service',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 203250,
    season_no: 5,
    ep_no: 6,
    ep_name: 'Room 33',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 203251,
    season_no: 5,
    ep_no: 7,
    ep_name: 'Flicker',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 203252,
    season_no: 5,
    ep_no: 8,
    ep_name: 'The Ten Commandments Killer',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 203253,
    season_no: 5,
    ep_no: 9,
    ep_name: 'She Wants Revenge',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 203254,
    season_no: 5,
    ep_no: 10,
    ep_name: 'She Gets Revenge',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 203255,
    season_no: 5,
    ep_no: 11,
    ep_name: 'Battle Royale',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 203256,
    season_no: 5,
    ep_no: 12,
    ep_name: 'Be Our Guest',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 858583,
    season_no: 6,
    ep_no: 1,
    ep_name: 'Chapter 1',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 878021,
    season_no: 6,
    ep_no: 2,
    ep_name: 'Chapter 2',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 878022,
    season_no: 6,
    ep_no: 3,
    ep_name: 'Chapter 3',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 878023,
    season_no: 6,
    ep_no: 4,
    ep_name: 'Chapter 4',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 878024,
    season_no: 6,
    ep_no: 5,
    ep_name: 'Chapter 5',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 878025,
    season_no: 6,
    ep_no: 6,
    ep_name: 'Chapter 6',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 878026,
    season_no: 6,
    ep_no: 7,
    ep_name: 'Chapter 7',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 878027,
    season_no: 6,
    ep_no: 8,
    ep_name: 'Chapter 8',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 878028,
    season_no: 6,
    ep_no: 9,
    ep_name: 'Chapter 9',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 878029,
    season_no: 6,
    ep_no: 10,
    ep_name: 'Chapter 10',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1255009,
    season_no: 7,
    ep_no: 1,
    ep_name: 'Election Night',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1260245,
    season_no: 7,
    ep_no: 2,
    ep_name: 'Don\'t Be Afraid of the Dark',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1260246,
    season_no: 7,
    ep_no: 3,
    ep_name: 'Neighbors from Hell',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1260247,
    season_no: 7,
    ep_no: 4,
    ep_name: '11/9',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1272037,
    season_no: 7,
    ep_no: 5,
    ep_name: 'Holes',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1272038,
    season_no: 7,
    ep_no: 6,
    ep_name: 'Mid-Western Assassin',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1272039,
    season_no: 7,
    ep_no: 7,
    ep_name: 'Valerie Solanas Died for Your Sins: Scumbag',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1272040,
    season_no: 7,
    ep_no: 8,
    ep_name: 'Winter of Our Discontent',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1272041,
    season_no: 7,
    ep_no: 9,
    ep_name: 'Drink the Kool-Aid',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1272042,
    season_no: 7,
    ep_no: 10,
    ep_name: 'Charles (Manson) in Charge',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1277290,
    season_no: 7,
    ep_no: 11,
    ep_name: 'Great Again',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1486732,
    season_no: 8,
    ep_no: 1,
    ep_name: 'The End',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1516010,
    season_no: 8,
    ep_no: 2,
    ep_name: 'The Morning After',
    watched: true },
  { user_id: 8,
    tv_id: 30,
    tv_name: 'American Horror Story',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/409065.jpg',
    ep_id: 1519873,
    season_no: 8,
    ep_no: 3,
    ep_name: 'Forbidden Fruit',
    watched: true },
    { user_id: 8,
    tv_id: 17118,
    tv_name: 'Mayans M.C.',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/407927.jpg',
    ep_id: 1486731,
    season_no: 1,
    ep_no: 1,
    ep_name: 'Perro/Oc',
    watched: true },
  { user_id: 8,
    tv_id: 17118,
    tv_name: 'Mayans M.C.',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/407927.jpg',
    ep_id: 1513826,
    season_no: 1,
    ep_no: 2,
    ep_name: 'Escorpión/Dzec',
    watched: true },
  { user_id: 8,
    tv_id: 17118,
    tv_name: 'Mayans M.C.',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/407927.jpg',
    ep_id: 1516012,
    season_no: 1,
    ep_no: 3,
    ep_name: 'Búho/Muwan',
    watched: true },
  { user_id: 8,
    tv_id: 17118,
    tv_name: 'Mayans M.C.',
    image:
     'http://static.tvmaze.com/uploads/images/medium_portrait/163/407927.jpg',
    ep_id: 1519901,
    season_no: 1,
    ep_no: 4,
    ep_name: 'Murciélago/Zotz',
    watched: true } 
    ])
    .then(() => {
      return knex.raw(`SELECT setval('${table}_id_seq', (SELECT MAX(id) FROM ${table}));`)
    })
};
